### ISSUE TITLE
3.1 and 3.2 greifing rule confusion

### ISSUE THREAD

**Issue by Cactusinapumpkin** [EarthMC/EarthMC.net#111]
**Exact wording of the rule**
Exactly how the rule should be written on the rules page.
 3.1	Destroying land within 5 chunks of claims.
Players may not damage terrain 5 chunks around claims (griefing).

3.2	Destroying land in wilderness.
Wilderness is defined by Towny as any land not currently claimed. You are allowed to grief structures or terrain as long as they are not within or 5 chunks to a claimed area.

Describe the solution you'd like
Rule change to make new player less likely to break the rule and add more concrete explanation. Make rule clearer and easier to follow.

**How will this rule affect the community**
Write your opinion on why this rule will be better for the community. It will cause less frustration and confusion about what is the appropriate space away from claims especially when the mayor greifed his own land and then someone else thinks that’s where people collect sand.

**Do you think this will benefit both the staff and the players. Yes less warns and less requests to warn and discussion if it in fact it falls under this rule.

Describe the solution you'd like
Rule change to make new player less likely to break the rule and add more concrete explanation. Make rule clearer and easier to follow.

Additional context
3.1	Destroying land around claims.
Players may not damage terrain around claims (griefing).

3.2	Destroying land in wilderness.
Wilderness is defined by Towny as any land not currently claimed. You are allowed to grief structures or terrain as long as they are not within or in close proximity to a claimed area.

I would like to add to add a distance of 5-10 chunks instead of saying around, or in proximity of to avoid confusion of if the mayor greifed his own land and new players thinking it’s an appropriate distance away from the town. Preferably a solid 5 chunks.

**Comment by Cactusinapumpkin** [comment]
I’m sorry I’m trying to do this with a iphone and I hate iphones

**Comment by AmphireYT** [comment]
Please Do this, I got warned for “greifing paris” for breaking rule 3.2. Although the title of 3.2 is “destroying land in wilderness”. I did not hesitate to read it becuase we werent on wilderness. We only read rule 3.1 becuase it had the word claims.

**Comment by KarlOfDuty** [comment]
This is not really relevant anymore as the rules have changed substantially since then.
