### ISSUE TITLE
3.6 Mapart Rule Clarification

### ISSUE THREAD

**Issue by Qorrin** [EarthMC/EarthMC.net#115]
Current Rule: Your map art may not contain nudity, sexual content, racist imagery or anything else that breaks any part of rule 2.

Proposed Rule: Your map art may not contain nudity, **lewd content**, sexual content, racist imagery or anything else that breaks any part of rule 2.

**How will this rule affect the community**
Many moderators are starting to enforce lewd mapart, and are taking a harder stance on what's allowed.  It should be clarified what mapart is approved and how to check if it's approved.  

**Do you think this will benefit both the staff and the players**
It will reduce the number of mapart tickets, reports, and clarify for players what is allowed.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by ghost** [comment]
+1, always good to have clarification

**Comment by SuperChrisBoy** [comment]
+1

**Comment by Qorrin** [comment]
One thing I would like to mention as well is that there are legal issues with lewd mapart, which is why it's being more heavily enforced

**Comment by Fjolnir5** [comment]
Is Lewd any more clear than sexual content? the 2 words are synonymous. dictionary definition of lewd is "crude and offensive in a sexual way.", perhaps a more clear way to word it would be no sexual organs on display? something to that nature

**Comment by Qorrin** [comment]
I like that point @Fjolnir5 , though I think any term is also debatable and subject to abuse :/

**Comment by MrDaneCZE** [comment]
I mean you can always just post the exact definition of what you as the mods and admins see as sexual/lewd

**Comment by Qorrin** [comment]
@MrDaneCZE I agree, they should post that.  That's why I am suggesting for clarification on the rule

**Comment by docwhomc** [comment]
Cause someone accidentally closed it.

**Comment by Qorrin** [comment]
@MrDaneCZE I agree, they should post that. That's why I am suggesting for clarification on the rule

**Comment by AmphireYT** [comment]
I think that a girl with a swim suit is fine at least they clothes have a purpose on why there there. Just having something that covers up the nipples and the private areas is fine. If you are using the clothes for sexual desires, then it shouldn't be allowed. Ex. Panties that are hella small; strings

**Comment by GitMocc** [comment]
As long as like, no actual genitals are shown, nips, etc., the mapart should be allowed. A very thin layer of a color covering the nip should be under **Lewd content,** although, in my opinion, lewd content shouldn't be against the rules.

**Comment by AmphireYT** [comment]
> As long as like, no actual genitals are shown, nips, etc., the mapart should be allowed. A very thin layer of a color covering the nip should be under **Lewd content,** although, in my opinion, lewd content shouldn't be against the rules.

couldnt agree more

**Comment by shirazmatas** [comment]
> One thing I would like to mention as well is that there are legal issues with lewd mapart, which is why it's being more heavily enforced

What legal issues? This is not confirmed by anyone??

The addition of "lewd content" just makes this rule even more vague and based on individual mods own values. One might think tits aren't lewd the other might think ankles are completely lewd

**Comment by jkmartindale** [comment]
> What legal issues? This is not confirmed by anyone??

Many countries have laws against sending (with any method) lewd/obscene content to people below a certain age. That would also cover any sort of art inside games. Disappointingly, many laws are also vague (or dense as hell) about what constitutes "lewd" or "obscene" or whatever terminology they choose to use. Prosecution is also incredibly unlikely unless someone on EarthMC does something massive to attract the attention of the authorities and investigators.

The restrictions proposed in #120 should be sufficient imo.

**Comment by AmphireYT** [comment]
> > What legal issues? This is not confirmed by anyone??
> 
> Many countries have laws against sending (with any method) lewd/obscene content to people below a certain age. That would also cover any sort of art inside games. Disappointingly, many laws are also vague (or dense as hell) about what constitutes "lewd" or "obscene" or whatever terminology they choose to use. Prosecution is also incredibly unlikely unless someone on EarthMC does something massive to attract the attention of the authorities and investigators.
> 
> The restrictions proposed in #120 should be sufficient imo.


Assuming that everyone is 13 and up ( if there nit then it is considered the parents fault) no one is sending maparts to people. They buy with there; they wanted it.

**Comment by jkmartindale** [comment]
> They buy with there; they wanted it.

This defense has not held up in many US courts and in some other countries. If you really want to figure out what boundaries are legal go talk to a lawyer.

But I'm pretty sure banning sexual content from EarthMC isn't based on whatever the minimum is to be in the clear internationally, it's based on what the admins and moderators think would create a suitable player environment. Legal boundaries are not a point worth discussing.

**Comment by AmphireYT** [comment]
> > They buy with there; they wanted it.
> 
> This defense has not held up in many US courts and in some other countries. If you really want to figure out what boundaries are legal go talk to a lawyer.
> 
> But I'm pretty sure banning sexual content from EarthMC isn't based on whatever the minimum is to be in the clear internationally, it's based on what the admins and moderators think would create a suitable player environment. Legal boundaries not a point worth discussing.

This game (minecraft) is pg13 and if you search up “pg 13 anime girls” the second picture is some girl showing off her panties. And if you go Pinterest, your just going to see more.

**Comment by AmphireYT** [comment]
Do this rule instead: https://github.com/EarthMC/EarthMC.net/issues/120

**Comment by captainb4** [comment]
> One thing I would like to mention as well is that there are legal issues with lewd mapart, which is why it's being more heavily enforced

There isn’t I’ll dm you why there is no legal issue at all
