### ISSUE TITLE
Helper Role

### ISSUE THREAD

**Issue by Qorrin** [EarthMC/EarthMC.net#116]
**What's a Helper?**
Basically, a Helper would just be a trial mod.  But, instead of being expected to learn other Mod stuff, they would only focus on moderating the chat, helping new players with commands, reporting things to the Moderators as needed, and overall being a positive influence on the community!

Helpers would have access to the following commands:
- Mute (maybe limited to tempmutes)
- Warn (only for extreme toxicity, n word bypasses, etc.)
- Kick (only in emergencies, such as active griefing)

Any actions taken by Helpers must be recorded, similar to our #staff-actions channel, along with evidence.  Any Moderator can examine a Helpers' actions and determine whether it's too harsh or too lenient, and ask the Helper to adjust the punishment.

**Why do we need Helpers?**
From my experience here, it's clear that the Mods focus heavily on technical issues, like rollbacks and refunds.  This is obviously very necessary, but also has the consequences of Mods not being able to engage with the community on a personal level, and feeling rather disconnected from the staff team.  Many staff are also unable to moderate things like chat, which makes it frustrating for the community due to how toxic it can be at times without being moderated.

I think that having 20 or so Helpers would allow the server to feel a lot more positive and friendly, especially to newer players.  Obviously a bit of rp should be allowed, where nations can be angry at each other, but it has gotten to the point where it can be rather personal and unnecessarily hostile or even sexual at times.  These Helpers would ensure that things don't get out of hand while the other Moderators are busy with technical things.

Thank you for any feedback!

**Comment by DCDylanc123410** [comment]
I think instead they can only mute and report in a separate chat just for helper evidence and actions. Along with this they have a special channel to make reports they see to staff members like prioritized reports. Also they have access to the behavior category in the Support Discord but no other category.  And obviously they have to be approved by mods and admins and they work under the mods and admins. Im saying this cause new mods cant even warn so a helper shouldnt be able  to warn either. I think this would be a nice feature to allow for the people who want to be mods to still be able to help but arent quite qualified to be a mod

**Comment by Conmqn** [comment]
I think this is a very good idea!

**Comment by Conmqn** [comment]
As another thought this could be something like the new mods trial and if they show good results the promotion to mod. Because i  think this would help stop the New mod confusion that people have and will help the server out in the long run.

**Comment by FutureLemon** [comment]
Basically new mods like you get helper before they get mod before?

**Comment by Qorrin** [comment]
@FutureLemon That's basically the idea, yes

**Comment by Camdropz** [comment]
This is the best idea I've seen in a while! Please add this!

**Comment by Taffffy** [comment]
Having helpers to moderate the chat would take a large job off of mods, who could focus on more important things like support ticket backlogs and refunds/rollbacks. I think this is a good idea and it should be implemented.

**Comment by Proserrr** [comment]
Like the idea, but would new mods and helpers both be a thing or would new mods just be renamed to helpers?

**Comment by NeonKrby** [comment]
https://github.com/EarthMC/Issue-Tracker/issues/450

**Comment by Krazy0999** [comment]
> Like the idea, but would new mods and helpers both be a thing or would new mods just be renamed to helpers?

I think they would be separate. So if you applied for mod you'd still be a new mod until you become an official mod, or you could apply for helper and become a helper, and never become a mod, unless you applied separately. So two different roles.

**Comment by Proserrr** [comment]
> EarthMC/Issue-Tracker#450

I can understand Karl’s reasoning in that issue posted over 1 year ago. We could just add more mods to further spread duties and responsibilities to ease the workload. But as more mods are added there are always some becoming more and more inactive. Adding new mods takes months and there are still numerous times where no mods are online and there is no moderation of chat and player behaviour. I think helpers, or something similar to them, would be a welcomed idea among the playerbase.

**Comment by Krazy0999** [comment]
I agree with silver, I also feel like being a mod gives you a lot of power, and the more of this power you give out the more it'll get abused. Power is good, and needed, but on small scales. Giving 50 people the perms of a moderator is asking for abuse of the power and misuse, whereas giving 20 people mod and 30 helper, will not only decrease the workload on mods, but it'll also be easier to moderate the moderators too.

**Comment by Camdropz** [comment]
Krazy5225 has an excellent point. I completely agree.

**Comment by Camdropz** [comment]
Exactly, Krazy5225 & Silverstreet have an important point, and I 100% agree with them. #AddHelpers

**Comment by coblobster2** [comment]
add helpers to help some of the rules get enforced
