### ISSUE TITLE
3.6 Mapart Rule Clarification

### ISSUE THREAD

**Issue by Qorrin** [EarthMC/EarthMC.net#117]
Current Rule: Your map art may not contain nudity, sexual content, racist imagery or anything else that breaks any part of rule 2.

Proposed Rule: Your map art may not contain nudity, lewd content, sexual content, racist imagery or anything else that breaks any part of rule 2.

How will this rule affect the community
Many moderators are starting to enforce lewd mapart, and are taking a harder stance on what's allowed. It should be clarified what mapart is approved and how to check if it's approved.

Do you think this will benefit both the staff and the players
It will reduce the number of mapart tickets, reports, and clarify for players what is allowed.

Please use https://github.com/EarthMC/Issue-Tracker for issues other than the EarthMC.net website

**Comment by Qorrin** [comment]
FUCK I CLOSED THE LAST ONE ON ACCIDENT

**Comment by ghost** [comment]
F, also still agree to this change

**Comment by Fjolnir5** [comment]
This is kind of a repost but i think a good place to look too is the definition of pornography, "printed or visual material containing the explicit description or display of sexual organs or activity, intended to stimulate sexual excitement." note sexual organs/activity. any maps that follow that should be gone, although as an added point I think stuff that is simply "lewd" but not in a legal sense pornography should be allowed. that 2nd bit is only my opinion though.
