### ISSUE TITLE
2.4 Toxicity Rule Modification

### ISSUE THREAD

**Issue by DCDylanc123410** [EarthMC/EarthMC.net#118]
**Exact wording of the rule**
Before:

2.4 Toxicity.
Toxicity is not allowed on this server. Toxicity in chat includes but is not limited to:
- Insulting others.
- Bullying/harassing others.
- Name-calling.
- Vulgar chat, using explicit language, inappropriate content which would be obscene or lewd talk.
- Talking or threatening about self-harm, or other deeply negative experiences.
- Leading or encouraging violence or hatred towards other players.
- Constructing buildings/pixel art that can be considered racist/sexually explicit or containing hate speech/symbols.
- Being malicious, toxic towards the staffs or anyone.
- Messages with sexual characters and sexual harassment.
- Hate Speech, discrimination in any form, such as negative comments related to skin color, race, sex/gender, sexual orientation, disability, religion/beliefs, or other personal qualities.

Toxicity is evaluated on a case by case basis and staff has final say in what is considered toxic behavior. Repeated behavior may lead to warnings, mutes and eventually a permanent ban.

After:

2.4 Toxicity.
Toxicity in any form is not allowed on this server. Toxicity in EMC includes but is not limited to:
- Insulting others.
- Bullying/harassing others.
- Name-calling.
- Vulgar chat, using explicit language, inappropriate content which would be obscene or lewd talk.
- Talking or threatening about self-harm, or other deeply negative experiences.
- Leading or encouraging violence or hatred towards other players.
- Constructing buildings/pixel art/map art that can be considered racist/sexually explicit/suggestive or containing hate speech/symbols.
- Being malicious, toxic towards the staffs or anyone.
- Messages with sexual characters and sexual harassment.
- Hate Speech, discrimination in any form, such as negative comments related to skin color, race, sex/gender, sexual orientation, disability, religion/beliefs, or other personal qualities.

This applies to any of the EMC servers and any of the EMC Official Discords. Toxicity outside of the official discords or server could still lead to punishment depending on a case by case basis.

Toxicity is evaluated on a case by case basis and staff has final say in what is considered toxic behavior. Repeated behavior may lead to warnings, mutes and eventually a permanent ban.

**How will this rule affect the community**
This could really change the community into a positive direction. The addition is small but meaningful. It could allow players to be able to feel more free in EMC and not worried about getting harassed about how they feel in discord and in EMC. I think all of us can agree the community is toxic and I truly believe together we can fight this toxicity and make a change

**Do you think this will benefit both the staff and the players**
This will allow the staff to punish players on Discord for their actions depending on the case instead of having to wait for the harassers to move to EMC. This in turn will make people to scared to be toxic allowing there to be less tickets in total and less punishment on EMC for behavior stuff.  This will help the players by making EMC more fun and more enjoyable because they don't have to worry about being harassed for who they are or what they are doing in EMC

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by captainb4** [comment]
Is the server PG13 or not because it sounds like you want it to be PG but don’t want people to stop cursing in chat. It doesn't make sense to just pick or choose what is "server-allowed" or not.  Lewd is subjective and if it’s a nude map art I do think it should be wiped but if a PG13 image gets wiped for being “lewd” who determines "lewd". The definition of lewd is: crude and offensive in a sexual way. Offensive can vary from person to person. When you start multiplayer on Minecraft you get a disclaimer stating user-made content might be offensive to some. Use Caution. If you want to enforce the rules on Map Art you need to be cautious and be VERY SPECIFIC. The server has bigger issues than mods running around and wiping maps because they are deemed "offensive" without evidence or debate. You have players who say stuff way over PG13. I don't understand this push to PG the server when there are soooooooo many other loop holes. I see players throw the Racial or Homophobic slurs all the time and you all turn a blind eye unless its the N-word. Like wtf?
![AF4CE73E-84CD-406A-A608-03E9A456F5CC](https://user-images.githubusercontent.com/65267219/81769496-61d2b380-94a3-11ea-8548-7ec8fd99a02c.png)

**Comment by solamint** [comment]
lol, imagine wanting to enforce one part of a rule when people are getting bullied to death, literally, which is covered by the same rule

**Comment by niveorum** [comment]
lool dude no offence but thats like the most stupid idea ive ever seen on github

**Comment by sirinfinity** [comment]
This may be very controversial, but ban all forms of swearing and racism (except oriental, that means east. You don't want to ban spaniards do you?)

**Comment by sirinfinity** [comment]
Don't ban people for saying N***** _**with the asterisks**_

**Comment by KarlOfDuty** [comment]
We have just changed the toxicity rules in a direction we felt was better for the server.

**Comment by FutureLemon** [comment]
> We have just changed the toxicity rules in a direction we felt was better for the server.

I don't think it's for the better, this post had 8 thumbs down and no one actually seems to say the rule needs a change. So it seems rather strange to actually change it.

**Comment by captainb4** [comment]
> > We have just changed the toxicity rules in a direction we felt was better for the server.
> 
> I don't think it's for the better, this post had 8 thumbs down and no one actually seems to say the rule needs a change. So it seems rather strange to actually change it.

I think they just want kids to play the server instead bc were harder to deal with (and ppl like toycat) XD

**Comment by DasCodes** [comment]
> I don't think it's for the better, this post had 8 thumbs down and no one actually seems to say the rule needs a change. So it seems rather strange to actually change it.

> I think they just want kids to play the server instead bc were harder to deal with (and ppl like toycat) XD

Karl said `in a direction we felt was better for the server`, never said it was changed according to this issue.

**Comment by docwhomc** [comment]
@DasCodes @KarlOfDuty who is we?

**Comment by nipdip** [comment]
Look, although I think that the current toxicity rules should stay, I don't like the harsh response to this guy's possible change. Please be more mellow.

**Comment by unbatedaura409** [comment]
What made you think this was a good idea? It's had an overwhelmingly negative response from the community. I don't mean to expose anyone, but here's Doc on this recent change: 
![sorrydoc](https://user-images.githubusercontent.com/42659943/82184417-dabb7c00-98a4-11ea-9e56-9db0900fa9e4.PNG)
And then here's a few examples of mods breaking this rule without punishment: 
![pussies](https://user-images.githubusercontent.com/42659943/82184929-a98f7b80-98a5-11ea-81b3-1fc52b18ec6e.png)
![yellowretard](https://user-images.githubusercontent.com/42659943/82184938-adbb9900-98a5-11ea-8771-fad8098582b5.png)
![karlretard](https://user-images.githubusercontent.com/42659943/82184952-b1e7b680-98a5-11ea-97d4-513b0d0b41e4.png)
![BUHLYON](https://user-images.githubusercontent.com/42659943/82185031-d0e64880-98a5-11ea-9921-0784b3984007.PNG)

**Comment by unbatedaura409** [comment]
Also, I think I should add this diagram someone made a while ago. It perfectly represents the way EMC has been going over the past half a year, maybe more. Take a look.
![downwardspiral](https://user-images.githubusercontent.com/42659943/82185457-77324e00-98a6-11ea-8fe7-c1254c220a2f.png)

**Comment by DasCodes** [comment]
> @DasCodes @KarlOfDuty who is we?

@docwhomc The administration.

**Comment by 10op10** [comment]
> > @DasCodes @KarlOfDuty who is we?
> 
> @docwhomc The administration.

Why do you never listen to the players? Everyone including most mods think this rule is bullshit, the only opinions you ask for is Eagles and Karl's, how about you listen to the players for once and see what they want and listen to suggestions too?

**Comment by docwhomc** [comment]
Since this issue has been turned into a referendum on the new rule.

**Comment by KarlOfDuty** [comment]
Make a new rule suggestion in that case, this one had been denied.

**Comment by DasCodes** [comment]
@10op10 What do you mean never listen to players? The new rules are literally made for players so they don't get punished by staff for saying words like "pussy", "retard".

**Comment by DasCodes** [comment]
Which is far less strict than the previous rule we had.

**Comment by 10op10** [comment]
> @10op10 What do you mean never listen to players? The new rules are literally made for players so they don't get punished by staff for saying words like "pussy", "retard".

But the players don't want to be punished for saying words like that, all you have to do is look at how many people have disliked this rule

**Comment by DasCodes** [comment]
Exactly my point. Read what I wrote.

**Comment by docwhomc** [comment]
> Make a new rule suggestion in that case, this one had been denied.

@KarlOfDuty According to your own justification for removing the cooking rules channel, "the administration" should have opened up that issue before making the changes.

**Comment by 10op10** [comment]
> Exactly my point. Read what I wrote.

If your saying you are allowing people to say pussy, why is it still filtered in the chat?

**Comment by DasCodes** [comment]
Would you prefer something not being sent to the chat or getting warned by mods?

**Comment by captainb4** [comment]
> > Exactly my point. Read what I wrote.
> 
> If your saying you are allowing people to say pussy, why is it still filtered in the chat?

I’m more focused on the map art side ppl are getting stuff stolen from them the imagines that there complainIng about is pg13. this shit is fucked there punishing the ppl that pay for ranks and spend like 20h on map art. if they want a cookie cutter server it’s fine we can leave they need us more than we need them.

**Comment by 10op10** [comment]
> Would you prefer something not being sent to the chat or getting warned by mods?

I'd prefer no restriction at all tbh, some words I get like the n-word or whore or even pussy, but muting players for saying "retard" is utter bullshit

**Comment by captainb4** [comment]
> > Would you prefer something not being sent to the chat or getting warned by mods?
> 
> I'd prefer no restriction at all tbh, some words I get like the n-word or whore or even pussy, but muting players for saying "retard" is utter bullshit. 

Just a theory but I think there’s a kid YouTube channel coming to emc and that’s why there trying to clean things up on emc

**Comment by 10op10** [comment]
> > > Would you prefer something not being sent to the chat or getting warned by mods?
> > 
> > 
> > I'd prefer no restriction at all tbh, some words I get like the n-word or whore or even pussy, but muting players for saying "retard" is utter bullshit.
> 
> Just a theory but I think there’s a kid YouTube channel coming to emc and that’s why there trying to clean things up on emc

But most players don't want that 
![image](https://user-images.githubusercontent.com/63156735/82190643-3ad41180-98e9-11ea-92c8-0c444b6ce8af.png)
As you can tell by the dislikes

**Comment by DasCodes** [comment]
@10op10 The new rules weren't made according to this issue. I understand you're thinking it is because Karl commented on this issue on the new rules being changed. Take a look at the new rules, you'll understand.
https://github.com/EarthMC/EarthMC.net/commit/90a5767df536837b8a4136f8775d3693db977d33

**Comment by captainb4** [comment]
> > > > Would you prefer something not being sent to the chat or getting warned by mods?
> > > 
> > > 
> > > I'd prefer no restriction at all tbh, some words I get like the n-word or whore or even pussy, but muting players for saying "retard" is utter bullshit.
> > 
> > 
> > Just a theory but I think there’s a kid YouTube channel coming to emc and that’s why there trying to clean things up on emc
> 
> But most players don't want that
> ![image](https://user-images.githubusercontent.com/63156735/82190643-3ad41180-98e9-11ea-92c8-0c444b6ce8af.png)
> As you can tell by the dislikes

So I think we need to have a talk with the higher ups about this issue like a almost debate if we have civilized discourse we might solve this without ya know half the community quitting

**Comment by 10op10** [comment]
> @10op10 The new rules weren't made according to this issue. I understand you're thinking it is because Karl commented on this issue on the new rules being changed. Take a look at the new rules, you'll understand.
> [90a5767](https://github.com/EarthMC/EarthMC.net/commit/90a5767df536837b8a4136f8775d3693db977d33)

What exactly is considered "Explicit forms of bullying" it will still cause mods to make mistakes because mods each have their own interpretation of the rule, like I got muted for saying retard, yet I called a mod retarded and the other mods have no issue this is part of the issue, the rule isn't clear enough

**Comment by docwhomc** [comment]
> Make a new rule suggestion in that case, this one had been denied.

Done: #126

**Comment by DasCodes** [comment]
@10op10 Any kind of bullies that makes a player quit the server type of bullies.

**Comment by 10op10** [comment]
> @10op10 Any kind of bullies that makes a player quit the server type of bullies.

Then why am I being penalised for calling a player retarded? I called them it once, they aren't going to quit the server because some random player said "your a retard" if people are getting offended they shouldn't be playing video games at all. Also if they feel bullied all they have to do is either ignore it or just turn off the screen.

**Comment by DasCodes** [comment]
That's why the new rule changes to make it more lenient?

**Comment by DasCodes** [comment]
I'm not able to understand your issue. Are you suggesting to go back to the stricter rule or have the one which is far less restricted?

**Comment by 10op10** [comment]
> I'm not able to understand your issue. Are you suggesting to go back to the stricter rule or have the one which is far less restricted?

Far less restricted

**Comment by captainb4** [comment]
> I'm not able to understand your issue. Are you suggesting to go back to the stricter rule or have the one which is far less restricted?

The problem isn’t rly ppl curseing and shit in chat mods are wiping ppls map arts they spend days on even though there pg13 images

**Comment by DasCodes** [comment]
I don't know any non-NSFW map art which was wiped.

**Comment by 10op10** [comment]
> I don't know any non-NSFW map art which was wiped.

The belle delphine map art was wiped

**Comment by DasCodes** [comment]
Idk what that is, feel free to send me the image in discord. But let's not fill this issue about a different subject.

**Comment by captainb4** [comment]
> > I don't know any non-NSFW map art which was wiped.
> 
> The belle delphine map art was wiped

Mine was to, the problem Is that emc staff doesn’t get that ppl playing arnt just kids there 15-20 year olds typically and if there not going to allow pg13 map art don’t allow pg13 chat

**Comment by solamint** [comment]
@KarlOfDuty @DasCodes can you guys PLEASE FUCKING CHOOSE A DEMOGRAPHIC. you have 8 YEAR-OLDS HERE ON THE SERVER, MIXED WITH 14-18 YEAR-OLDS. Fix the rules and enforce them. I thought this would be a nice server to join because of what I saw in the rules, and as it turns out, it's even worse than what the rules made it sound. Your broken rules are worse than any other site ever, and even Club Penguin Online (shut down due to child predators) had better moderating power than this. Stop simping to the children and make the server for the people who use it. Change it for the players, not for your "WE". I know I broke GitHub's guidelines, but this is fucking REDICULOUS. Maybe actually play your server for a while and interact, then you can find what's been told to you all along. Slap a big fat warning when first joining the server that the server is 13+, or put it in the server's description. All you did was restate 2.4 in a way that makes it 0.1% more clearer. Minecraft isn't just a "kids game", and the server's community isn't for "kids". Yet you are trying to force it to children. Stop trying to groom little children, and actually HELP US.

**Comment by captainb4** [comment]
> @KarlOfDuty @DasCodes can you guys PLEASE FUCKING CHOOSE A DEMOGRAPHIC. you have 8 YEAR-OLDS HERE ON THE SERVER, MIXED WITH 14-18 YEAR-OLDS. Fix the rules and enforce them. I thought this would be a nice server to join because of what I saw in the rules, and as it turns out, it's even worse than what the rules made it sound. Your broken rules are worse than any other site ever, and even Club Penguin Online (shut down due to child predators) had better moderating power than this. Stop simping to the children and make the server for the people who use it. Change it for the players, not for your "WE". I know I broke GitHub's guidelines, but this is fucking REDICULOUS. Maybe actually play your server for a while and interact, then you can find what's been told to you all along. Slap a big fat warning when first joining the server that the server is 13+, or put it in the server's description. All you did was restate 2.4 in a way that makes it 0.1% more clearer. Minecraft isn't just a "kids game", and the server's community isn't for "kids". Yet you are trying to force it to children. Stop trying to groom little children, and actually HELP US.

Thank you

**Comment by solamint** [comment]
THERE'S EVEN A NIGGER COCK MAPART EVERYWHERE, and mods don't care. Suprising.

**Comment by solamint** [comment]
[Here's the image.](https://user-images.githubusercontent.com/43187285/82255373-80f99700-9922-11ea-968e-ea44e12b0653.png)
