### ISSUE TITLE
Server rating rule

### ISSUE THREAD

**Issue by Nalasleafheart** [EarthMC/EarthMC.net#119]
**Exact wording of the rule**

If the server is PG-13:
Server Rating 
EMC is a PG-13 rated server. This means all content not suitable for teens is prohibited. Prohibited content includes but is not limited to:
- Excessive cursing, slurs and lewd chat.
- Overly sexual or nsfw imagery (anything that you can't wear or do in public)

If the server is PG
Server Rating 
EMC is a PG rated server. This means all content not suitable for younger children is prohibited. Prohibited content includes but is not limited to:
- Insults, cursing and slurs in chat
- Any forms of sexual or suggestive chat or imagery 
-  Violence and guns
- Content or chat relating to gruesome or "adult" topics 

**How will this rule affect the community**
It leaves a clear cut understanding of what is and isnt allowed on the server. There is a big disconnect between mods and players on what exactly is allowed and isnt allowed.

**Do you think this will benefit both the staff and the players**
No one knows what Fix or Karl exactly want on the server for the community leaving both mods and players to argue about what's right and wrong. Keeping a rule or statement on the site or server keeps everyone on the same page and it wont lead to misunderstanding or fights between staff and players. It gives a clear understanding for everyone and doesnt allow some things to be accepted and others on the same level not to be. 

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by IJustGotKarma** [comment]
+1

**Comment by solamint** [comment]
I agree. It also helps target a certain demographic, and can, in the long run, stop these massive spikes of young children being exposed to what they shouldn't be playing. You hear "Earth server" and you'd think its a "for everyone" thing, but it isn't. A lot of what in this server is not PG, as there are tons of "adult" topics in the server, slurs, insults, violence, and even racism. If this is ever adopted, it should and will most likely be PG-13. I feel like the rules cut out a huge chunk of this, and never even mention what to expect.

**Comment by GitMocc** [comment]
+1

**Comment by AmphireYT** [comment]
+1

**Comment by shirazmatas** [comment]
There can possibly a legal issue with using the labels "pg-13" or "pg" as you can't use them without actually being rated by Motion Picture Association of America. Also if anything as the server is hosted in Europe PEGI guidelines would be a better fit

**Comment by Nalasleafheart** [comment]
> There can possibly a legal issue with using the labels "pg-13" or "pg" as you can't use them without actually being rated by Motion Picture Association of America. Also if anything as the server is hosted in Europe PEGI guidelines would be a better fit

if there is indeed a legal issue with using those labels, it could be reworded to these,
for something that'd be "pg-13" - EMC is a 13+ server. This means all content not suitable for teens is prohibited. Prohibited content includes but is not limited to:
and for "pg" it could be reworded to -  EMC is a server for all ages(or 7+ could be there instead). This means all content not suitable for younger children is prohibited. Prohibited content includes but is not limited to:

**Comment by KarlOfDuty** [comment]
This doesn't really make any sense, why would we put a random movie rating on the server? What would that even mean?
