### ISSUE TITLE
[Rule change] revamp of rule 3.6 [Finished]

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/EarthMC.net#120]
**Exact wording of the rule**
previous

> 3.6 Map art.
Creating map art is allowed as long as it does not interfere with other towns. It is recommended to place map art in Antarctica as there is a lot of unused space there. If you place it outside of Antarctica you will have to claim the area as it will count as proximity greifing if the other towns around you don't like it.

Your map art may not contain nudity, sexual content, racist imagery or anything else that breaks any part of rule 2. 

New:

3.6 Map art.
Creating map art is allowed as long as it does not interfere with other towns. It is recommended to place map art in Antarctica as there is a lot of unused space there. If you place it outside of Antarctica you will have to claim the area as it will count as proximity greifing if the other towns around you don't like it.

Your map art may not contain sexual content (showing simulated and unsimulated [sexual acts](https://books.google.se/books?id=VEM0L4lu4NoC&pg=PA76&lpg=PA76&dq=A+sexual+act+means+(A)+contact+between+the+penis+and+the+vulva+or+the+penis+and+the+anus,+and+for+purposes+of+this+subparagraph+contact+involving+the+penis+occurs+upon+penetration,+however+slight;+(B)+contact+between+the+mouth+and+the+penis,+the+mouth+and+the+vulva,+or+the+mouth+and+the+anus;+(C)+the+penetration,+however+slight,+of+the+anal+or+genital+opening+of+another+by+a+hand+or+finger+or+by+any+object,+with+an+intent+to+abuse,+humiliate,+harass,+degrade,+or+arouse+or+gratify+the+sexual+desire+of+any+person;+or+(D)+the+intentional+touching,+not+through+the+clothing,+of+the+genitalia+of+another+person+who+has+not+attained+the+age+of+16+years+with+an+intent+to+abuse,+humiliate,+harass,+degrade,+or+arouse+or+gratify+the+sexual+desire+of+any+person.&source=bl&ots=Rb2iGk0YxS&sig=ACfU3U0Bk70eD6xdBE3FeGwOUrIXNy7-3Q&hl=sv&sa=X&ved=2ahUKEwi0jsqLoLnpAhXlAxAIHfywADEQ6AEwAHoECAgQAQ#v=onepage&q=A%20sexual%20act%20means%20(A)%20contact%20between%20the%20penis%20and%20the%20vulva%20or%20the%20penis%20and%20the%20anus%2C%20and%20for%20purposes%20of%20this%20subparagraph%20contact%20involving%20the%20penis%20occurs%20upon%20penetration%2C%20however%20slight%3B%20(B)%20contact%20between%20the%20mouth%20and%20the%20penis%2C%20the%20mouth%20and%20the%20vulva%2C%20or%20the%20mouth%20and%20the%20anus%3B%20(C)%20the%20penetration%2C%20however%20slight%2C%20of%20the%20anal%20or%20genital%20opening%20of%20another%20by%20a%20hand%20or%20finger%20or%20by%20any%20object%2C%20with%20an%20intent%20to%20abuse%2C%20humiliate%2C%20harass%2C%20degrade%2C%20or%20arouse%20or%20gratify%20the%20sexual%20desire%20of%20any%20person%3B%20or%20(D)%20the%20intentional%20touching%2C%20not%20through%20the%20clothing%2C%20of%20the%20genitalia%20of%20another%20person%20who%20has%20not%20attained%20the%20age%20of%2016%20years%20with%20an%20intent%20to%20abuse%2C%20humiliate%2C%20harass%2C%20degrade%2C%20or%20arouse%20or%20gratify%20the%20sexual%20desire%20of%20any%20person.&f=false), full nudity, visible reproduction organs, nipples are allowed if the mapart is based on an artwork displayed or formerly displayed on a museum), racist imagery, or break any of the following points
- Explicit forms of bullying.
- Repetitive use of derogatory terms.
- Comments encouraging self-harm.
- Inciting violence or explicit forms of hate speech against racial and social minorities.

**How will this rule affect the community**
less vagueness, less authoritarian approach to map arts.

**Do you think this will benefit both the staff and the players**
Less tickets and confusion
**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**
Leave suggestions to change this below, this is preliminary

**Comment by benbenyatta** [comment]
IMO this rule clarifies way more than the one proposed by Qorrin. This one lays out CLEAR guidelines to which maparts would be allowed and which would not be allowed. Strongly supporting this one, gj Shiraz

**Comment by MrDaneCZE** [comment]
solid proposal, except for the "sexual acts" part which is still bit too unspecific (but we already talked about this in my ticket) other than that 100% better rule that the current one

**Comment by sirinfinity** [comment]
delete the map art that says N*gger Cock

**Comment by AmphireYT** [comment]
Yes I agree with this abd if anyone would like to argue with me feel free

**Comment by Qorrin** [comment]
@FenZenyatta I agree, I was proposing to simply add things that are now being enforced, but this goes way more  in depth and clarifies it better

**Comment by GitMocc** [comment]
+1

**Comment by solamint** [comment]
I mean, anything can be considered a "sexual act". That's the big problem with this, which sucks.

**Comment by AmphireYT** [comment]
> I mean, anything can be considered a "sexual act". That's the big problem with this, which sucks.

A sexual act means (A) contact between the penis and the vulva or the penis and the anus, and for purposes of this subparagraph contact involving the penis occurs upon penetration, however slight; (B) contact between the mouth and the penis, the mouth and the vulva, or the mouth and the anus; (C) the penetration, however slight, of the anal or genital opening of another by a hand or finger or by any object, with an intent to abuse, humiliate, harass, degrade, or arouse or gratify the sexual desire of any person; or (D) the intentional touching, not through the clothing, of the genitalia of another person who has not attained the age of 16 years with an intent to abuse, humiliate, harass, degrade, or arouse or gratify the sexual desire of any person.

Idk whats so hard about it.

**Comment by shirazmatas** [comment]
> > I mean, anything can be considered a "sexual act". That's the big problem with this, which sucks.
> 
> A sexual act means (A) contact between the penis and the vulva or the penis and the anus, and for purposes of this subparagraph contact involving the penis occurs upon penetration, however slight; (B) contact between the mouth and the penis, the mouth and the vulva, or the mouth and the anus; (C) the penetration, however slight, of the anal or genital opening of another by a hand or finger or by any object, with an intent to abuse, humiliate, harass, degrade, or arouse or gratify the sexual desire of any person; or (D) the intentional touching, not through the clothing, of the genitalia of another person who has not attained the age of 16 years with an intent to abuse, humiliate, harass, degrade, or arouse or gratify the sexual desire of any person.
> 
> Idk whats so hard about it.

This exactly, the "sexual acts" part can be hyperlinked to lead to this definition.

**Comment by shirazmatas** [comment]
I have updated the rule definition based on the feedback received, I will leave the debate open until Sunday in which I will rename the ticket to [finished]

**Comment by ketchupdrinker** [comment]
> nipples are allowed if the art is part of a museum
I'm not sure what this means, does this entail that male/female nipples can only be shown if the map art is based of a painting in an art museum?
Male nipples as well aren't considered nudity, so am I allowed to show male chests in map art?

**Comment by shirazmatas** [comment]
> 
> 
> > nipples are allowed if the art is part of a museum
> > I'm not sure what this means, does this entail that male/female nipples can only be shown if the map art is based of a painting in an art museum?
> > Male nipples as well aren't considered nudity, so am I allowed to show male chests in map art?

I changed the sentence in my original post. Yes both male and female nipples would be banned unless the mapart is based on a real artistic piece like the "Liberty Leading the People". Do you believe it should be different?

**Comment by ketchupdrinker** [comment]
I mean male nipples aren't considered nudity by all western media networks, aswell as all western cultures this explains why mens swimsuits don't have tops, it doesn't really make sense to me why this would be bannable since I was considering making Ricardo Milos map art

**Comment by shirazmatas** [comment]
> 
> 
> I mean male nipples aren't considered nudity by all western media networks, aswell as all western cultures this explains why mens swimsuits don't have tops, it doesn't really make sense to me why this would be bannable since I was considering making Ricardo Milos map art

the point of this rule suggestion was to make an indiscriminate rule update which would not be affected by geographically based views on sexuality.

**Comment by coblobster2** [comment]
So why did this rule fail so much?
