### ISSUE TITLE
[Rule change] New Rule: 1.6 - Item duplication

### ISSUE THREAD

**Issue by nipdip** [EarthMC/EarthMC.net#125]
1.6 Item duplication
      The intentional duplication of items is banned, due to the problems it faces toward the economy and the lag-friendliness of the server. All item duping is bannable(unless approved by a staff member) except for the following:

 - Carpet duping
              
**How will this new rule affect the community?**
Multiple scandals have appeared on the server involving the duplication of gold and valuables, which could potentially destroy the economy, and TNT duping flying machines pose a dangerous threat to EarthMCs normally lag-friendly environment, and to the wilderness terrain surrounding towns. New players must know that item duping on the server is forbidden, and that we have rules for a reason.

**How it will benefit both players and staff**
First of all, staff will have a better method to tell new players that item duping is forbidden. By making it an official rule, no one will want to dupe items. Second, players are testing technologies all of the time on EarthMC, and even without duping, they will inevitably find other, more benevolent solutions to solve their problems. Plus, it will make the server more balanced, as nations with item dupers could become unstoppable forces able to destroy their vanilla opponents with ease using item dupers.

Please tell me what you think of this potential new rule! Think of potential other dupers that shouldn't be bannable, and tell me about these potential dupers. As long as they don't cause imbalance, disrupt the economy, or create substantial lag, they're fair game. Feel free to remove dupers from the lest of non-bannables as well.

**Please use https://github.com/EarthMC/Issue-Tracker for issues other than the EarthMC.net website**

**Comment by GRAnimated** [comment]
there's been a few mods ingame that said TNT duping wasn't allowed but at the same time stuff like this are said so i'm not sure if TNT duping is or isn't allowed
![image](https://user-images.githubusercontent.com/23510999/89116626-31783100-d464-11ea-8690-cfc99c0f3496.png)

**Comment by Proserrr** [comment]
“Unwritten” or hidden rules like this need to be made more clear in my opinion.

**Comment by 32Red** [comment]
is tnt duping allowed for terra forming?

**Comment by BusDuster** [comment]
> is tnt duping allowed for terra forming?

Not quite... 

Best to just dig and mine the old fasion way.. 

"3.5 Major terraforming
In order to preserve the accurate geography of the map, major terraforming of the natural terrain is not allowed. In general, if your edits of the landscape alter the Dynmap view of the natural landscape, they will be removed. Examples of this includes for instance draining large lakes/rivers, creating artificial islands which do not exist in real life, or covering the ocean with platforms. Usually vertical terraforming is allowed as it does not change the dynmap view."
