### ISSUE TITLE
Consensus on item duplication

### ISSUE THREAD

**Issue by nipdip** [EarthMC/EarthMC.net#129]
**Exact wording of the rule**
Item duplication, in any form, is illegal and bannable, except for the following dupers:
- Carpet duping
- Rail duping

**How will this rule affect the community**
Currently, the server has no consensus on item duplication. I believe that if the server got an official rule about item duping, whether as part of `1.3 or as an entirely new rule(1.6), new players like myself would be less prone to duplication. Plus, gold duplication can break the economy, and TNT duping can cause immense lag and destroy terrain, especially when used in mass. Others though, like carpet and rail duping, are more benign, and thus should be allowed.

**Do you think this will benefit both the staff and the players**
Staff members would have a better method of conveying the rules on item duplication than discord, which is unreliable as some players won't listen and dupe thinking its legal. Plus, banning some forms of duping but legalizing others helps the playerbase and increases balance and infrastructure. By not letting players dupe gold and TNT, we can prevent unstoppable nations from forming using TNT and gold dupers to destroy their opponents, and preventing players from causing immense lag and kicking players from the server.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by Oln123** [comment]
I agree it is confusing to new players when there is not clearly stated exceptions to this rule. When I say carpet and rail duping Is allowed a lot of people rightfully wont trust me because im not a mod.

**Comment by 10op10** [comment]
> **Exact wording of the rule**
> Item duplication, in any form, is illegal and bannable, except for the following dupers:
> 
> * Carpet duping
> * Rail duping
> 
> **How will this rule affect the community**
> Currently, the server has no consensus on item duplication. I believe that if the server got an official rule about item duping, whether as part of `1.3 or as an entirely new rule(1.6), new players like myself would be less prone to duplication. Plus, gold duplication can break the economy, and TNT duping can cause immense lag and destroy terrain, especially when used in mass. Others though, like carpet and rail duping, are more benign, and thus should be allowed.
> 
> **Do you think this will benefit both the staff and the players**
> Staff members would have a better method of conveying the rules on item duplication than discord, which is unreliable as some players won't listen and dupe thinking its legal. Plus, banning some forms of duping but legalizing others helps the playerbase and increases balance and infrastructure. By not letting players dupe gold and TNT, we can prevent unstoppable nations from forming using TNT and gold dupers to destroy their opponents, and preventing players from causing immense lag and kicking players from the server.
> 
> **Please use https://github.com/EarthMC/Issue-Tracker for issues other than the EarthMC.net website**

Carpet duping is allowed and also explosion revert is on so it restores the terrain

**Comment by FutureLemon** [comment]
Why would you dupe rails when there's a good alternative to make powered rails: 
![image](https://user-images.githubusercontent.com/44688587/82731188-5f732380-9d05-11ea-8833-d8b9232ad4e3.png)
Just go read the FAQ page on the website. https://earthmc.net/faq.html
