### ISSUE TITLE
[Rule] Ban Scamming

### ISSUE THREAD

**Issue by NeonKrby** [EarthMC/EarthMC.net#13]
I recently got scammed by ThonkingThatcher, I payed him 32 gold to make a town in China so i could up my soon to found nations chunk bonus, The moment i gave him the gold he ran away and made a town in Australia, I would like there to be a rule against scamming because it would make it so no one has to worry about being scammed

**Comment by johnyuki** [comment]
You're just too trusting...

**Comment by KarlOfDuty** [comment]
As @johnyuki stated above, scammers is just something you have to deal with when giving people things. As stealing is also not against the rules it doesn't make any sense to ban scammers.
