### ISSUE TITLE
Politics rule suggestion 

### ISSUE THREAD

**Issue by ghost** [EarthMC/EarthMC.net#131]
**Exact wording of the rule**
Exactly how the rule should be written on the rules page.
Real-life politics and controversial issues are not allowed in EarthMC chat. 
**How will this rule affect the community**
Write your opinion on why this rule will be better for the community.
There would be less racism and toxicity in the chat.
**Do you think this will benefit both the staff and the players**
Describe how both parties will benefit from this rule.
The players will not have to see people arguing politics and generally ripping on other people's countries, and the staff will not have to warn as many people for being toxic.
**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by MineHero43** [comment]
This makes no sense at all, why restrict people from having open discussions about real life political matters on a server that is based around virtual geopolitics..? These discussions aren’t inherently “racist” or “toxic” either

**Comment by ghost** [comment]
> This makes no sense at all, why restrict people from having open discussions about real life political matters on a server that is based around virtual geopolitics..? These discussions aren’t inherently “racist” or “toxic” either

Because no one is actually discussing politics. People are only making fun of other countries for things. And yes, the "discussions" are inherently racist and toxic when they start out with people saying "the United States sucks" or "white people deserve to die" and shit like that is all that is being said. People right now are saying "justice for george" but no one is discussing it, they just say it then continue to talk about how white people suck. 

Same thing with the "political discussions" people have about controversial topics that they likely only know what they've seen on the news. They start out saying just bullshit like "Trump is racist, why didn't he ban travel earlier to stop covid" then that already creates toxicity for people telling them what an idiot they are, and if anyone tries to discuss it they go on and dismiss the points so they can talk about how racist Trump and white people are.

And this doesn't only happen for white people and people who live in America. I have seen many people talk about different countries and just talk crap about different people or the country in general. There are never actual discussions. 

Your first statement also makes no sense at all. Why restrict people discussing real life politics on a game based on virtual geopolitics? You answered your own question. The server is based on VIRTUAL geopolitics. Not real life politics. There are absolutely no real discussions about real life politics in the chat that aren't toxic or meant to be slander against another country or leader. Anyone who says otherwise is just dumb or lying

**Comment by FutureLemon** [comment]
Ah yes, a rule to remove freedom of speech even more...

**Comment by jkmartindale** [comment]
will somebody pleeease think of the poor wypipo

**Comment by jkmartindale** [comment]
It's a totally fair point that a lot of the political discussion that happens in EarthMC is more bait than debate, but that kind of toxic behavior should theoretically be covered by the toxicity rule. Adding politics and "controversial issues" to the list of unwanted behavior doesn't even clarify much because both categories are rather subjective.

I'd support something that adds to the Unwanted Behavior section toxic behavior that political discussion can bring. But a blanket ban is overreacting.

**Comment by KarlOfDuty** [comment]
Basically everything is political somewhere, this doesn't make a lot of sense.
