### ISSUE TITLE
Toxic politics rule suggestion 

### ISSUE THREAD

**Issue by ghost** [EarthMC/EarthMC.net#132]
**Exact wording of the rule**
Exactly how the rule should be written on the rules page.
Any real-life politics discussions that are meant to demean or disrespect someone's culture, personal beliefs, country, or country's leader are considered toxic behavior and are not allowed.

**How will this rule affect the community**
Write your opinion on why this rule will be better for the community.
Well since it's obvious that everyone thinks that making it against the rules to talk about politics (even though no one actually discusses politics) shouldn't be done, I think it would be beneficial to make it so the only way people can actually talk about politics, is how they should be discussed in the first place. Karl closed my other post before too many people could comment, but one great comment from jkmartindale did show up.

 "It's a totally fair point that a lot of the political discussion that happens in EarthMC is more bait than debate, but that kind of toxic behavior should theoretically be covered by the toxicity rule. Adding politics and "controversial issues" to the list of unwanted behavior doesn't even clarify much because both categories are rather subjective.

I'd support something that adds to the Unwanted Behavior section toxic behavior that political discussion can bring. But a blanket ban is overreacting."

Obviously people will comment that people will be offended by politics whether or not it is "toxic" but if someone actually wants to talk about politics then there is an obvious point people cross where it goes from normal politics discussion to bait and toxicity, and it's not hard for people or staff to tell where the line is.

This rule would affect the community by making it so blatant toxic political chat is gone from the server and normal decent political behavior is allowed, even though it doesn't happen either way.

**Do you think this will benefit both the staff and the players**
Describe how both parties will benefit from this rule.
I get told by my town's citizens daily that the toxic political chat is annoying and some have gone as far as to turn off their chat entirely. We shouldn't be accepting toxic chat if it turns people away from EMC, and that's why this rule would benefit the players. As for the staff, this rule would benefit them because with this rule in place, they wouldn't have to be annoyed by toxicity in the chat.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by MineHero43** [comment]
Why are people such snowflakes and offended by “toxic” debates, it’s just a chat, Jesus Christ. Add a chat filter to filter out specific racist words but other than that it’s free and open discussion. If you’re offended and genuinely incapable of just ignoring it, turn off chat.

It actually is pretty hard to tell where the supposed line is.

This rule that you’re proposing is so subjective as well, granting mods the power to label whatever political discussion they disagree with as “unwanted behaviour” where do you draw the line? What is your definition of a toxic political debate?

What people discuss shouldn’t be regulated as long as it’s not blatant bullying, homophobia etc. Political discussions don’t fall into that category at all. Could you perhaps name some specific examples of past discussions that have triggered you to propose this ‘rule’?

This is clearly just a minority of underaged players who have never been exposed to open online debates before who are calling for the chat to be restricted to suit their needs. 

The vast majority of players couldn’t care less about what’s said in chat, frankly I’m sure most find it entertaining.

When you join minecraft multiplayer a warning pops up on your screen which mentions that there may be adult content on minecraft servers, everyone has to click yes and agree that they’re aware. If you’re still offended then maybe you should look for servers that are designed specifically for more underaged audiences.

**Comment by ghost** [comment]
You sure talk a lot for someone who hardly plays anymore minehero

Tell me if you can see the difference between these two sentences.

Why did Donald Trump take so long to close the borders during this pandemic?
Donald Trump is retarded for not closing the borders sooner.

If you want to try and give me a better example you think would fit here, then feel free to try and I will tell you where it becomes toxic.

Speaking of toxic, cool your jets Bucko, just trying to have a discussion here, no need to call me triggered or a snowflake. It's still Minecraft no matter how you look at it and people don't want to see garbage in the chat.

**Comment by MineHero43** [comment]
“Someone who hardly plays anymore” are you high? I’m online almost everyday but irrelevant point. I’d never even heard of who you are until I saw this and your previous post. Pretty bad first impression imo

You want to punish someone for saying “Donald Trump is a retard for not closing the border”?

I think everyone reading this will see how absurd your proposal is just by your example you gave

There’s nothing wrong or toxic about that sentence at all. Only someone looking for a bone to pick would find that upsetting.

You really need to get your priorities straight

**Comment by ghost** [comment]
> “Someone who hardly plays anymore” are you high? I’m online almost everyday but irrelevant point. I’d never even heard of who you are until I saw this and your previous post.

lmao just shows how out of touch you really are with the EMC community, I built the Gherkin in your own town. You hardly ever talk on EMC. There's no way you've not ever seen me on EMC or on a discord, so now you're just saying stuff to be annoying.

Why are you so adamant about letting toxic behavior be allowed in the chat? You hardly even chat at all, and I have never seen you talk about politics once so this wouldn't even affect you.

Saying things like Trump is a retard for any reason is not only toxic in itself, but it is also inviting toxic chat and behavior. This isn't even politics at this point, it's just toxicity and for some reason, you have no problem with it.

**Comment by MineHero43** [comment]
> > “Someone who hardly plays anymore” are you high? I’m online almost everyday but irrelevant point. I’d never even heard of who you are until I saw this and your previous post.
> 
> lmao just shows how out of touch you really are with the EMC community, I built the Gherkin in your own town. You hardly ever talk on EMC. There's no way you've not ever seen me on EMC or on a discord, so now you're just saying stuff to be annoying.
> 
> Why are you so adamant about letting toxic behavior be allowed in the chat? You hardly even chat at all, and I have never seen you talk about politics once so this wouldn't even affect you.
> 
> Saying things like Trump is a retard for any reason is not only toxic in itself, but it is also inviting toxic chat and behavior. This isn't even politics at this point, it's just toxicity and for some reason, you have no problem with it.

I totally didn’t debate Coronavirus and other subjects for an hour in chat recently. I’ve engaged in many political debates on the server. Just shows how much you’re talking out of your ass, making stuff up as you go along. I’ve never heard of who you are, you’re clearly irrelevant or just easily forgettable. Fun fact: You didn’t build the Gherkin in London.

Your definition of toxicity is so skewed and wrong. The rules were already changed before to give players more freedom as to what they can say and prevent stupid warns over words such as “retard”

Going by your rule we could just label anything we don’t like as toxic and demand mods warn people over it. It’s a trashy subjective rule that has no place on the server.

You’re clearly underaged and haven’t been on the internet for too long if you’re upset about the word “retard” being used to define politicians.

If you want to experience real toxicity go play 2b2t and then come back and tell me that “Donald Trump is a retard for not closing the borders” is toxic.

It’s not toxic, stop being a snowflake, it doesn’t harm anyone, ignore it. Simple as.

**Comment by jkmartindale** [comment]
> meant to demean or disrespect someone's...country, or country's leader are considered toxic behavior

bruh I still want to be able to say Xi Jinping looks like Winnie the Pooh, this hurts nobody except maybe his oppressive regime

<img src="https://user-images.githubusercontent.com/11380394/83470353-322e2000-a43f-11ea-82cb-1c14fc7d6f07.png" title="Doesn't he tho?" width="50%" height="50%"/>

**Comment by ghost** [comment]
>I’ve never heard of who you are, you’re clearly irrelevant or just easily forgettable. Fun fact: You didn’t build the Gherkin in London.

> You’re clearly underaged and haven’t been on the internet for too long if you’re upset about the word “retard” being used to define politicians.
>
> If you want to experience real toxicity go play 2b2t and then come back and tell me that “Donald Trump is a retard for not closing the borders” is toxic.
> 
> It’s not toxic, stop being a snowflake, ignore it. Simple as.


Lmao get a mod to show you who placed the blocks for the gherkin if you're this stupid. 
I am not underage, but thanks for making the argument that you think anything that happens on the internet should be allowed on EMC. I am doing this because I have gotten complaints from my citizens about the toxicity in chat revolving around politics. Also, every time there is a toxic debate around politics in chat someone always says "Can we keep politics off a block game" and someone always replies "This is a geopolitical block game" and I have said this before but since you have some sort of dementia I will say it again, it's a Virtual geopolitical server. The geopolitics are based on the actual server itself.

Also nice job comparing EMC to 2b2t, as if we should be more like 2b2t. I am from anarchy servers so I know toxicity when I see it buddy. Just because it's on another server or on the internet doesn't mean we should have it on EMC.

**Comment by MineHero43** [comment]
> > I’ve never heard of who you are, you’re clearly irrelevant or just easily forgettable. Fun fact: You didn’t build the Gherkin in London.
> 
> > You’re clearly underaged and haven’t been on the internet for too long if you’re upset about the word “retard” being used to define politicians.
> > If you want to experience real toxicity go play 2b2t and then come back and tell me that “Donald Trump is a retard for not closing the borders” is toxic.
> > It’s not toxic, stop being a snowflake, ignore it. Simple as.
> 
> Lmao get a mod to show you who placed the blocks for the gherkin if you're this stupid.
> I am not underage, but thanks for making the argument that you think anything that happens on the internet should be allowed on EMC. I am doing this because I have gotten complaints from my citizens about the toxicity in chat revolving around politics. Also, every time there is a toxic debate around politics in chat someone always says "Can we keep politics off a block game" and someone always replies "This is a geopolitical block game" and I have said this before but since you have some sort of dementia I will say it again, it's a Virtual geopolitical server. The geopolitics are based on the actual server itself.
> 
> Also nice job comparing EMC to 2b2t, as if we should be more like 2b2t. I am from anarchy servers so I know toxicity when I see it buddy. Just because it's on another server or on the internet doesn't mean we should have it on EMC.

Clearly you can’t read, when did I say that everything that’s allowed on the internet should be allowed on emc?

I said if you want to experience real toxicity then go play 2b2t and come back and try and argue that emc is toxic. Not a comparison at all, in fact the opposite.

Your citizens need to learn to mind their own business and ignore whatever it is so long as it’s not directed at them, which I’m sure it isn’t.

I highly doubt you even know what the word toxic means since you’re just throwing it around left and right, constantly crying wolf.

Obviously when you’ve got people role playing as country leaders, politicians etc you’re going to get debates about their real life counterparts, historical events etc. That’s just how it is, to try and censor that would be completely absurd.

Your citizens are clearly in the minority, they’re clearly underaged. No one is harmed by political discussions, you’ve clearly got a bone to pick.

Let the mods punish actual rule breaking and not waste their time on cherry picking whatever you don’t like that’s being discussed at a given time.

**Comment by pesetz** [comment]
retard is toxic ban ban ban ban ;(((((((

**Comment by ghost** [comment]
> I highly doubt you even know what the word toxic means since you’re just throwing it around left and right, constantly crying wolf.

Tell me what you think toxic means on EarthMC because to me it seems like you think it only applies to when people are using racial slurs or telling people to off themselves

**Comment by ghost** [comment]
> retard is toxic ban ban ban ban ;(((((((

actually, according to the rules, using the word retard often isn't allowed

"Repetitive use of derogatory terms."

**Comment by MineHero43** [comment]
> > I highly doubt you even know what the word toxic means since you’re just throwing it around left and right, constantly crying wolf.
> 
> Tell me what you think toxic means on EarthMC because to me it seems like you think it only applies to when people are using racial slurs or telling people to off themselves

That’s exactly what it should be. Blatant racism or homophobia for the sake of it. I’d argue bullying as well although that’s more subjective and what counts as bullying varies from person to person.

Utilising words such as “retard” to emphasise on a point being made is not toxic whatsoever, no one is harmed by it. Especially when it’s in the context of a political discussion.

To be specific, toxicity is the excessive use of hostile language, threats and swearing all directed at a particular individual. Essentially what we’d consider cyberbullying.

**Comment by ghost** [comment]
> Utilising words such as “retard” to emphasize* on a point being made is not toxic whatsoever, no one is harmed by it. Especially when it’s in the context of a political discussion.

Okay maybe retard was a bad adjective for the subject, but you do agree though that racism, homophobia and bullying should not be allowed in the chat, and that there is what 90% of these "political" discussions devolve into and mods do nothing about it.

**Comment by MineHero43** [comment]
> > Utilising words such as “retard” to emphasize* on a point being made is not toxic whatsoever, no one is harmed by it. Especially when it’s in the context of a political discussion.
> 
> Okay maybe retard was a bad adjective for the subject, but you do agree though that racism, homophobia and bullying should not be allowed in the chat, and that there is what 90% of these "political" discussions devolve into and mods do nothing about it.

Blatant racism and homophobia are already punishable and have been ever since the server was made. There’s nothing new about that.

It’s simply false to state that a majority of political discussions evolve into racist or homophobic flame wars. In fact I’ve never seen one do so.
Sure, debates naturally get heated but from my experience there’s always an underlying sense of civility.

**Comment by ghost** [comment]
> To be specific, toxicity is the excessive use of hostile language, threats and swearing all directed at a particular individual. Essentially what we’d consider cyberbullying.

Why in your opinion is something only toxic if it is directed at a particular individual? If I said something like "India is a piece of shit country" how would that not be toxic? Or even "All white people deserve to die" while racist, that isn't directed toward any one person

**Comment by ghost** [comment]
> It’s simply false to state that a majority of political discussions evolve into racist or homophobic flame wars. In fact I’ve never seen one do so.

Give me one minute, I will find one that has happened in chat

**Comment by MineHero43** [comment]
> > To be specific, toxicity is the excessive use of hostile language, threats and swearing all directed at a particular individual. Essentially what we’d consider cyberbullying.
> 
> Why in your opinion is something only toxic if it is directed at a particular individual? If I said something like "India is a piece of shit country" how would that not be toxic? Or even "All white people deserve to die" while racist, that isn't directed toward any one person

There’s nothing toxic about that, it’s just an opinion which could be considered offensive by some. They then have the right to challenge that opinion. Frankly India is a shit country so I don’t see the problem in pointing it out..

**Comment by MineHero43** [comment]
But you see you’re proving my point. This rule you’re proposing is so subjective and can be interpreted in so many ways by so many different people.

What one person considers “toxic” another person doesn’t even pay attention to.

Not to mention it would be essentially unenforceable by mods

**Comment by ghost** [comment]
> > > To be specific, toxicity is the excessive use of hostile language, threats and swearing all directed at a particular individual. Essentially what we’d consider cyberbullying.
> > 
> > 
> > Why in your opinion is something only toxic if it is directed at a particular individual? If I said something like "India is a piece of shit country" how would that not be toxic? Or even "All white people deserve to die" while racist, that isn't directed toward any one person
> 
> There’s nothing toxic about that, it’s just an opinion which could be considered offensive by some. Frankly India is a shit country so I don’t see the problem in pointing it out..

There's no point in even talking to you anymore if you're this delusional and opinionated, have fun being a keyboard warrior in future comments Mr. racist

**Comment by MineHero43** [comment]
> > > > To be specific, toxicity is the excessive use of hostile language, threats and swearing all directed at a particular individual. Essentially what we’d consider cyberbullying.
> > > 
> > > 
> > > Why in your opinion is something only toxic if it is directed at a particular individual? If I said something like "India is a piece of shit country" how would that not be toxic? Or even "All white people deserve to die" while racist, that isn't directed toward any one person
> > 
> > 
> > There’s nothing toxic about that, it’s just an opinion which could be considered offensive by some. Frankly India is a shit country so I don’t see the problem in pointing it out..
> 
> There's no point in even talking to you anymore if you're this delusional and opinionated, have fun being a keyboard warrior in future comments Mr. racist

Just call everyone you disagree with racist, kek. Maybe your proposal to label political discussions as “toxic” and then using that as a pretext to censor them would receive more support in the Chinese edition of Minecraft. Goodnight boio

**Comment by ghost** [comment]
"Frankly India is a shit country so I don’t see the problem in pointing it out.."
> Just call everyone you disagree with racist, kek. 

btw you got real quiet about that whole gherkin thing once I told you to get mods to show you I built it

**Comment by MineHero43** [comment]
> "Frankly India is a shit country so I don’t see the problem in pointing it out.."
> 
> > Just call everyone you disagree with racist, kek.
> 
> btw you got real quiet about that whole gherkin thing once I told you to get mods to show you I built it

I’m not allowed to say that India is shit? Am I racist just because Indians just so happen to be brown? I think many countries are shit, India is just one. Doesn’t make me racist against brown people.

Your Gherkin point was just pulled out of your ass. You went from saying I don’t play anymore to then saying that I don’t talk in chat to then saying that I don’t participate in debates.

All of it was false, pulled out of your behind to distract from the debate. Now you’ve got no arguments left so you just pull the race card and call it a day, no surprise there.

You’re clearly out looking for some bones to pick, your proposed ‘rule’ is an absolute subjective mess and this entire discussion has proven that and as I explained above, it would be completely unenforceable.

**Comment by ghost** [comment]
> > "Frankly India is a shit country so I don’t see the problem in pointing it out.."
> > > Just call everyone you disagree with racist, kek.
> > 
> > 
> > btw you got real quiet about that whole gherkin thing once I told you to get mods to show you I built it
> 
> I’m not allowed to say that India is shit? Am I racist just because Indians just so happen to be brown? I think many countries are shit, India is just one. Doesn’t make me racist against brown people.
> 
> Your Gherkin point was just pulled out of your ass. You went from saying I don’t play anymore to then saying that I don’t talk in chat to then saying that I don’t participate in debates.
> 
> All of it was false, pulled out of your behind, now you’ve got no arguments left so you just pull the race card and call it a day, no surprise there.

hey, I could argue with your bullshit arguments all day, I just don't see any point because you'll just keep pulling shit out of your ass and calling it an argument. You should go on America's got talent because you've got a talent for saying the same garbage over and over again. "Completely unenforceable" It would be easily enforceable. Any time a political argument happens people would just look at it and if people start getting hostile and as to your definition "toxic" then mods would do something about it.

My Gherkin point was not pulled out of my ass, you said you didn't know who I was so I told you I was the one who built the giant glass dildo in your town. If you don't believe me go to a mod and ask them to see who placed the blocks

**Comment by MineHero43** [comment]
> > > "Frankly India is a shit country so I don’t see the problem in pointing it out.."
> > > > Just call everyone you disagree with racist, kek.
> > > 
> > > 
> > > btw you got real quiet about that whole gherkin thing once I told you to get mods to show you I built it
> > 
> > 
> > I’m not allowed to say that India is shit? Am I racist just because Indians just so happen to be brown? I think many countries are shit, India is just one. Doesn’t make me racist against brown people.
> > Your Gherkin point was just pulled out of your ass. You went from saying I don’t play anymore to then saying that I don’t talk in chat to then saying that I don’t participate in debates.
> > All of it was false, pulled out of your behind, now you’ve got no arguments left so you just pull the race card and call it a day, no surprise there.
> 
> hey, I could argue with your bullshit arguments all day, I just don't see any point because you'll just keep pulling shit out of your ass and calling it an argument. You should go on America's got talent because you've got a talent for saying the same garbage over and over again. "Completely unenforceable" It would be easily enforceable. Any time a political argument happens people would just look at it and if people start getting hostile and as to your definition "toxic" then mods would do something about it.
> 
> My Gherkin point was not pulled out of my ass, you said you didn't know who I was so I told you I was the one who built the giant glass dildo in your town. If you don't believe me go to a mod and ask them to see who placed the blocks

No, your proposal would be absolutely unenforceable as everyone interprets a toxic political debate differently from the person sitting next to them. You’re blowing this out of proportion.

My definition of toxicity is already what’s enforced and punished on the server. You’re clearly uninformed. If someone is spamming racist or homophobic slurs, they’ll be punished accordingly. There’s nothing new about that.

Stop whining about political discussions in chat, just ignore them if you’re such a snowflake.

If your way of contending with being on the losing side is by lashing out and insulting me then sure, go all out. At least come up with original insults please.

This is all pretty embarrassing considering you said you played on anarchy servers..

**Comment by ghost** [comment]
> No it would be absolutely unenforceable as everyone interprets a toxic political debate differently from the person sitting next to them. You’re blowing this out of proportion.
> 
> Stop whining about political discussions in chat, just ignore them if you’re such a snowflake.

As I just said, when a political discussion goes over the line into what you consider "Toxic" behavior, that is when mods would step in. You're not getting this and you were the one who described toxic behavior 

You keep saying that "snowflake" term as if I am personally offended by everything. I just want to make it so people on emc can enjoy the chat without having to see bullshit.

Bud, you gotta stop editing your messages after you've posted them, just get everything you want to say out and then post it, this isn't a popcorn discussion

Are you saying that everyone on anarchy servers has to be a toxic retard who yells slurs in the chat nonstop? You can do that all you like on anarchy servers, but some of us actually build communities and make friends

**Comment by MineHero43** [comment]
> > No it would be absolutely unenforceable as everyone interprets a toxic political debate differently from the person sitting next to them. You’re blowing this out of proportion.
> > Stop whining about political discussions in chat, just ignore them if you’re such a snowflake.
> 
> As I just said, when a political discussion goes over the line into what you consider "Toxic" behavior, that is when mods would step in. You're not getting this and you were the one who described toxic behavior
> 
> You keep saying that "snowflake" term as if I am personally offended by everything. I just want to make it so people on emc can enjoy the chat without having to see bullshit.
> 
> Bud, you gotta stop editing your messages after you've posted them, just get everything you want to say out and then post it, this isn't a popcorn discussion
> 
> Are you saying that everyone on anarchy servers has to be a toxic retard who yells slurs in the chat nonstop? You can do that all you like on anarchy servers, but some of us actually build communities and make friends

You’ve completely abandoned your original point.
Now you’re saying it should be based on my definition of toxicity which is “blatant racism and homophobia for the sake of it.”

“toxicity is the excessive use of hostile language, threats and swearing all directed at a particular individual. Essentially what we’d consider cyberbullying.“

If someone is spamming racist, homophobic slurs or blatantly outright bullying someone in chat, they will be punished accordingly. There’s  nothing new about that. You should really inform yourself more.

My point about you playing on anarchy servers is that I’d expect you to know what real toxicity is and know that there’s nothing toxic about “Donald Trump is a retard”

**Comment by ghost** [comment]
> You’ve completely abandoned your original point.
> Now you’re saying it should be based on my definition of toxicity which is “blatant racism and homophobia for the sake of it.”
> 
> If someone is spamming racist or homophobic slurs, they will be punished accordingly, there’s nothing new about that. You should really inform yourself more.
> 
> My point about you playing on anarchy servers is that I’d expect you to know what real toxicity is and know that there’s nothing toxic about “Donald Trump is a retard”


I am trying to put it in terms you can understand, that's why I am putting in terms of your definition of toxicity.

People say racist and homophobic slurs every day and mods hardly ever do anything about it, you just ignore it so you wouldn't even care, but some people don't actually like seeing racism in chat.

Toxicity isn't only based on your definition by the way, it can be interpreted in multiple ways. This conversation is actually going nowhere, congrats, you've stopped a conversation because you feel the need to keyboard warrior everything you see. Maybe talk in chat more and stop ignoring everything and you will see.

Lastly, make sure to get a mod to check the gherkin! I built it!

**Comment by MineHero43** [comment]
> > You’ve completely abandoned your original point.
> > Now you’re saying it should be based on my definition of toxicity which is “blatant racism and homophobia for the sake of it.”
> > If someone is spamming racist or homophobic slurs, they will be punished accordingly, there’s nothing new about that. You should really inform yourself more.
> > My point about you playing on anarchy servers is that I’d expect you to know what real toxicity is and know that there’s nothing toxic about “Donald Trump is a retard”
> 
> I am trying to put it in terms you can understand, that's why I am putting in terms of your definition of toxicity.
> 
> People say racist and homophobic slurs every day and mods hardly ever do anything about it, you just ignore it so you wouldn't even care, but some people don't actually like seeing racism in chat.
> 
> Toxicity isn't only based on your definition by the way, it can be interpreted in multiple ways. This conversation is actually going nowhere, congrats, you've stopped a conversation because you feel the need to keyboard warrior everything you see. Maybe talk in chat more and stop ignoring everything and you will see.
> 
> Lastly, make sure to get a mod to check the gherkin! I built it!

“It can be interpreted in multiple ways” well you just completely destroyed your entire point with that one phrase. Further proving that it would be unenforceable due to how subjective it is.

I’ll head out for the night, you’ve got no arguments left and you’re just lashing out like a little child at this point anyway

**Comment by ghost** [comment]
> > > You’ve completely abandoned your original point.
> > > Now you’re saying it should be based on my definition of toxicity which is “blatant racism and homophobia for the sake of it.”
> > > If someone is spamming racist or homophobic slurs, they will be punished accordingly, there’s nothing new about that. You should really inform yourself more.
> > > My point about you playing on anarchy servers is that I’d expect you to know what real toxicity is and know that there’s nothing toxic about “Donald Trump is a retard”
> > 
> > 
> > I am trying to put it in terms you can understand, that's why I am putting in terms of your definition of toxicity.
> > People say racist and homophobic slurs every day and mods hardly ever do anything about it, you just ignore it so you wouldn't even care, but some people don't actually like seeing racism in chat.
> > Toxicity isn't only based on your definition by the way, it can be interpreted in multiple ways. This conversation is actually going nowhere, congrats, you've stopped a conversation because you feel the need to keyboard warrior everything you see. Maybe talk in chat more and stop ignoring everything and you will see.
> > Lastly, make sure to get a mod to check the gherkin! I built it!
> 
> “It can be interpreted in multiple ways” well you just completely destroyed your entire point with that one phrase. Further proving that it would be unenforceable due to how subjective it is.
> 
> I’ll head out for the night, you’ve got no arguments left and you’re just lashing out like a little child at this point anyway

Lmao lashing out like a little child, that's golden. Coming from the guy who comments on things that don't have anything to do with him and wouldn't affect him in any way, who proceeds to call people names based on their opinions and keeps commenting the same stale points no matter what is said. Next time I know to just ignore your retarded comments. For fucks sakes, you're more talkative on the github than the actual server. You've said more in this thread than you've said this whole year on emc
Comment more if you want, but I won't be replying or looking at your arguments so it will only be for the sake of your own retardation if you do reply. You're obviously too unintelligent and unempathetic to even think about someone else's opinion on anything. Mark Twain once said "Never argue with a fool, onlookers may not be able to tell the difference."

**Comment by GitMocc** [comment]
i hate hearing liberal nonsense in chat

**Comment by MineHero43** [comment]
> > > > You’ve completely abandoned your original point.
> > > > Now you’re saying it should be based on my definition of toxicity which is “blatant racism and homophobia for the sake of it.”
> > > > If someone is spamming racist or homophobic slurs, they will be punished accordingly, there’s nothing new about that. You should really inform yourself more.
> > > > My point about you playing on anarchy servers is that I’d expect you to know what real toxicity is and know that there’s nothing toxic about “Donald Trump is a retard”
> > > 
> > > 
> > > I am trying to put it in terms you can understand, that's why I am putting in terms of your definition of toxicity.
> > > People say racist and homophobic slurs every day and mods hardly ever do anything about it, you just ignore it so you wouldn't even care, but some people don't actually like seeing racism in chat.
> > > Toxicity isn't only based on your definition by the way, it can be interpreted in multiple ways. This conversation is actually going nowhere, congrats, you've stopped a conversation because you feel the need to keyboard warrior everything you see. Maybe talk in chat more and stop ignoring everything and you will see.
> > > Lastly, make sure to get a mod to check the gherkin! I built it!
> > 
> > 
> > “It can be interpreted in multiple ways” well you just completely destroyed your entire point with that one phrase. Further proving that it would be unenforceable due to how subjective it is.
> > I’ll head out for the night, you’ve got no arguments left and you’re just lashing out like a little child at this point anyway
> 
> Lmao lashing out like a little child, that's golden. Coming from the guy who comments on things that don't have anything to do with him and wouldn't affect him in any way, who proceeds to call people names based on their opinions and keeps commenting the same stale points no matter what is said. Next time I know to just ignore your retarded comments. For fucks sakes, you're more talkative on the github than the actual server. You've said more in this thread than you've said this whole year on emc
> Comment more if you want, but I won't be replying or looking at your arguments so it will only be for the sake of your own retardation if you do reply. You're obviously too unintelligent and unempathetic to even think about someone else's opinion on anything. Mark Twain once said "Never argue with a fool, onlookers may not be able to tell the difference."

Idk where you get your argument from that I never talk in chat and that this rule would have no effect on me. Just shows how uninformed you are and your lack of general knowledge.

You talk a whole load about toxic debates yet throughout this GitHub you’ve proven that you’re incapable of holding a normal and civil discussion. You resort to cussing and insulting when you’re in the wrong, very cool.

Of course the rule would impact me. I’m a player..? I have a right to comment wherever I want to, wether you like it or not.

**Comment by Oln123** [comment]
Among others the big issue with this is defining politics.
Like is it talking about political issues ? If so then That can be a lot.
Is it talking about Politicians ? If so U wouldn't be able to make fun of dictators.
If it doesnt apply to dictators, then who decides who is a dictator. Is putin or Victor Oban a dictator ?
Like there is so much Grey area with "politics" And I feel like Staff would only be criticised for it. Like I can imagine a mod muting cause someone talked about trump. People in chat would say that the mod is biased and is using their power to silence political opinions. Regardless if mods are doing that, it would only make the mod-player relationship more toxic
