### ISSUE TITLE
4.2

### ISSUE THREAD

**Issue by Aquarigger** [EarthMC/EarthMC.net#140]
**rule 4.2**
naming towns

If I wanted to create a town in antarctica what would i call it without it going against this rule?
(I am not good with geography.)

**Comment by Proserrr** [comment]
You can name it anything as long as its not too similar to the name of another town, and not toxic or offensive. You can read the rule on the earthmc rules webpage

**Comment by shirazmatas** [comment]
Rules github not meant for help questions.
