### ISSUE TITLE
3.3 Claim Blocking

### ISSUE THREAD

**Issue by DCDylanc123410** [EarthMC/EarthMC.net#141]
**Exact wording of the rule**

**Before:**

3.3 Claim blocking.
“Claim blocking” is referring to the act of deliberately placing claims near a town in order to block its expansion. This includes placing a new town next to another with the intent of blocking their expansion.

![](https://earthmc.net/src/img/claimBlockExample1.jpg) 
![](https://earthmc.net/src/img/claimBlockExample2.jpg)
![](https://earthmc.net/src/img/claimBlockExample3.jpg)

A town's claims count as blocking if they create long arms of claims protruding from their town like in the images above. These arms are an issue as they do not only block existing towns but also take up large areas where future towns could otherwise be created.
 
Only mayors of towns being claim blocked may report breaking the rule as claiming along someone's border is fine if all involved towns agree on it.

All claims which staff concludes to be blocking a town will be removed without any refund. Players found to be claim blocking more than once may be warned and denied the ability to place outposts all together.

**After:**

**3.3 Extreme Claim Blocking**
Extreme Claim Blocking is not allowed on EMC. Extreme claim blocking isn't limited to but includes: 
       Hollow Claiming.
       Claiming a town inside another town.
       Surrounding a town in claims.

For a claim block to be able to be reported the mayor of an affected town nearby must be the one to report it. Along with this the claim block but be preventing the expansion of nearby towns or preventing the creation of new towns. All claims which staff concludes to be blocking a town will be removed without any refund.

Claim Blocking is evaluated on a case by case basis and staff has final say in what is considered an extreme claim blocking. Players found to be claim blocking my be warned if there was an intent to cause harm through claim blocking.

**How will this rule affect the community**
This rule will help the community by allowing players to do more of what they want. This rule would only affect new claim blocking tickets after the rule goes in place. This will allow players to defend their own town better but also make sure the extremes dont ruin their playing experience. The claim blocking rule already doesn't get very enforced because everybody feels they are being claim blocked where in many instances they might not actually be. This causes both sides to get very upset and prevents anything from truly getting resolved

**Do you think this will benefit both the staff and the players**
Staff and players have to do claim blocking tickets as it is. The staff sometimes ignore the tickets do to their length and difficulty and the players get upset at that but also the outcome of the ticket often times. With a claim blocking ticket usually one of the parties will always be upset about the outcome and nothing truly gets resolved. With the rule set up like this less things will be considered against the rules which will generate less tickets and less people will get upset at the outcome of the tickets

**Comment by KarlOfDuty** [comment]
As per the staff conversation to limit and simplify the rule I think this is more appropriate:

**3.3 Town claims**
Towns are not allowed to have areas of unclaimed chunks inside of their borders as this can substantially increase the size of a town without them actually having to increase their claim limit legitimately.

Surrounding other towns in claims is also not allowed. The only exception to this is when a town is created in an area where it is already surrounded.

**Comment by ghost** [comment]
I agree with this rule simplification.

**Comment by coblobster2** [comment]
But hollow claims are used s lot to make sure they get the land they want during a border agreement. The old rule saying that as long as you are claiming the inside of it was good and allowed for more expanding on this hostile server.

**Comment by KarlOfDuty** [comment]
The main reason to make this rule change is to remove staff interaction from players' border agreements as that should never have been something for staff to be involved in,
