### ISSUE TITLE
Rule 2.1: Teleportation Trap

### ISSUE THREAD

**Issue by Shiachanthedevil** [EarthMC/EarthMC.net#146]
**Exact wording of the rule**
The act of tricking players into teleporting to /n spawn chunk or town homeblock and chunks adjacent to town home block or /n spawn chunk by misleading words so that the person can kill or trap them is not allowed. Spawn camping, which means killing at the /n spawn chunk or town homeblock, is also not allowed. This rule also applies on nether portal trap, which means blocking the nether portal with blocks so that people cannot escape from the nether portal.
.
Traps used during wars or battles that the player doesn't get stuck for a longer period of time (i.e. 15 minutes or more) is allowed.

**How will this rule affect the community**
The rule itself is already here in our current rules. This version of Rule 2.1 uses a clearer wordings to clear misunderstanding and points out that spawn camping, which is illegal but not yet written in the rules, is against the rule. Also, there's a modification so that some gray area would be covered in this new version of Rule 2.1

**Do you think this will benefit both the staff and the players**
For both parties, with this clearer version of the rule, it will be easier for all of us to understand what's allowed and what's not allowed and better implement the rule. Also, it better protects players from "legal" trap which is actually gray area of the current rule. People should not be scared to teleport to towns around the world, as this severely degrades the community experience, and generates excessive toxicity.
**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by coblobster2** [comment]
Define what a long period of time is. And also I think the wording could be a bit less confusing. I can see this wording getting people to argue over whether or not teleporting and getting them into a trap outside of n spawn or home plot is allowed.

**Comment by Shiachanthedevil** [comment]
Thanks for giving comment on this. I will edit it now. You can see if that would be better or not. For the trap outside /n spawn or homeblock, I intend to allow it as long as it doesn't trap people for too long (i.e. more than 15 minutes ), and not located at the homeblock or /n spawn chunk or the chunks right next to it

**Comment by Cactusinapumpkin** [comment]
I might add something like explaining nether portal trapping is where you place anything at the entrance 2x2 of the portal causing them to get stuck. I have accidentally portal trapped someone not realizing they couldn't talk or move. Like allow 2x2 blocks empty at the entrance of the portal because sometimes I see fence gates but it still blocks them in. by 2x2 I mean 2 block where the portal is and two more at the entrance to allow them to get out of the portal.

**Comment by Cactusinapumpkin** [comment]
also "chunks adjacent to town home block or /n spawn chunk"  is this just one chunk all around the home / n spawn chunk or more than one? I have seen people have their trap two chunks away from spawn and allowed it because it doesn't take more than 15 mins from them to die

**Comment by coblobster2** [comment]
Hmm I guess another issue that may occur is the fact you can put the spawn on a corner that is basically in a pvp plot even though the main home plot is not

**Comment by Shiachanthedevil** [comment]
> also "chunks adjacent to town home block or /n spawn chunk" is this just one chunk all around the home / n spawn chunk or more than one? I have seen people have their trap two chunks away from spawn and allowed it because it doesn't take more than 15 mins from them to die

I originally intended to mean two chunks, but on second thought I think it might be too broad. I will wait for more opinion on this and decided the definition of adjacent chunks 



> Hmm I guess another issue that may occur is the fact you can put the spawn on a corner that is basically in a pvp plot even though the main home plot is not

As long as people died in the homeblock involuntarily, it would be spawn camping. If there is a guy luring people to go to a specific /n spawn or homeblock with misleading word, it will be against the this new version of rule to kill people within the 1 (or 2, depending on opinions ) chunk radius of the homeblock or /n spawn

**Comment by KarlOfDuty** [comment]
Added the war info, check #148 for the other stuff.
