### ISSUE TITLE
Rules 2, 3, and 4 as a whole

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#147]
2. Behavior and chat
2.1 Teleport traps
The act of tricking players into teleporting to a specific location that is a trap in the plot or plots directly next to the teleported to plot. (I have heard that turning the N spawn plot into a PVP plot is illegal. If it is I would just add that and if the plots directly next to them can be turned to PVP)  This used to be allowed but a lot of players abused it to the degree players voted to forbid it. 
Normal traps that don't involve players blindly teleporting into them are allowed however, as long as the player doesn't get stuck for a longer than 10 minutes. 

2.2 Stealing and raiding players/towns/nations.
Stealing from and raiding other players is allowed. It’s up to each and every player to protect their assets. This includes councilors stealing from Mayors and the town.

2.3 Spam.
Spamming or sending messages in a way that disrupts chat flow, normally by sending a similar message repeatedly, is not allowed. (I know this one is hard but this one is too inconsistently managed. Occasionally you see a warn for starting it but I think just a consistent mute like 1 hour or something would help this rule.  Unless the spammer does it consistently)

2.4 Unwanted behavior.
Listed unwanted behavior is not allowed on the server. Unwanted behavior includes:
Explicit forms of bullying.
Repetitive use of derogatory terms.
Comments encouraging self-harm.
Inciting violence or explicit forms of hate speech against racial and social minorities.
Explicit talk about sex.

Toxicity is evaluated on a case by case basis and staff have the final say in what is considered toxic behavior. Repeated behavior may lead to warnings, mutes, and eventually a permanent ban. 
(So this rule I feel like it is pretty good, but it is the worst one managed. You can search on the towny discord chat and find thousands of results for all of them. I understand you can not stop all of them, but almost none are being stopped. I would say the n-word is the only word that is consistently patrolled. That is a good start but some of these are pretty bad stuff to see on a server and should be monitored too.)

2.5 Impersonating other players, towns, and nations.
Impersonating players by taking advantage of, but not limited to, usernames, nicknames, town/nation names is not allowed. Offenders will be asked to revert to their proper character. If any damage is done staff may choose to ban the offending player.
(unless consent was given, but I think that is kind of obvious.)

2.6 - 2.10 (Great Rules!)

2.11 Language in global chat channels.
When speaking in either the global chat or the donator chat channel you should stick to English only. You can use other private chat channels for other languages such as town chat or private messages. If there are only or almost only players who also speak your language online you are allowed to speak it in the global channels too.
(if possible I would make the chat names of these other language chats in their language, so when they join they see it says Turkish, Spanish, or Chinese) 

3. Griefing
3.1 Destroying land in or around claims.
Players may not damage land in or around claims (griefing). Players breaking this rule will be warned and damage will be rolled back. Players doing this more than once may face a permanent ban. Placing and removing blocks during siege war events is allowed when necessary to the extent needed in the conflict.
Examples of grief:
Cobble monsters - Mountain-like structures that are built using lava and water.
Lava/water curtains - Placing rows of lava/water in the sky to make a wall of falling lava.
TNT craters.
Mass spawning entities within or around a town (Chickens, Boats, etc.).
(What happens if a councilor griefs? After how many blocks being placed or destroyed is grief? How far away until it is not grief, especially in deserts?)

3.2 Destroying land in the wilderness.
Wilderness is defined by Towny as any land not currently claimed. You are allowed to grief structures or terrain as long as they are not within 3 chunks of a claimed area. However, any player may request major terrain grief to be rolled back even in the wilderness. Breaking railways or ice roads are not allowed even in the wilderness if willingly connecting two existing towns. This does not only apply to the rails but all blocks the railroad is made of.
(again proximity is very vague for no reason. say at least 3 chunks away from a town.)

3.3 Claim blocking.
“Claim blocking” is referring to the act of deliberately placing claims near a town in order to block its expansion. This includes placing a new town next to another with the intent of blocking their expansion.

A town's claims count as blocking if they create long arms of claims protruding from their town like in the images above. These arms are an issue as they do not only block existing towns but also take up large areas where future towns could otherwise be created.

Only mayors of towns being claim blocked may report breaking the rule as claiming along someone's border is fine if all involved towns agree on it.

All claims which staff concludes to be blocking a town will be removed without any refund. Players found to claim blocking more than once may be warned and denied the ability to place outposts all together.
(this I heard is getting deleted. I understand no eating towns, but why are hollow claims not allowed. I understand large ones being illegal like Alabama)

3.4 Stealing specific blocks.
Stealing specific blocks for their value is not considered grief and is therefore allowed. This does not apply to easily acquired blocks even if they are valuable to you.
(I have no idea what this is referring to)

3.5 Major terraforming.
In order to preserve the accurate geography of the map, major terraforming of the natural terrain is not allowed. In general, if your edits of the landscape alter the Dynmap view of the natural landscape, they will be removed. Examples of this include for instance draining large lakes/rivers, creating artificial islands that do not exist in real life, or covering the ocean with platforms. Usually, vertical terraforming is allowed as it does not change the dynmap view.
(I like how this one went a bit into explaining, but if I was new I would be worried if I can make a city in a place where a city is not in real life or if I can clear the land in general to make a city or town.)

3.6 Map art.
Creating map art is allowed as long as it does not interfere with other towns. It is recommended to place map art in Antarctica as there is a lot of unused space there. If you place it outside of Antarctica you will have to claim the area as it will count as griefing if the other towns around you don't like it.

Your map art may not contain nudity, sexual content, racist imagery, depictions of children, or anything else that breaks any part of rule 2. Some memes and nonsexual imagery may also be banned.
(The first part is good but griefing was misspelled. The last part is good but I would go into explaining that memes and some nonsexual imagery are banned such as.  The second part has been so inconsistently explained. I am happy about the wording but the actual modding of it has been horrific. Is skin allowed? sometimes yes sometimes no. I have seen that it sometimes depends on the persons body type and size. I also have seen inconsistency in the amount of clothes and what exactly the definition of sexual means. I personally would not say a bikini and thong are sexual as they are worn in public places such as the beach where children go. Obviously we all have different opinions and it is up to the admins in the end. I have seen 2 memes get banned so far. One being the Luigi big butt and the Nice Cock meme. I have heard the nice cock is not banned cause it does not show anything but if it is not that sets a terrible precedent. What skins are allowed then? what is allowed to be said in chat? what is allowed everywhere?)

4. Naming
4.1 Nation names.
Before creating a nation, make sure your name complies with the nation's naming rules. Nation names may be changed by a staff member if the rule is not followed and maybe disbanded if the rule is repeatedly broken.
Nation name cannot be fictional. It has to have the same name as a current or past nation.
A nation can be named after the region, province, or another large geographical area with defined borders if an accurate nation name is already taken.
Nation name must correspond with the map location of the nation capital.
The nation cannot have a similar name to an already established nation to the point where one could easily be confused with the other.
(I personally like this rule, but I think that it can be enforced a bit more often instead of in big chunks.)

4.2 Town names.
Fictional town names are allowed. However, we highly recommend towns to have a name tied to the real-life town location.
Town names cannot be inappropriate/toxic/offensive.
Towns cannot have similar names to already established towns to the point where one could easily be confused with the other.
Names may be changed by a staff member if the rule is not followed.
(this was good I just changed the order to make it more clear)

4.3 Nicknames, Minecraft usernames, and Towny titles
Do not use explicit, sexual, racist or otherwise inappropriate nicknames, Minecraft usernames, or Towny titles.
(I do not think this rule is really enforced much but I would add on something about skins. Can you enter the server with a nazi server)

**How will this rule affect the community**
I think this will help create a better community. The people who play will finally be able to understand the rule and there might be fewer questions on what is and is not allowed. I also think this will end a lot of the divide in the community between mods and players that has been steadily growing. 

**Do you think this will benefit both the staff and the players**
I think most of these rules should be changed so the players can relax and be able to play EMC without being worried they will be banned over random new rules, a newly enforced rule, or a vague rule. Plus the mods will not get yelled at as much and they will have less to do.

I did change some of the actual wording of the rules. Some I felt like I did not have enough info so I commented in the ().

**Comment by KarlOfDuty** [comment]
Could you make your suggestions in seperate issues instead?

**Comment by coblobster2** [comment]
Do you want a post for each individual rule? would that not be a lot and over spam the GitHub?

**Comment by KarlOfDuty** [comment]
No, thats fine

**Comment by coblobster2** [comment]
Ok I will try to condense anyway cause some of these are small issues
