### ISSUE TITLE
2.1 Teleport Trap Confusion

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#148]
**Exact wording of the rule**
2.1 Teleport traps
The act of tricking players into teleporting to a specific location that is a trap in the plot or plots directly next to the teleported to plot.
 This used to be allowed but a lot of players abused it to the degree players voted to forbid it.
Normal traps that don't involve players blindly teleporting into them are allowed however, as long as the player doesn't get stuck for a longer than 10 minutes.

(So for this one, I have a few questions that I think can easily be answered if put into the rules. 
+ is a plot
X is a plot with nation spawn

+++
+X+
+++

so let's say the Plot in the middle that I made X is the plot where a nation spawn is located. So which Plots directly next to the X plot can be PVP? Also, you are able to put a nation spawn on the very edge of a plot which could lead to an argument because if a trap is allowed to be placed in the + plots then they may be forced into it even though the nation spawn is in the X plot. Also is it completely illegal to turn the X plot into a PVP plot? If so add that to the rule. )

**How will this rule affect the community**
I think getting rid of the vagueness of how long a long time actually is will stop inconsistencies between mods will help the community have a better understanding of what is and is not allowed. This way fewer arguments will occur. The explanation on what plots can be PVP and have traps will also clear up some of the confusion of the newer addition of spawn traps being illegal.  

**Do you think this will benefit both the staff and the players**
I think this will benefit players because if you were to ask a mod on this issue they will give different answers and may have to take the time to ask other mods to get a final answer when most of this can be explained in a simple explanation. Also, I am not saying to just choose the time I gave I am just thinking under 15 minutes cause of AFK. I am just saying a simple fair time that everyone can know would be helpful. 

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by coblobster2** [comment]
For some reason my key got messed up. A plus sign is just a regular plot

**Comment by KarlOfDuty** [comment]
Sometimes it would be appropriate to turn on pvp in a spawn plot, completely banning it would let harassers have a safe area within an enemy town even if it's not related to a tp trap. And to answer your other question, as long as the area they teleport into is safe then there is no problem, the areas around it may be pvp as that would be no different than accidentally walking into any other pvp area. If someone has pvp on in their spawn plot but doesn't harm anyone then that is also fine.

**Comment by Shiachanthedevil** [comment]
> Sometimes it would be appropriate to turn on pvp in a spawn plot, completely banning it would let harassers have a safe area within an enemy town even if it's not related to a tp trap. And to answer your other question, as long as the area they teleport into is safe then there is no problem, the areas around it may be pvp as that would be no different than accidentally walking into any other pvp area. If someone has pvp on in their spawn plot but doesn't harm anyone then that is also fine.

Well, the problem now is that there're players killing others continuously at the pvp plot next to the spawn which is extremely close to those pvp plots and we want to prevent that from happening as this would ruin players' experience

**Comment by KarlOfDuty** [comment]
I think that will just be a thing that happens, I don't think it is much different to just having someone run into a pvp plot anywhere else
