### ISSUE TITLE
2.2 Stealing

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#149]
**Exact wording of the rule**
2.2 Stealing and raiding players/towns/nations.
Stealing from and raiding other players is allowed. It’s up to each and every player to protect their assets. This includes councilors stealing from Mayors and the town.

**How will this rule affect the community**
I think the community will understand that stealing is allowed even as a councilor. Although I wish this was not a rule I know it is not exactly possible to moderate and it makes the game a bit more fun if people are allowed to steal. This is already a rule I just thought it should be stated so people know. 

**Do you think this will benefit both the staff and the players**
I think players will have a better understanding and maybe more fun while mods will get fewer tickets saying a councilor took everything! 

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by KarlOfDuty** [comment]
Ok then
