### ISSUE TITLE
Rule Complaint

### ISSUE THREAD

**Issue by FurdenFuhrer** [EarthMC/EarthMC.net#15]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when mods are being retarded about naming rules, sometimes enforce them and sometimes they don't. I also am frustrated with the whole nation range BS. This reset could have been great, but no, the mods have to ruin it by adding these dumb ass rules.
**Describe the solution you'd like**
Clear concise description? Actually listen to the community have heard very little support in favour of keeping these rules and a shit ton on removing them for good.
**Additional context**

**Comment by FurdenFuhrer** [comment]
https://www.strawpoll.me/17415337

**Comment by FurdenFuhrer** [comment]
https://www.strawpoll.me/17415337

**Comment by FurdenFuhrer** [comment]
Vote, please.

**Comment by FurdenFuhrer** [comment]
I want staff to see people's wants. It is up to us to show them!

**Comment by KillerDuck00** [comment]
Not to be a bummer, but it's super easy to add fake votes on strawpoll

**Comment by FurdenFuhrer** [comment]
How so?
I have Ip duplication checker on

**Comment by FurdenFuhrer** [comment]
and you have to verify that you are not a robot

**Comment by KillerDuck00** [comment]
just use a vpn

**Comment by FurdenFuhrer** [comment]
...

**Comment by FurdenFuhrer** [comment]
Well shit

**Comment by KillerDuck00** [comment]
it takes 3 min to add 30 votes if you are doing it slowly

**Comment by FurdenFuhrer** [comment]
Well all I can control is to spread this poll to try and get a slightly accurate percentage of what the people want. 
What would you suggest

**Comment by KillerDuck00** [comment]
I honestly dont know, this is the exact reason i dont like strawpoll. Best you could do is just hope that people are honest and not douchebags, however i wouldnt trust strawpoll with a penny.

**Comment by FurdenFuhrer** [comment]
I would love the staff to somehow gage what the ppl want

**Comment by FurdenFuhrer** [comment]
Maybe you would have to like somehow link the strawpoll to the emc discord and you have to be a verified player?

**Comment by KillerDuck00** [comment]
That would be nice, but I don't know if it is possible. So the problem is that NATIONS have to have the name of a real nation and that towns have to be closer than a certain value from the nation capital?

**Comment by FurdenFuhrer** [comment]
That is the issue. Something to fix the whole nation range issue is to expand it of course, and with the nation naming rules I think they are flawed in the way of enforcement to where someone has to report the violation so people can have a name that violates the law for months and just one day get reported and forced to change it.

**Comment by KillerDuck00** [comment]
So say the range is increased, as everyone expands won't they just complain again?

**Comment by FurdenFuhrer** [comment]
Of course, they would. You cannot make everyone happy, but, compromises have to be made because a side likes the range so a median between the two would be nice. What I would do is what Fix said before Terra Nova officially released that the range would make it so you could invite towns from all of North America. He never specified that it was the old server's North America and not the new ones, so, just poor communication on his part. But, that would expand it greatly so large regions like Brazil, China, USA, and the European part of Russia can actually unite.

**Comment by FurdenFuhrer** [comment]
Making the range this size would still make it more costly for Europeans to make colonial nations, but large irl nations can be made, and China couldn't just own a random bit of Portugal, so both sides would get something they want.

**Comment by Pengun78** [comment]
Jesus christ emc would be so fucked up without the naming rules and no nation range
"Ppnation invaded russia2 yesterday in their south american colony!"

**Comment by Pengun78** [comment]
If you want an example go to the classic emc map and see some locations
Mexico is literally owned by canada

**Comment by FurdenFuhrer** [comment]
Pengun I've played on EMC for over a year and seen the most stupid of shit, but, how is just what EMC was and what it is supposed to be. Competition of adding new towns doesn't happen if one regional power just is there and no one else can invite towns because of the range.

**Comment by FurdenFuhrer** [comment]
and also, it is 1000 g to make a nation, there ain't going to be rando's that make Ppnation they are going to have to be active players.

**Comment by Pengun78** [comment]
Nah there will bro believe me ive also played emc for a long long time and it used to be everything except realistic i love how it is right now

**Comment by JuliusCaesar12** [comment]
Pengun78, you sound like you came from California

But, how are you supposed to do your conquests when the nation range is in place?

**Comment by Pengun78** [comment]
You conquest close nations

**Comment by FutureCW** [comment]
You conquest close nations in Europe*
A majority of the nations you could possibly do that to are in Europe or North America and that leaves out Asia, Africa, Oceania, and South America. I do believe nation range should increase atleast a little with size but a lot of nations like mine aren’t even that close to their full potential yet

**Comment by KarlOfDuty** [comment]
We will not be removing the naming rules at this time.
