### ISSUE TITLE
2.3 Spam

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#150]
**Exact wording of the rule**
2.3 Spam.
Spamming or sending messages in a way that disrupts chat flow, normally by sending a similar message repeatedly, is not allowed.

**How will this rule affect the community**
I know this one is hard but this one is too inconsistently managed. Occasionally you see a warn for starting it but I think just a consistent mute like 1 hour or something would help this rule. Unless the spammer does it consistently. I think the wording for this one is good, I just think that it is not enforced and when it is, it is not enforced consistently. 

**Do you think this will benefit both the staff and the players**
Players will have a better understanding of what is and is not allowed in chat. The mods will have to do more on this one but realistically this does not happen very often. 

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by KarlOfDuty** [comment]
Again, this is not really related to the rules page but this is something we have talked about yes.
