### ISSUE TITLE
2.4 Toxicity

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#151]
**Exact wording of the rule**
2.4 Unwanted behavior.
Listed unwanted behavior is not allowed on the server. Unwanted behavior includes:
Explicit forms of bullying.
Repetitive use of derogatory terms.
Comments encouraging self-harm.
Inciting violence or explicit forms of hate speech against racial and social minorities.
Explicit talk about sex.

(So this rule I feel like it is pretty good, but it is the worst one managed. You can search on the towny discord chat and find thousands of results for all these. I understand staff can not stop all of them, but almost none are being stopped. I would say the n-word is the only word that is consistently patrolled. That is a good start but some of these are pretty bad stuff to see on a server and should be monitored too. I took out the last part because it is obvious that people will get punished and the rule should not be enforced on a case by case basis. Unless it is something really out of right field then it should be a routine similar to spamming.)

**How will this rule affect the community**
I think if this can somehow can be figured out to be modded then the server would have a lot better atmosphere around it. EMC is a very special and different server and has a lot of new things such as EMC Mental Health. A discord server where you can vent and talk about stuff in life and EMC. EMCMH is great to combat the toxicity but truthfully if this rule was enforced I think it would help make a lot of people's lives a lot better. 

**Do you think this will benefit both the staff and the players**
I think the overall mood surrounding the server will go up. EMC has gotten a bit known for its toxicity similar to 2b2t. I also think that if the server is going to take a turn to focus on accompanying the younger demographics this should be taken care of. I think in general this needs to be fixed. This is one of the rules that will have to be vague with explanations so it helps the community. 
**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by jkmartindale** [comment]
What changes are you asking for? The only change I see here is taking out the last two sentences of 2.4 without anything about why taking them out is beneficial.

**Comment by coblobster2** [comment]
Good point. I think this is one of the rules that has problems but it is not the rules itself. It is just the way it is handled. I guess this is not the best place for a staff moderating idea but I do not know anywhere else where you can get comments and critiques. On this one I was just asking for more moderation of some kind. I think the biggest example is kys now yes people say it as a joke but is it really funny? Not usually so idk if it should be allowed on the server. Stuff like that if patrolled can really help the community

**Comment by coblobster2** [comment]
And I would take them out because toxicity should not really be on such a case by case situation to the point where it needs to be said. Every ticket is a case by case situation and stating it right there in the open can seem to allow more inconsistent modding that has been plaguing the server for alittle while now

**Comment by KarlOfDuty** [comment]
This issue tracker is specifically about the website, not the minecraft server, so specific rule changes only.
