### ISSUE TITLE
2.11 Just a suggestion

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#152]
**Exact wording of the rule**
2.11 Language in global chat channels.
When speaking in either the global chat or the donator chat channel you should stick to English only. You can use other private chat channels for other languages such as town chat or private messages. If there are only or almost only players who also speak your language online you are allowed to speak it in the global channels too.

(if possible I would make the chat names of these other language chats in their language, so when they join they see it says Turkish, Spanish, or Chinese)

**How will this rule affect the community**
Make it easier for new players to join and find their chat to talk. Occasionally you see a mod or player say do /Turkish to join the Turkish chat but they may not understand it because it is in English.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by KarlOfDuty** [comment]
As playing on the server already requires some basic understanding of english I feel like one would at least know what their own language is called. And in any case it needs to be clear to others what the command does and means.
