### ISSUE TITLE
3.1 Griefing

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#153]
**Exact wording of the rule**
3.1 Destroying land in or around claims.
Players may not damage land in or within 3 chunks of a claim (griefing). Players may not destroy or place more than 30 blocks within 3 chunks of any claim. Players breaking this rule will be warned and damage will be rolled back. Players doing this more than once may face a permanent ban. Placing and removing blocks during siege war events is allowed when necessary to the extent needed in the conflict.
Examples of grief:
Cobble monsters - Mountain-like structures that are built using lava and water.
Lava/water curtains - Placing rows of lava/water in the sky to make a wall of falling lava.
TNT craters.
Mass spawning entities within or around a town (Chickens, Boats, etc.).

(What happens if a councilor griefs? After how many blocks being placed or destroyed is it considered grief? How far away until it is not grief, especially in deserts? The 30 blocks is just an idea. I do not know what a good number would actually be but a ballpark number would be good.)

**How will this rule affect the community**
I think some clarification on some of these issues will help the community know what exactly they can and can not report. 

**Do you think this will benefit both the staff and the players**
Players and staff will know what they can and can not do in-game. Staff will get fewer tickets because people will know what is not allowed and should not make tickets on the issue if the rule does not say it is illegal. 

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by coblobster2** [comment]
also for 3.2, I would just add that griefing within 3 chunks from a claim anywhere is illegal. or whatever amount of chunks staff wants.

**Comment by KarlOfDuty** [comment]
I don't think adding such specifics would be useful for this rule, all griefing is very different so this just opens up for abuse one way or the other.
