### ISSUE TITLE
3.3 Claimblocking/Hollow Claims

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#154]
**Exact wording of the rule**
3.3 Town Eating/Extreme Claimblocking
Players are not allowed to claim completely around another town.
Extreme Claimblocking is also illegal but Claimblocking is legal now. 
Hollow Claims are allowed but no bigger than 10 unclaimed chunks per town.

(this I heard is getting deleted. I understand no eating towns, but why are hollow claims not allowed? I understand large ones being illegal like Alabama because they hurt other towns.)

**How will this rule affect the community**
Simpler and easy for the community to not break the rules. 

**Do you think this will benefit both the staff and the players**
Staff will have a lot fewer tickets because claim blocking is legal. Players will be happy and it will make it more competitive to get gold to claim. 

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by KarlOfDuty** [comment]
This has already been updated recently.
