### ISSUE TITLE
3.4 Absolute complete confusion rule

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#155]
3.4 Stealing specific blocks.
Stealing specific blocks for their value is not considered grief and is therefore allowed. This does not apply to easily acquired blocks even if they are valuable to you.

UH, so this one I just do not know what it is talking about. I talked about it with someone and they said maybe it has to do with proximity grief and if that is so I would just list what specific blocks it means. 

Sorry for the bad formatting on this one.
**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by KarlOfDuty** [comment]
Stealing is allowed but griefing is not?

**Comment by shirazmatas** [comment]
please fix format
