### ISSUE TITLE
3.5 Terraforming

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#156]
**Exact wording of the rule**
3.5 Major terraforming.
In order to preserve the accurate geography of the map, major terraforming of the natural terrain is not allowed. In general, if your edits of the landscape alter the Dynmap view of the natural landscape, they will be removed. Examples of this include for instance draining large lakes/rivers, creating artificial islands that do not exist in real life, or covering the ocean with platforms. Usually, vertical terraforming is allowed as it does not change the dynmap view. You are allowed to terraform to create your city or town anywhere on land. 

**How will this rule affect the community**
I think adding the last sentence will help new players have the reassurance that they are allowed to make a new town in open land. 

**Do you think this will benefit both the staff and the players**
Players and staff will know whether or not creating a new town in a random place is allowed to be terraformed. 

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by KarlOfDuty** [comment]
I think this would just make it more confusing as that cold be interpreted as basically anything.
