### ISSUE TITLE
3.6 Mapart Precedent

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#157]
**Exact wording of the rule**
3.6 Map art.
Creating map art is allowed as long as it does not interfere with other towns. It is recommended to place map art in Antarctica as there is a lot of unused space there. If you place it outside of Antarctica you will have to claim the area as it will count as griefing if the other towns around you don't like it.

Your map art may not contain nudity, sexual content, racist imagery, depictions of children, or anything else that breaks any part of rule 2. Some memes and nonsexual imagery may also be banned.

(The first part is good but griefing was misspelled. The last part is also good but it has been modded so inconsistently. I am happy about the wording but the actual modding of it has been horrific. When it comes to a map art is skin allowed to be shown? Sometimes yes, sometimes no. I have seen that it sometimes depends on the person's body type and size. I also have seen inconsistency in the amount of clothes people are allowed to wear and what exactly the definition of sexual means on EMC. I personally would not say a bikini and thong are sexual as they are worn in public places such as the beach where children go. Obviously we all have different opinions and it is up to the admins in the end. I have seen 2 memes get banned so far because of this rule, one being the Luigi big butt and the Nice Cock meme. I have heard, the nice cock meme is not banned cause it does not show anything but if it is banned that sets a terrible precedent for the rest of the server. What is allowed to be said in chat? As for the other maps that have been banned some of them are leaving me saying What skins are players allowed to play on the server with then? what is allowed everywhere? This rule being enforced has been good and bad. It has stopped some maps that definitely should not have been on the server while also banning some that open up a pandora's box worth of questions of what is and are not allowed on the server. Also, people are able to live with stuff being banned but it should be explained and not left to question why or what is the problem. I was very happy to hear the Hitler maps were banned. I also think that the all of a sudden warning people on this issue is terrible modding because people did not know this was illegal to have. Yes some of it you can say oh look it is in the rules, but just because it is in the rules does not mean anything unless the mods actually enforce it which the toxicity rule shows.)

**How will this rule affect the community**
I think a rule clarification explaining what is and is not allowed and why is needed to help the server move on and become what the admins want it to be. Although this rule is harmless on its own it is severely affecting other rules and the community. 

**Do you think this will benefit both the staff and the players**
I think this will create better communication between staff and players and help the community be less toxic towards each other. The mods have been trying to defend some of these rules by pointing at other rules that are similar but they are not being enforced.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by coblobster2** [comment]
update: I do think the banning has calmed down and what is getting banned is getting a bit more clear. The worriedness in this post is not there as much because memes are not really getting banned anymore, but I do still see the maps being banned in a very random way when it comes to the size and shape of the person plus whether or not someone is considered ugly or beautiful is also an aspect that seems to affect this rule for some reason.

**Comment by solamint** [comment]
The mapart banning has calmed down since no one wants to make mapart because they dont know if itll be removed or not.
