### ISSUE TITLE
4.1 Inconsistency Nation names

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#158]
**Exact wording of the rule**
4.1 Nation names.
Before creating a nation, make sure your name complies with the nation's naming rules. Nation names may be changed by a staff member if the rule is not followed and maybe disbanded if the rule is repeatedly broken.
Nation name cannot be fictional. It has to have the same name as a current or past nation.
A nation can be named after the region, province, or another large geographical area with defined borders if an accurate nation name is already taken.
Nation name must correspond with the map location of the nation capital.
The nation cannot have a similar name to an already established nation to the point where one could easily be confused with the other.

(I personally like this rule, but I think that it can be enforced a bit more often instead of in big chunks.)

**How will this rule affect the community**
I think the community will not get so mad when their nation is all of a sudden renamed to contact the staff if it happened closer to when they created the nation and spent time making a reputation for their nation. 

**Do you think this will benefit both the staff and the players**
Players will have a better understanding and caring for the rules if it was enforced more commonly. The staff may not like having to enforce this but I think if they are going to have this as a rule it should be enforced more commonly which should not be that hard with news outlets sharing what nations were made recently. 

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by KarlOfDuty** [comment]
I don't really see a change here?

**Comment by jkmartindale** [comment]
I think it's just commentary on rule enforcement, like with #151

**Comment by KarlOfDuty** [comment]
Right, that's probably not the right place then.
