### ISSUE TITLE
4.2 good rule

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#159]
**Exact wording of the rule**
4.2 Town names.
Fictional town names are allowed. However, we highly recommend towns to have a name tied to the real-life town location.
Town names cannot be inappropriate/toxic/offensive.
Towns cannot have similar names to already established towns to the point where one could easily be confused with the other.
Names may be changed by a staff member if the rule is not followed.

(good rule just changed the order to make it easier to understand.)
sorry to make a post for this one.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by KarlOfDuty** [comment]
I think it makes more sense as is.
