### ISSUE TITLE
Price changing on queue priority for Brazilian R$

### ISSUE THREAD

**Issue by ketchupdrinker** [EarthMC/EarthMC.net#161]
I would like to see a potential change in the price of queue priority for Brazil R$ from 80 Real to 30-40 Real.

Before you jump the gun here let me explain, Brazilian currency is much weaker than other currencies worldwide so it has much less purchase power, in Brazil if you were attempting to buy a US product for 15USD it would be the equivalent of spending 30USD in Real equivalent and therefore isn't fair to people in those countries.

Queue priority allows players to be more active and spend more time in EMC and less time in the queue, South America has a large population of internet users but South America is the most inactive continent on EMC. If the price was changed it would open up more markets to Brazilians, and in turn generate more sales on queue priority from Brazilian users.

**Comment by coblobster2** [comment]
Emc decides this? Wouldn't it just be like PayPal or whatever that changes the currency

**Comment by jkmartindale** [comment]
As far as I can tell Buycraft doesn't support multiple price points per item. You pick a currency and amount to receive, and it prices other currencies to match.

The only way to offer a different price point for BRL would be to set up a PayPal buy button or something on a different webpage and have an admin add a manual payment to Buycraft every time someone buys it.

**Comment by KarlOfDuty** [comment]
Yeah that is sadly not possible.
