### ISSUE TITLE
2.7 Addition

### ISSUE THREAD

**Issue by ghost** [EarthMC/EarthMC.net#167]
**Exact wording of the rule**
2.7 Sharing personal information
Sharing personal information and identities of others without their explicit permission is strictly forbidden. Personal information may be, but not limited to, “real life” photos of players, phone numbers, home addresses, social networks, school/work location, family relations and IP-addresses. Any info that is "in the public domain" such as public discords or chats doesn't exempt you from this rule. Any sharing of personal info must have to explicit permission of the person who the info is about. Any violation of this rule will result in an immediate permanent ban.

**How will this rule affect the community**
I find it interesting that we perm ban for doxxing but recently ive seen players getting temp banned for it as well. Doxxing is Doxxing regardless of where the info is or who it is about, just cause its "public" doesn't mean it is allowed to shared whatsoever unless you have explicit permission from the person who the info is about to share it.

**Do you think this will benefit both the staff and the players**
I think this change will further close any loopholes in the doxxing rule that recently players have found, we cannot allow doxxers to only get temp bans. Doxxing is serious offense that should be taken as such.

**Comment by Shiachanthedevil** [comment]
I agree. Putting info in public domain doesn't mean that you can spread that info to others without consent, which is doxxing in nature. As we have been enforcing the rule that doxxer should be permanently banned, I don't see there's any difference for this kind of situation too.

**Comment by coblobster2** [comment]
I like adding IP addresses. But can you give an example of the bottom part. It is very broad and I feel like could mean multiple things.

**Comment by ghost** [comment]
sure, "public domain" is like you posting a pic of yourself in the emc discord, even in that space, that info is not to be sent around regardless if it is in a "public" place, sharing it around would constitute doxxing

**Comment by coblobster2** [comment]
Ok interesting. That kinda makes sense. I guess my next question is where is the line. Is sharing someone's name okay? State or province? Country?

**Comment by ghost** [comment]
I believe Fix has said that sharing nationality is fine, as its not really identifying, (I will clarify for you and get back with a for sure answer for that). In regards to names and states i would say dont share unless given permission from the player who said it, as that could be counted as identifying information

**Comment by ghost** [comment]
i wrote this because we have had cases of players sharing around images of banned players and effectively getting away with doxxing cause "their image was in a public place". I personally don't feel that is right, even if the person posted it there, that gives no right for others to take it and share it around with no punishment
Edit 1: I will not say who of course

**Comment by coblobster2** [comment]
Ok. I think first name or nickname should be ok cause that is what people will go by. But yeah full name shouldn't be shared at all

**Comment by ghost** [comment]
That can be discussed further, im open to discussing first name and/or nicknames
