### ISSUE TITLE
[Rule Change] Rule 2.4

### ISSUE THREAD

**Issue by TheTerrorByte** [EarthMC/EarthMC.net#168]
Currently, the way rule 2.4 is worded does not prevent discrimination against majority groups. The rule should be updated to include protection for majority groups as well, as according to the way the rule is currently worded, it is legal to use discriminatory language against majority groups (ex: Whites). 

Current wording:
Inciting violence or explicit forms of hate speech against racial and social minorities.

Suggested change:
Inciting violence or explicit forms of hate speech against **any racial and social group.**

**Comment by gazings** [comment]
Would also include ethnic group for brevity’s sake
