### ISSUE TITLE
Shop Suggestion: Premium perms addition

### ISSUE THREAD

**Issue by Twitchyyy** [EarthMC/EarthMC.net#173]
**I used to buy premium but...**
As someone with donor, the only feature that would be useful to me is changing the dynmap claim colors. However, currently only nation Kings have the perms to do so and I'm a Chancellor in my nation.

The suggestion is to allow nation Chancellors the perms to also change the dynmap claim colors. This would probably greatly increase the amount of Premium sales and help the server get more revenue for development and support. It would also make the map more colorful than it is now as more people who lead nations would have perms, adding to the server's overall aesthetic and appeal to new players. You could have it work the same way as it does for Kings: in order for the color to stay, the player has to remain a Chancellor and in the nation.
 
Personally, as nation leader who is doing the trick of transferring a nation to a friend to shift the claim radius/star to another capital while keeping the n spawn in the original town, I now have no reason to buy premium as the towny pluggin no longer considers me king and I can't change the dynmap claim colors. If Chancellors could change the colors, I would definitely buy it again.

**Please allow Premium players who are nation Chancellors the ability to do /emcmap nationcolor and /emcmap nationoutline**

**Comment by FixTheAdmin** [comment]
Thanks for the suggestion!
I think this might work as long as kings are able to remove it regardless if they have premium or not.

**Comment by Oln123** [comment]
I agree this would be epical imo.
also gg for quick response

**Comment by Twitchyyy** [comment]
That would be a good way to balance perms. Something like /emcmap nationcolor reset | /emcmap nationoutline reset for kings

**Comment by alsjad** [comment]
Absolutely agree

**Comment by unbatedaura409** [comment]
Yes please

**Comment by Kiriyashiki** [comment]
Please bring this. Despite fix approving the idea, still nothing has been done in 4 months...

**Comment by shirazmatas** [comment]
please change to include format
