### ISSUE TITLE
EarthMC News machine 🅱roke

### ISSUE THREAD

**Issue by jkmartindale** [EarthMC/EarthMC.net#175]
Is it gone for good or...?

![image](https://user-images.githubusercontent.com/11380394/95038258-4c993400-0693-11eb-8652-e0a944d4709a.png)

**Comment by unbatedaura409** [comment]
why would you open something about emcl bot on the emc github

**Comment by JaVolimKatarinu** [comment]
It took me a while, but a nice IP address. ;)

**Comment by jkmartindale** [comment]
> why would you open something about emcl bot on the emc github

https://earthmc.net/news machine 🅱roke

**Comment by jkmartindale** [comment]
> Is it gone for good or...?

yes
![image](https://user-images.githubusercontent.com/11380394/95658887-45cf4e80-0ae3-11eb-9551-f61de39aa7ba.png)

rip EarthMC News which was silently shuttered right before the website was silently updated to suck
![image](https://user-images.githubusercontent.com/11380394/95658909-67c8d100-0ae3-11eb-979b-54cdc75bf405.png)

**Comment by DasCodes** [comment]
We are migrating the platform hence it'll be down for a few more days.

**Comment by jkmartindale** [comment]
![image](https://user-images.githubusercontent.com/11380394/100164633-e6a08000-2e7d-11eb-8350-9ba294de7ef5.png)
👀
