### ISSUE TITLE
Where did custom recipes go?

### ISSUE THREAD

**Issue by sgmedev** [EarthMC/EarthMC.net#177]
**Add your suggested contents here**
A clear and concise description of what it is.

Custom recipes

**Additional context**

I don't know if I'm missing something but there used to be custom recipes on the [faq](https://earthmc.net/faq) but now they are gone and the faqs start at number 2 instead of 1 and after a quick look at the website I still can't find them
![image](https://user-images.githubusercontent.com/30369708/95642939-9c468800-0af7-11eb-88b4-d932bf0bd552.png)

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by jkmartindale** [comment]
bruhh so much documentation is now missing

**Comment by FutureLemon** [comment]
I've noticed this too big sad :(

**Comment by jkmartindale** [comment]
wordpress moment

**Comment by shirazmatas** [comment]
Follow format

**Comment by sgmedev** [comment]
> Follow format

@shirazmatas Format followed, reopen pls
