### ISSUE TITLE
Buycraft always showing price in USD

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/EarthMC.net#178]
When you're on the website to buy premium or queue priority you can chose to change the currency to your preferences but it still shows in USD. 

This isn't really an issue unless it just charges you in USD after changing the currency which can make stuff much more expensive, however I think it's just a visual bug and can potentially make it so people don't buy the ranks because they think they have to buy a rank for $95.

![image](https://user-images.githubusercontent.com/44688587/95976027-3d468300-0e17-11eb-9128-ff1ed02c8322.png)

As you can see I changed to DKK and yet it says $95.

![image](https://user-images.githubusercontent.com/44688587/95976090-564f3400-0e17-11eb-9142-eb1327057e21.png)

**Comment by shirazmatas** [comment]
Fix discriminating against danes smh

**Comment by 10op10** [comment]
Please follow format

**Comment by shirazmatas** [comment]
true, follow format

**Comment by shirazmatas** [comment]
also its patched now anyways
