### ISSUE TITLE
Nether Death Spamming Rule Change

### ISSUE THREAD

**Issue by ZGamerz123** [EarthMC/EarthMC.net#179]
Whenever I want to do a nether battle, me and everyone else involved gets kicked for "death spamming". We aren't death spamming, we are just fighting and nether death messages are enabled. I want this rule to be changed so that we can't get kicked for "death spamming". The rule prevents us from having epic nether battles, or even going in the nether to fight at al. Thank you and I hope this rule will change.

**Comment by coblobster2** [comment]
There were talks to disable death messages in the nether. Thoughts on this?

**Comment by ZGamerz123** [comment]
sorry I am new to github I accidently wrote the description in a comment

**Comment by ZGamerz123** [comment]
I think it should be disabled

**Comment by ZGamerz123** [comment]
I am tired of getting kicked for death spam it's not even spam it's a battle and it doesn't even flood the chat

**Comment by jkmartindale** [comment]
> There were talks to disable death messages in the nether. Thoughts on this?

I think the ideal situation would be to throttle death messages so that a maximum amount will be shown for a given period of time. We'd get the benefits of death messages without any notion of spam.

**Comment by ZGamerz123** [comment]
> > There were talks to disable death messages in the nether. Thoughts on this?
> 
> I think the ideal situation would be to throttle death messages so that a maximum amount will be shown for a given period of time. We'd get the benefits of death messages without any notion of spam.

I think that's a good idea

**Comment by shirazmatas** [comment]
follow format
