### ISSUE TITLE
Rule Complaint 4.1

### ISSUE THREAD

**Issue by JuliusCaesar12** [EarthMC/EarthMC.net#18]
EarthMC is a sandbox, right? That being said, why can't we make any nation name we want that isn't toxic and would actually suit ourselves. I would like to make a nation along the lines of Noble States or something, but with this rule, I can't make this.

**Comment by ghost** [comment]
In the same way the Earth MC map is based on a non-fictional place (i.e. the actual earth) the aim of the server is to reflect the nations and towns that exist in real life. It is a geo-political server.
 I'm indifferent to the rule I don't agree or disagree with it. 
As I understand it sandbox means non-linear and while forcing nations to maintain some form of linearity by making them use accurate geographical nation names, there is still a lot of freedom. 
Nation names can be past or present and towns can be named after anything you want.
 I think the point of the rule is in itself to reinforce the goal of the server: To create an earth  like minecraft server with towny with nations and towns that reflect those in real life. 
It would be a bit bizarre to have a nation called say "Mordor" for example.
Lots of players are opposed to the rule like you, but the majority are for it and changing the rule would change the concept of the server shifting it away from a geo-political minecraft earth.

**Comment by Kyoris** [comment]
I mean as I stated in issue #20  you should allow mashup names of real nations/regions.

**Comment by JuliusCaesar12** [comment]
I can't believe I missed this
I see why that a name like Mordor wouldn't work mainly because it isn't a word, but why can't we use actual words that seem fitting to an Empire of your own Creation?
I's like to have a game where you can name an empire after something that is appropriate, an actual word, and fitting. Things like Somaltia would be fine because it is a mashed name of a real nation, but things like the N-word, swears, or s. intercourse wouldn't work because the majority of people that play Minecraft are kids.

**Comment by ghost** [comment]
I doubt the rule will be changed regardless because again, fictional nation names irrespective of how fitting some players may find them would change the goal of the server away from recreating non-fictional nations on the Earth.

**Comment by laidang08** [comment]
I feel like this rule should allow more names that follow a realistic history like affiliated groups like KKK, gangs like the crips or bloods, or large groups like the Nazis.

**Comment by ghost** [comment]
> I feel like this rule should allow more names that follow a realistic history like affiliated groups like KKK, gangs like the crips or bloods, or large groups like the Nazis.

It does Nazi Germany is a nation. There are also work arounds for the rule, example: Atlantis could not be a real nation so... we chose Danelaw based on our geographic location, it was the area under you guessed it Danish rule during the viking crusades of Britain. The work around is you can set your tag to whatever you want. So although our nation is Danelaw or name in chat its for example: ATL:Atlantis: Aitonater. Even though our nation name is Danelaw.

**Comment by KarlOfDuty** [comment]
We will not be allowing fictional nation names at this time.
