### ISSUE TITLE
Entity Purge Plugin

### ISSUE THREAD

**Issue by unbatedaura409** [EarthMC/EarthMC.net#181]
EMC needs an entity clear plugin. It's very obvious. I know admins may not understand as they can't play the server like the normal player, and I understand that, but if anybody has ever rode on a boat through the ocean or even just walked through wilderness long enough you'll know what I'm talking about. The amount of entities on EMC is insane, and a mob chunk limit simply isn't enough. We need a full entity purge plugin, one that happens every 30-45 minutes or so. You'd be surprised how much it helps. It would remove dropped items, regardless of value or usefulness. This would not remove mobs, or maybe it could remove mobs not within towns. It would help with the lag, and anybody who knows about this kind of thing can vouch.

**Comment by Taffffy** [comment]
I fully agree

**Comment by FutureLemon** [comment]
Go to the issue tracker, this is only for website related issues 😳

**Comment by unbatedaura409** [comment]
Closed b/c wrong category
