### ISSUE TITLE
Implement better server autosave - fix 1hr rollbacks

### ISSUE THREAD

**Issue by bwilso1** [EarthMC/EarthMC.net#182]
**Add your suggested contents here**
The past two nights I've been on, there have been 0.5 to 1 hr rollbacks when the server reboots.  This causes issues with players losing vote crates because the external site will not re-send crates despite the inventory being lost.  This also destroys a lot of build progress.

Depending on whether a player deposits gold into a chest or withdraws it, gold can be lost or duplicated with these frequent rollbacks.

**Additional context**

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by FutureLemon** [comment]
Go to the issue tracker, this is only for the website

**Comment by shirazmatas** [comment]
what future said
