### ISSUE TITLE
100% Fix for Mystery Heads, ending pay to win.

### ISSUE THREAD

**Issue by DarkOakMetarex** [EarthMC/EarthMC.net#183]
I suggest to fix the problem to allow every player on EarthMC to be able to collect head crates although the rarity won't be as
great than if you were to have premium. If you have premium you can get access to a better % Chance of rare heads but make
sure that regular players have a chance to still get these rare ones also but at a very lower rate for example. when you have
premium you can have up to 20-30% chance for a High Tier Head but with no Premium you have a 5-10% chance for one.
Also making the heads also regularly appear in bruh crates with a chance the same as premium since bruh crates are rare and take a lot of time and making vote crates also give off a chance for heads 5-10%. This would also make the chat more vibrant when awarding things from the crates.

All in all this really sums up the entire issue we've been having here on the server for the most part at least I believe that to be the case and I hope many can agree with this plan or concept.

**Comment by coblobster2** [comment]
Hey not sure how github works but I think they may want you to move this over to the other part of github also I opened up a github issue on this

**Comment by shirazmatas** [comment]
Yes what co blobs ter said
