### ISSUE TITLE
Rule 3.4

### ISSUE THREAD

**Issue by MarangaI** [EarthMC/EarthMC.net#185]
"Stealing specific blocks for their value is not considered grief and is therefore allowed. This does not apply to easily acquired blocks even if they are valuable to you."
This rule is ridiculous. I was robbed by someone in my /res friend list, and the mods would only roll back a fence that was broken and some other less significant items. However, I was also robbed of my god gear and god tools, but those were not rolled back. If certain items can't be stolen and certain items can be stolen, just make it so that stealing is not allowed in any case at all

**Comment by jkmartindale** [comment]
If this was done in Towny plots, then the theft would be allowed under rule 2.2

**Comment by shirazmatas** [comment]
Please follow format and reopen
