### ISSUE TITLE
[OPINION] EMC - What The %$&£ Is Happening?

### ISSUE THREAD

**Issue by MarkusAurelius124** [EarthMC/EarthMC.net#188]
### EMC - What The %$&£ Is Happening?

For the last several months, a great decline has been happening on a once widely beloved server. From the disabling of Villagers, to lowering the Slot count, from the neglecting new Claim Blocking rule to the frustratingly inactive staff, one is forced to raise the question:
What the %$&£ is happening?

From the dawn of EMC, a community was forged, an alliance of role-playing Minecraft Politicians, striving to create and dominate their piece of the virtual world. From the ordinary player to moderators and admins alike, we were a community of people, banding together for the sake of enjoyment and relief from our mundane lives.
That era has long been forlorn. We, the people, can do naught but sit by and watch with utter helplessness as the server we once enjoyed is being altered and transformed into what can only be described as the lowest layer of Hell - endless queues.
An endless queue to enter the server.
An endless queue to get our support tickets handled.
An endless queue to get our hands on items that we once took for granted due to their scarcity.
Yet, while this might seem like yet another rant, a disgruntled player demanding solutions, that is not the case.
As much as you cannot judge a book by its over, we cannot presume the faults listed above are due to maleficence.
When we are ignorant of the cause of things not going our way, we assume wicked intent - 
That our issues aren't being addressed due to an uncaring, inactive staff. That the decrease of slots is the result of greed.
I wholeheartedly believe that is not the case, and therefore only ask for the following-
Information. Cooperation. Dedication.
To inform us of the reasoning behind decisions that have been made, and those that are yet to come.
To involve us in the inner workings of the server and let us sound our opinions.
And to take the appropriate time to listen and take notice of our criticism.

''Terra Nova'' - New Earth. Lets try to keep this one going for longer than the old one.

Note: This paragraph was released PRIOR to the Neowyld Documents.

**Comment by Barbay1** [comment]
We did talk about another discord server for people to talk to the staff.  Not sure whether the staff or players should create it though.
Since the staff is mostly voluntary, it'll be hard to add another thing to manage.  So are there any (unbiased) volunteers?

**Comment by MarkusAurelius124** [comment]
> We did talk about another discord server for people to talk to the staff. Not sure whether the staff or players should create it though.
> Since the staff is mostly voluntary, it'll be hard to add another thing to manage. So are there any (unbiased) volunteers?

Are you a staff member?

**Comment by shirazmatas** [comment]
please repost in different tickets for each step you would like according to the given format when making a ticket. issues resolving rules, support tickets and website should be here. Issues resolving gameplay on the other github issue tracker.

You can post general discussion threads on the subreddit too at reddit.com/r/earthmc.
