### ISSUE TITLE
Update the website sourcecode + navbar not responsive

### ISSUE THREAD

**Issue by MadeInLithuania** [EarthMC/EarthMC.net#189]
**Add your suggested contents here**
Like I said before, a responsive navigation bar (js, jquery), and also update the code so we can help hunting bugs.

<img width="959" alt="not_r" src="https://user-images.githubusercontent.com/49497113/100291078-184c4080-2f7d-11eb-948c-a1dd17db2545.png">

- __Zuki__

**Comment by jkmartindale** [comment]
The current website is on the beta branch https://github.com/EarthMC/EarthMC.net/tree/beta

**Comment by MadeInLithuania** [comment]
Ty, also fine I'll do it myself
