### ISSUE TITLE
Allow towns to join a nation that's further away than 3000 blocks

### ISSUE THREAD

**Issue by Barbay1** [EarthMC/EarthMC.net#193]
Swrhitzy said something like this:
EarthMC's description states, "A geopolitical sandbox". 
With the 3000 block radius, this isn't the case. This server isn't a geopolitical sandbox, it is a towny server with a collection of small nations.  You can't make an empire on this server. You have to rely on others to make "colony" nations that don't feel a part of your nation. 
So expand the radius to at least 10,000 blocks, or just abolish it.

**Exact wording of the rule**
Some nations are popular.  
Increase the distance from a nation that a town is allowed to join.
(Distance: 3,000 blocks to 10,000 blocks, or remove the block limit entirely)

**How will this rule affect the community**
Allow towns further away than 3000 blocks to join a nation.

**Do you think this will benefit both the staff and the players**
Players have more choice which nation they join, and the towns might be able to spread out more and it won't be as crowded.
Allows bigger empires to be created with perhaps more direct control over provinces.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by MarangaI** [comment]
3000 blocks is already a pretty far distance

**Comment by Barbay1** [comment]
I think it's a special case for some nations, which aren't bounded by geography, but religion.

**Comment by Warriorrrr** [comment]
Wrong repository, should be re-opened on https://github.com/EarthMC/Issue-Tracker/issues

**Comment by Barbay1** [comment]
Are you sure?  It's just a proprosal, not a technical issue.

**Comment by Basically-Andrew** [comment]
This repository is intended for the EarthMC Website. The issue-tracker is intended for server related issues.

**Comment by shirazmatas** [comment]
warriorrr is correct, repoen on that issue tracker
