### ISSUE TITLE
Rule 4.3 Clarification required whether dictators and horrible people fall under offensive

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/EarthMC.net#195]
**Exact wording of the rule**
The following account characteristics may not be explicit, sexual, racist or otherwise inappropriate. Famous people throughout history can be used:

    Username
    Nickname
    Player skin
    Towny titles

**How will this rule affect the community**
clarifies names such as hitler, stalin, osama, churchill etc. please comment below for more in depth what it should be

**Do you think this will benefit both the staff and the players**
yes.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by MarangaI** [comment]
Churchill was not a terrible person he literally saved europe from a fascist dictatorship

**Comment by 10op10** [comment]
I agree with the part where no sexually explicit names or racist names, but banning names like Hitler, Stalin ETC. takes the fun out of role play which the server is based on, not everyone wants to be someone boring who just sat in a chair for 4 years and did nothing, not only that you would have to ban nation names like Soviet_Union, Nazi Germany etc.

**Comment by shirazmatas** [comment]
Ok, I reworded it so it would be allowed
