### ISSUE TITLE
Rule 2.12 - A Rule Against Selling Mod Donations 

### ISSUE THREAD

**Issue by hydro78878** [EarthMC/EarthMC.net#197]
**Exact wording of the rule**
Exactly how the rule should be written on the rules page. 'any player found to be selling or trading gifts given by moderators that are unobtainable otherwise will be permanently banned'

**How will this rule affect the community**
Write your opinion on why this rule will be better for the community. mods should not be able to give gifts because this can have major effects on geopolitics 

**Do you think this will benefit both the staff and the players**
Describe how both parties will benefit from this rule. staff will still be able to give gifts to players they like and people will stop being scammed by items, and people will stop being enriched by unfair abuses

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by 3meraldK** [comment]
How the fuck some random gifts are affecting whole geopolitics? For the god's sake tell me that

This suggestion is so awful that it doesn't allow to sell some unneeded items, sometimes a legendary artefacts (for an instance, enchanted golden block, bedrock, dragon's head etc.) Even if for real money, tbh I don't really care. You spend your own cash on whatever you want.

**Comment by shirazmatas** [comment]
All comments are negative, I assume people does not want this rule until proven differently.
