### ISSUE TITLE
Re-add the Custom recipes

### ISSUE THREAD

**Issue by 10op10** [EarthMC/EarthMC.net#198]
When the website was redesigned etc the custom recipes were removed from the FAQ page and most new players are not aware EMC has custom recipes, and players before the website was changed probably don't remember all the custom recipes.

Before the website was changed

![image](https://user-images.githubusercontent.com/63156735/105472929-68513600-5c94-11eb-9072-39e9f24004be.png)

After the website was changed

![image](https://user-images.githubusercontent.com/63156735/105472987-7b640600-5c94-11eb-8441-caccbc008929.png)

**Comment by IAmUnStTV** [comment]
Yes, I agree. I remember needing the recipe for End Rods. You can access the old website at [The Internet Archive](web.archive.org)

**Comment by shirazmatas** [comment]
Please change to follow format

**Comment by SuperChrisBoy** [comment]
I was wondering why it starts at 2 and not 1. Now I know what's missing.

**Comment by shirazmatas** [comment]
No format no ticket
