### ISSUE TITLE
Rule Change for Nation Names.

### ISSUE THREAD

**Issue by ReonBorich** [EarthMC/EarthMC.net#2]
**Is your feature request related to a problem? Please describe.**
Forming rebellions is impossible with the current rule because nations have to be real countries that exist.

**Describe the solution you'd like**
The rules to be change so that anything that has existed is allowed to be a nation. EG ISIS and other similar terrorist groups.

**Additional context**
This would make the idea of civil wars a proper concept.

**Comment by KarlOfDuty** [comment]
Does anyone else support this? Otherwise I will close this issue.

**Comment by Dan1804** [comment]
I agree. I got lucky with my nation single I have 100s of clan names to choose from.

**Comment by ghost** [comment]
I mean, for most places you've just got to pull up a Wikipedia page to find a name. Even Madagascar has rebel namezs, so it really isn't an issue

**Comment by ghost** [comment]
On the contray, I can see why people would want more names, and I like the idea of large regions being accepted under nation names. Northumbria, for example.

**Comment by KarlOfDuty** [comment]
Yes, I agree. How would one define this rule?

**Comment by KarlOfDuty** [comment]
The rules have been updated to support larger regions as names of nations now.
