### ISSUE TITLE
Rule 1.1

### ISSUE THREAD

**Issue by TwitchPid** [EarthMC/EarthMC.net#200]
**Exact wording of the rule**
Exactly how the rule should be written on the rules page.
Cheat clients, macro keys and other modifications which give the player gameplay leverage over other players are not allowed. **Players found breaking this rule will face a permanent ban, and yes, permanent means permanent.**

That, as the rule is now, does not give players a chance to redeem themselves. This means they recieve a permanent ban, and could only be unbanned for a false ban. Players who are caught cheating would of course, learn a lesson from the ban, and could assure mods that they will not cheat again. This is how it **should** be:

Cheat clients, macro keys and other modifications which give the player gameplay leverage over other players are not allowed. Players found breaking this rule will face a 30-day ban. This will be recorded as a warn on the player's account for further use. After the 30-day ban, if the player is found breaking this rule in **any** way, they will be **permanently banned.**

**How will this rule affect the community**
Write your opinion on why this rule will be better for the community.
This will change the community by giving players who break this rule a second chance; a chance to redeem themselves. Players currently have no way to appeal a ban of this kind, because of the zero-tolerance policy. This will also make bans less dramatic, as the player of subject's contacts can be assured the player will be unbanned. This may give way to new cheaters popping up, as they know they have more than one chance to cheat, but the current rule is already bad enough.

**Do you think this will benefit both the staff and the players**
Describe how both parties will benefit from this rule.
Mostly, people around a banned player will not be toxic around this subject as they know the player is only facing a temp-ban. The banned player will have enough time to learn the consequences and will see what they have done. They have a second chance to play on one of the best Minecraft Earth servers out there.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by Warriorrrr** [comment]
_when you try to get the rules altered to get yourself unbanned_

**Comment by TwitchPid** [comment]
> _when you try to get the rules altered to get yourself unbanned_

Yah, I'm trying to alter the rules for myself, but it helps with everybody. I don't know why you hate cheaters so much. Mods told me to do this in my ticket.

**Comment by pesetz** [comment]
> I don't know why you hate cheaters so much.

Indeed

**Comment by TwitchPid** [comment]
> > I don't know why you hate cheaters so much.
> 
> Indeed

oops
i called myself a cheater 🤓

**Comment by 10op10** [comment]
Warrior is right, you got banned for cheating and now you want the rules to change because you’re banned, I like EMCs zero tolerance policy because guess what, if they cheated once they are likely to do it again

**Comment by TwitchPid** [comment]
> Warrior is right, you got banned for cheating and now you want the rules to change because you’re banned, I like EMCs zero tolerance policy because guess what, if they cheated once they are likely to do it again

You are right. This is why the player will face a warn, and the suspicious player plugin can be used to track them. If they are caught again, they are perm-banned with no chance of redeemal.

**Comment by gabeeebaby** [comment]
You clearly broke a rule, you even admitted to it. It is one thing if you did something that was in a gray area or could be disputed, but you did something that is a definite permanent ban. You need to deal with the fact that you got caught and move on.

**Comment by TwitchPid** [comment]
> You clearly broke a rule, you even admitted to it. It is one thing if you did something that was in a gray area or could be disputed, but you did something that is a definite permanent ban. You need to deal with the fact that you got caught and move on.

I know what I've done. Every player would do this. I'm taking every chance I can at getting unbanned.

**Comment by SuperChrisBoy** [comment]
I guess Karl will say one word: "nope"

**Comment by jkmartindale** [comment]
This didn't work when another cheater tried to change the rule (#96), don't think this is going to do any better xd

**Comment by 3meraldK** [comment]
> > _when you try to get the rules altered to get yourself unbanned_
> 
> Yah, I'm trying to alter the rules for myself, but it helps with everybody. I don't know why you hate cheaters so much. Mods told me to do this in my ticket.

Hating cheaters is the most right thing everyone should do. Banning them, too. But on the other side, I can agree with you - those punishments shouldn't be permament. As I never cheated in my whole Minecraft history for making profits or having other benefits, I really hate people using hack clients smh

But giving second chance after the very long punishment should teach smarter ones that cheating is not tolerable and rules are very strict.

**Comment by byemc** [comment]
> Mods told me to do this in my ticket.

I don't believe that. Wouldn't that defeat the purpose of the rules in the first place?

**Comment by DeadGlamour** [comment]
I mean, big servers like hypixel have a 30 days ban, but then again they have an auto ban while we have 2 active mods...

**Comment by 10op10** [comment]
To be honest EMC should get an anti cheat plugin, but lag would need to be fixed first as it may trigger false bans

**Comment by byemc** [comment]
> To be honest EMC should get an anti cheat plugin, but lag would need to be fixed first as it may trigger false bans

I've used cheat clients before (only when i was checking out an anarchy server) and they have protections _against_ anti-cheat. This might work if EarthMC gets a _good_ anti-cheat.

**Comment by TwitchPid** [comment]
> > Mods told me to do this in my ticket.
> 
> I don't believe that. Wouldn't that defeat the purpose of the rules in the first place?

![Screenshot_20210125-144344_Discord~2](https://user-images.githubusercontent.com/77942629/105765417-06a3fc80-5f1e-11eb-82f3-018a527f010d.jpg)

**Comment by MarangaI** [comment]
> > > Mods told me to do this in my ticket.
> > 
> > 
> > I don't believe that. Wouldn't that defeat the purpose of the rules in the first place?
> 
> ![Screenshot_20210125-144344_Discord~2](https://user-images.githubusercontent.com/77942629/105765417-06a3fc80-5f1e-11eb-82f3-018a527f010d.jpg)

Mods say this for every single ticket, regardless of the rules.

**Comment by Taffffy** [comment]
Just don't cheat in the first place, if you do you deserve a permanent ban and should only have it revoked if you can prove you are innocent. Otherwise why follow the rule at all..

**Comment by byemc** [comment]
I actually have a non-EarthMC example. 

Whenever copyright law changes in whatever country, all copyrighted works _after_ that law was put in place will follow _that_ law. Anything that came before it that was copyrighted _before_ will still fall under the _old_ rules.

**Comment by byemc** [comment]
So anyone banned _before_ the new rules in place should fall under the same thing, _right_? Sure, I'll never know unless I get a confirmation from a mod(erator).

**Comment by 10op10** [comment]
> So anyone banned _before_ the new rules in place should fall under the same thing, _right_? Sure, I'll never know unless I get a confirmation from a mod.

no when the rules change players get unbanned eg Louisdek

**Comment by byemc** [comment]
> > So anyone banned _before_ the new rules in place should fall under the same thing, _right_? Sure, I'll never know unless I get a confirmation from a mod.
> 
> 
> 
> no when the rules change players get unbanned eg Louisdek


Ah ok thanks.

**Comment by sillymilk** [comment]
lmao

**Comment by shirazmatas** [comment]
> 
> 
> > Mods told me to do this in my ticket.
> 
> I don't believe that. Wouldn't that defeat the purpose of the rules in the first place?

we tell people that always if they think the rule is unfair they have to prove it in the github and build a consensus. if enough people think its unfair then it's changed. This issue is exactly filling its purpose to show what people think.

**Comment by byemc** [comment]
Ah

**Comment by TwitchPid** [comment]
ok
