### ISSUE TITLE
Rule 3.1 - Destroying land in or around claims

### ISSUE THREAD

**Issue by MarkusAurelius124** [EarthMC/EarthMC.net#201]
_To whom it may concern,_
**Rule 3.1 states:**
Players may not damage land in or around claims (griefing). Players breaking this rule will be warned and damage will be rolled back. Players doing this more than once may face a permanent ban. Placing and removing blocks during siege war events is allowed when necessary to the extent needed in the conflict.

**Examples of grief (but not limited to):**

Cobble monsters – Mountain-like structures that are built using lava and water.
Lava/water curtains – Placing rows of lava/water in the sky to make a wall of falling lava.
**TNT craters.**
Mass spawning entities within or around a town (Chickens, Boats, etc.).

My inquiry is into "TNT Craters", or more specifically - The use of TNT on EMC.
.
.
.
**Why, on a server that claims itself to be a Geopolitical Minecraft server, are Explosives absolutely useless?**
They have literally limitless uses in wars, and this one rule outlaws all of them.
Considering that land blown up by TNT regenerates, why are these absurd, draconic restrictions still in place?
And I'm only referring to TNT, as its removal from the list of "griefing examples" can absolutely co-exist with the rest of the rules.

EDIT: I was made aware TNT craters don't regenerate anymore. The question of making what should be a large aspect of a Geopolitical Earth server practical still remains.

**Comment by DeadGlamour** [comment]
Meh it's a garbage weapon anyway, beds and crystals are where it's at.
Also, there used to be a super tnt mcmmo feature which was locked out because server bad

**Comment by gustasmarcinkevicius** [comment]
LOL in some servers, you can’t even get TNT, so yeah. It is a very good rule.

**Comment by byemc** [comment]
Sand is _very_ rare on EMC, go digging for sand and get killed by some guy with a grudge against you for stealing their sand

**Comment by shirazmatas** [comment]
Please follow format
