### ISSUE TITLE
Griefing

### ISSUE THREAD

**Issue by gustasmarcinkevicius** [EarthMC/EarthMC.net#202]
Griefing

Do NOT put innapropriate paintings or make a infinite room in the base you want to grief. You will be permanently banned by staff.

Well, some people make innapropriate paintings and put them in their friend’s base. And if the player is under 16, he doesn’t know what IT is. 

It will benefit only the players, because the players will live in a nice, quiet base. 

Contact me at gustasmarcinkas@outlook.com if you need to talk with me. If a random person decides to SPAM MY E-MAIL, I will block you.

**Comment by gustasmarcinkevicius** [comment]
If any staff sees this and want’s to contact me, e-mail me.

**Comment by jkmartindale** [comment]
> If a random person decides to SPAM MY E-MAIL, I will block you

Is this a challenge? 👀

**Comment by gustasmarcinkevicius** [comment]
No sir.

**Comment by shirazmatas** [comment]
Please follow format and I  will reopen
