### ISSUE TITLE
Rule 3.6 Illegal Map Art

### ISSUE THREAD

**Issue by ghost** [EarthMC/EarthMC.net#203]
**Exact wording of the rule**

Your map art may not contain nudity, sexual content, racist imagery or anything else that breaks any part of rule 2.

**How will this rule affect the community**
This Github issue is being created because of the unbalanced enforcement of illegal map arts. 

1.  I understand the staff teams reasoning for banning certain map arts. As much as it would be nice to have an unregulated market, Full nudity and explicit sexual content is against Minecraft's EULA. See here: [EULA](https://account.mojang.com/documents/minecraft_eula) (Just control+F and search for "Illegal" to find the correct section regarding this information). 
2.   The EULA only states "porn", I personally believe the staff team has over moderated the map art community and has banned many non-porn pieces.  

See Below:

[Banned 1#](https://cdn.discordapp.com/attachments/743017606369247283/766951215938011156/Ahegao6.png)
[Banned 2#](https://user-images.githubusercontent.com/67532219/114961130-09800080-9e2e-11eb-8ed1-f7090839db73.png)
[Banned 3#](https://cdn.discordapp.com/attachments/743017606369247283/766948885917728768/Ahegao1.png)
[Banned 4#](https://cdn.discordapp.com/attachments/743017606369247283/766946777575981056/2020-10-17_02.44.10.png)
[Banned 5#](https://cdn.discordapp.com/attachments/743017606369247283/766951338553638942/Ahegao8.png)
[Banned 6#](https://cdn.discordapp.com/attachments/743017606369247283/766951373774127124/Ahegao9.png)
[Banned 7#](https://cdn.discordapp.com/attachments/743017606369247283/766951589935185930/Ahegaomaybe2.png)
[Banned 8#](https://cdn.discordapp.com/attachments/743017606369247283/766955033690243072/unknown.png)
[Banned 9#](https://cdn.discordapp.com/attachments/743017606369247283/828489737525526548/unknown.png)
[Banned 10#](https://cdn.discordapp.com/attachments/743017606369247283/757728907574116422/unknown.png)
[Banned 11#](https://cdn.discordapp.com/attachments/743017606369247283/757728947000836170/unknown.png)
[Banned 12#](https://cdn.discordapp.com/attachments/743017606369247283/766949964555223060/Ahegao3.png)

There are many more map arts that will fall under this list. Some in this list have a disputed legality. **_That is the issue here.*_* One mod will say a map is illegal and you will get warned for it. Even though dozens of mods may have walked past and had no issue with it. We need a base line here and no more stupid mod interpretations. 

3.   Maps with over sexualization (Woman in tight bikinis or thongs) are currently banned. I agree with that decision. But maps that show no cleavage and no obvious explicit material should not be banned. For example. "Nice Cock" is a meme and the map art is posted all over the server. You can find this meme all over the internet and **on Google**. Recently a staff member claims "this was banned" even though numerous other staff members have contradicted this statement.  **_If Google, a multibillion dollar company that uses safe search algorithms to remove porn and sexual content from its image searches, deems this content "Safe" then why cant EMC?_** (FYI they also deem Ahego, non explicit content) (See below)

4.  Many "Ahego" maps are banned because "simply because someone said they are sexually explicit". With that logic I could say a map art of a grapefruit is "something else".... That does not make it sexual explicit. [Vice News article on Ahego.](https://www.vice.com/en/article/7kz7be/anime-porn-fetish-ahegao-hentai-censorship) This article talks about Ahego and how its creation was to circumvent Japanese pornography laws. _**That right there should be enough to show that this is not pornography**_. In other words, Ahego is not defined as explicit pornography in Japan, Its not deemed explicit by Google, and not deemed explicit under US government pornography standards.
### Describe the solution you'd like

Map Art rules need to be reformed in these ways:

- Full nudity and overly sexual mapart with explicit materials stay banned
- Any mapart outside of this category should be deemed legal.
- Ahego map arts are deemed legal as they are not deemed explicit by numerous credible sources. 
- A clear and consise list of banned maps are created and can be referenced by staff. Right now mods go off of judgement and can be biased in some cases. I have had my own legal maps stolen by mods who "thought" they were illegal. I know some maps are recorded in a list but this is far from complete.

**Do you think this will benefit both the staff and the players**
Yes.

Players can be homophobic on EMC and not get banned/warned/muted/ and often verbally warned by staff.  I have reported players for homophobic slang and harassments and mods have said they cannot do anything. This is against Minecraft's EULA. Clearly staff don't care so why would looking at a Luigi butt be offensive and a overinterpretation of Minecraft's EULA for pornography be needed?

**Comment by Chotobits** [comment]
If mods will not address this issue and instead will just sweep it away because they don’t want to deal with this issue then players should not hold respect to their authority.

**Comment by jkmartindale** [comment]
> If Google, a multibillion dollar company that uses safe search algorithms to remove porn and sexual content from its image searches, deems this content "Safe" then why cant EMC?

Because it's an algorithm with very little manual review that is trained on traditional, photographic pornography, and less so on nonrealistic depictions. This is why you can find yiff with SafeSearch turned on, for example...and I don't think you think that's safe for EarthMC. An algorithm is not a "credible source", as you call it.

**Comment by Colt44Magnum** [comment]
Nice Cock

**Comment by ghost** [comment]
> > If Google, a multibillion dollar company that uses safe search algorithms to remove porn and sexual content from its image searches, deems this content "Safe" then why cant EMC?
> 
> Because it's an algorithm with very little manual review that is trained on traditional, photographic pornography, and less so on nonrealistic depictions. This is why you can find yiff with SafeSearch turned on, for example...and I don't think you think that's safe for EarthMC. An algorithm is not a "credible source", as you call it.

Just my opinion. Players are already exposed to other "mature" content on the server. No reason why map art should be solely targeted in the name of a PG rating.

**Comment by coblobster2** [comment]
> > > If Google, a multibillion dollar company that uses safe search algorithms to remove porn and sexual content from its image searches, deems this content "Safe" then why cant EMC?
> > 
> > 
> > Because it's an algorithm with very little manual review that is trained on traditional, photographic pornography, and less so on nonrealistic depictions. This is why you can find yiff with SafeSearch turned on, for example...and I don't think you think that's safe for EarthMC. An algorithm is not a "credible source", as you call it.
> 
> Just my opinion. Players are already exposed to other "mature" content on the server. No reason why map art should be solely targeted in the name of a PG rating.

not really anymore. there has been a crackdown on this. Chat has been changing and what is allowed to be said has been changing too.

**Comment by coblobster2** [comment]
Personally 9 7 4 I think could or should be legal, but ahegao faces are sexual they literally are considered a fetish. In the article you shared it says 
"In a different context, there's nothing technically sexual about the hentai facial expression known as ahegao. It's definitive features include crossed eyes, flushed cheeks, and a lolling, drooling tongue—and on their own, none of these are explicit. A face that looks like this could plausibly represent anything: someone in pain, or extreme ecstasy, or lusting after a really good meal.

But even if you're a very, very offline adult, you can look at an ahegao face and know something else is going on outside the frame. And from ahegao's origins, that's by design."

I agree we do not need to go off the grandparents or parents rule (The rule is if you would not show them then do not make it) and that the actual rule should be clearer as with others but it still does need to be pretty strict as there is a very wide age group of people that play on the server and after all it is Minecraft and not an incognito tab.

**Comment by solamint** [comment]
>>>> If Google, a multibillion dollar company that uses safe search algorithms to remove porn and sexual content from its image searches, deems this content "Safe" then why cant EMC?

>>> Because it's an algorithm with very little manual review that is trained on traditional, photographic pornography, and less so on nonrealistic depictions. This is why you can find yiff with SafeSearch turned on, for example...and I don't think you think that's safe for EarthMC. An algorithm is not a "credible source", as you call it.

>> Just my opinion. Players are already exposed to other "mature" content on the server. No reason why map art should be solely targeted in the name of a PG rating.

> not really anymore. there has been a crackdown on this. Chat has been changing and what is allowed to be said has been changing too.

So chat has been changing huh? People are still spilling their shitty political takes, saying homophobic things, argue over jack shit, and you're saying it's changing? Very odd. Chat has been like that since I joined EMC again. I don't think it's changing.

**Comment by coblobster2** [comment]
> > > > > If Google, a multibillion dollar company that uses safe search algorithms to remove porn and sexual content from its image searches, deems this content "Safe" then why cant EMC?
> 
> > > > Because it's an algorithm with very little manual review that is trained on traditional, photographic pornography, and less so on nonrealistic depictions. This is why you can find yiff with SafeSearch turned on, for example...and I don't think you think that's safe for EarthMC. An algorithm is not a "credible source", as you call it.
> 
> > > Just my opinion. Players are already exposed to other "mature" content on the server. No reason why map art should be solely targeted in the name of a PG rating.
> 
> > not really anymore. there has been a crackdown on this. Chat has been changing and what is allowed to be said has been changing too.
> 
> So chat has been changing huh? People are still spilling their shitty political takes, saying homophobic things, argue over jack shit, and you're saying it's changing? Very odd. Chat has been like that since I joined EMC again. I don't think it's changing.

yeah the homophobic has been getting cracked down on more. the other stuff is just normal emc chat

**Comment by solamint** [comment]
I also want to mention that *true* homophobia is being let by freely, while unintended "homophobia" (like me telling someone what the F slur is) is not allowed. It seems as if only slurs are homophobic, but the true meaning isnt, like referencing the Bible to say "gay is a sin".

**Comment by coblobster2** [comment]
> I also want to mention that _true_ homophobia is being let by freely, while unintended "homophobia" (like me telling someone what the F slur is) is not allowed. It seems as if only slurs are homophobic, but the true meaning isnt, like referencing the Bible to say "gay is a sin".

yeah that is next step I think

**Comment by solamint** [comment]
Why should it be in steps? Shouldnt it all be enforced all at once? Do you realize how stupid saying "yea we banned slurs, but never actually filtered them and allowed the bypass of slurs, and we arent cracking down on the bad things that can be conveyed without using the slurs" actually is?

**Comment by coblobster2** [comment]
> Why should it be in steps? Shouldnt it all be enforced all at once? Do you realize how stupid saying "yea we banned slurs, but never actually filtered them and allowed the bypass of slurs, and we arent cracking down on the bad things that can be conveyed without using the slurs" actually is?
> […](#)
> On Apr 19, 2021, at 00:06, coblobster2 ***@***.***> wrote: ﻿ I also want to mention that true homophobia is being let by freely, while unintended "homophobia" (like me telling someone what the F slur is) is not allowed. It seems as if only slurs are homophobic, but the true meaning isnt, like referencing the Bible to say "gay is a sin". yeah that is next step I think — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

well I think we have to an extent. a lot of what is muted and warned in chat is not public and I do not really do chat stuff so I do not know. I just find the rule to vague and everyone has different opinions on what should be and shouldn't and then it gets into politics.

**Comment by americanfrog** [comment]
allow all maps to be made. Let people choose what is good and what is not good.

**Comment by americanfrog** [comment]
i am not a clown im a frog

**Comment by solamint** [comment]
time to make several racist, antisemetic, sexist, homophobic, xenophobic, transphobic, lolicon hentai porn maparts

**Comment by Takii-Takii** [comment]
Oh shut up, learn to take a joke smh

**Comment by solamint** [comment]
that *is* a joke

**Comment by Takii-Takii** [comment]
Thats why you complained about it outside of here x)

**Comment by ghost** [comment]
@coblobster2 
Putting Ahego to the Side. Please tell me why Luigi butt and Nice Cock should be banned

**Comment by coblobster2** [comment]
> @coblobster2
> Putting Ahego to the Side. Please tell me why Luigi butt and Nice Cock should be banned

nice cock I said should be legal. the luigi one also I just did not put that.
