### ISSUE TITLE
Mcmmo Parties 

### ISSUE THREAD

**Issue by Conmqn** [EarthMC/EarthMC.net#205]
So I love the parties for MCMMO but there needs to be changes.
I feel one change needed is like a rank for people to give to add others and kick others from the party so not one single person has to do that so it can work out smoother for nations/alliances with wars/pvp. 
That's my main concern for now about Parties right this moment.

**Comment by JaVolimKatarinu** [comment]
Please refer to [MCMMO Issue tracker](https://github.com/mcMMO-Dev/mcMMO/issues), as this can't be done by the EMC staff team.
