### ISSUE TITLE
Dynmap not working

### ISSUE THREAD

**Issue by TWRS1** [EarthMC/EarthMC.net#206]
Map on the official site stopped working. It says error 502, after then refreshes the page and says map is offline. Is the server not working or something other happened?

**Comment by Warriorrrr** [comment]
The server is currently offline, the dynmap will work again when the server is back up.

**Comment by byemc** [comment]
> Map on the official site stopped working. It says error 502, after then refreshes the page and says map is offline. Is the server not working or something other happened?

![image](https://user-images.githubusercontent.com/77801870/119272605-ad638580-bbfe-11eb-8c5e-397c274aa686.png)
