### ISSUE TITLE
Inactivity Rule

### ISSUE THREAD

**Issue by coblobster2** [EarthMC/EarthMC.net#207]
**Exact wording of the rule**
Inactivity:
If a Mayor goes inactive and only joining the server to save their town/nation from falling they must play at least 5 hours (not including waiting in queue) within a 4 month period. If the mayor does not play the minimum amount and a ticket is made in a reasonable amount of time. The town/nation can be removed or passed to a councilor/chancellor so the land does not become an abandoned wasteland. 

If a Mayor knows ahead of time they will not be around for an extended period of time, they can share and make a ticket.  

*Personally I think the 5 hours is a bit low but felt we should start low and go higher. 

*There is no perfect solution but I do think this is a good start to combat the people who hope on only to save their town. I personally would like a harsher rule than this. 

**How will this rule affect the community**
With the server growing and the amount of gold being spent on land being higher than the amount of land being unclaimed from falling towns in some places there is a shortage of space. One argument that people make to show a flaw in EMC is the lack of space or change in some towns. This rule will hopefully prevent a bit of this. This will also benefit new players as it will help them see an open map to start and make a town somewhere. 

**Do you think this will benefit both the staff and the players**
It will benefit players more than staff. With other rule changes hopefully creating less tickets this may make more but will help the server a bit more.

**Comment by gabeeebaby** [comment]
Having a gold upkeep would be a superior method. Anything where staff has to intervene would lead to problems and cries of abuse. If the upkeep is in gold, it’s in the hands of the server to manage inactivity. It shouldn’t be more than one can reasonably achieve with voting. This also allows players that want to take a break to grind before hand. Some people only play during the summer or vice versa. Nation and town costs should also increase heavily to reduce the amount of inactive towns. Currently anyone can afford to make a nation in less than a month of regular play and a town in a day or two.
