### ISSUE TITLE
Clarify Rule 1.4

### ISSUE THREAD

**Issue by gabeeebaby** [EarthMC/EarthMC.net#208]
The current 1.4 rule says that a “players main account may be warned,” if they use alternate  accounts. This sounds like you may or may not be warned, but the staff team gave communicated that “it means first time you get warned, if you do it again after being warned you will be permbanned.” This makes sense as a rule, but is not said anywhere in the actual rules. The rule should be edited to more clearly reflect what is being enforced.

**Comment by Basically-Andrew** [comment]
Many of earthmc's rules are interpreted by staff and aren't actually enforced how the rule is written. Each rule's wording should be adjusted by how it's actually enforced by staff, so there is no room for confusion or error. For example, rule [2.1 (Teleport Traps)](https://earthmc.net/rules/#:~:text=2.1,or%20more).) is commonly enforced in a 3x3 chunk range of nation spawn, however, no language is used or placed in the rule for players to know this information. This makes the rules to earthmc extremely confusing and hard to understand for not just regular players but new players of earthmc. **PLEASE** improve the wording on each rule or have staff actually enforce rules by their language.

**Comment by coblobster2** [comment]
> Many of earthmc's rules are interpreted by staff and aren't actually enforced how the rule is written. Each rule's wording should be adjusted by how it's actually enforced by staff, so there is no room for confusion or error. For example, rule [2.1 (Teleport Traps)](https://earthmc.net/rules/#:~:text=2.1,or%20more).) is commonly enforced in a 3x3 chunk range of nation spawn, however, no language is used or placed in the rule for players to know this information. This makes the rules to earthmc extremely confusing and hard to understand for not just regular players but new players of earthmc. **PLEASE** improve the wording on each rule or have staff actually enforce rules by their language.

The 3 by 3 became a confusion cause staff thought the ruled changed. This caused mods to rule it mistakenly. Rule changes are way too slow

**Comment by coblobster2** [comment]
> The current 1.4 rule says that a “players main account may be warned,” if they use alternate accounts. This sounds like you may or may not be warned, but the staff team gave communicated that “it means first time you get warned, if you do it again after being warned you will be permbanned.” This makes sense as a rule, but is not said anywhere in the actual rules. The rule should be edited to more clearly reflect what is being enforced.

It is still a case by case basis with anything. If you do something against the rules expect a punishment.

**Comment by gabeeebaby** [comment]
> It is still a case by case basis with anything. If you do something against the rules expect a punishment.

The rules should state exactly what the punishment is so that players don't cry bias. Of course there are going to be special cases, but most of the time its either you did it or no, so the rules should say exactly what the punishment is. I can't think of an alting or teleport trap case where there is an in between. Tickets should not be deciding what the rule means or the disagreement of the wording of the rule, it should be deciding if you actually broke it. If something is enforced by staff, then it should be in the rules, otherwise you can't expect people to follow it. Some of the rules just say that something isn't allowed, but it doesn't clarify whether that is a mute, warn, ban, etc. People shouldn't purposely break the rules, but it would make less room for bias (especially as many staff are nation leaders)
