### ISSUE TITLE
Australia breaking rules

### ISSUE THREAD

**Issue by jacky20022** [EarthMC/EarthMC.net#212]
Hello to whoever is reading this!  

Australia is currently claiming plots directly next to Oceania, this is a problem seeing as Australia and Oceania are not on good relations, and due to the lack of battle they have chosen to hunt any Oceanian they see in the wilderness, hopefully you might be able to fix this

they are in the small + sign on the left hand side, being called Holt

Cheers!
Jack

![image](https://github.com/EarthMC/EarthMC.net/assets/160210241/f4602cc6-e613-4141-a84a-73999678190a)

**Comment by jwkerr** [comment]
https://discord.gg/EZBYmpp
