### ISSUE TITLE
Transferring Donator rank?

### ISSUE THREAD

**Issue by HaydenTownley** [EarthMC/EarthMC.net#25]
Is it possible to transfer donator rank? If its applicable the account i want to transfer from can be banned if it cant be removed.

**Comment by NeonKrby** [comment]
wut

**Comment by ghost** [comment]
Last time I checked that was a no

**Comment by ghost** [comment]
Who would you be transferring it to and why?...

**Comment by Keennoo** [comment]
THIS WOULD BE AMAZING for me personally as I don't play and my rank has... well it's like tripled in value and I know other old people who don't play and wouldn't mind making some cash.

**Comment by KarlOfDuty** [comment]
Make a support ticket/contact staff.
