### ISSUE TITLE
I cannot connect.

### ISSUE THREAD

**Issue by Memelord53** [EarthMC/EarthMC.net#27]
I just cant connect. The server says im disconnected every time I try to join.

**Comment by NeonKrby** [comment]
Meme are you connecting using version 1.13.2 and do you also legally own a minecraft account?

**Comment by Memelord53** [comment]
yes i do own a legal account and yes im using 1.13.2

**Comment by NeonKrby** [comment]
then ask the mods in game not in github

**Comment by Memelord53** [comment]
jeez sorry
