### ISSUE TITLE
Ocean Cities (within reason)

### ISSUE THREAD

**Issue by RangerMK01** [EarthMC/EarthMC.net#29]
I recently have entertained the idea of designing a futuristic city, specifically one built in/over an ocean.
I understand there are rules against ocean platforms, but I was curious if we could work to make the rule more specific. Example, random and ugly platform are not allowed, but well designed builds such as ships, oil rigs, and ocean styled cities would be permitted.
Just an idea, and I was curious for the sake of me wanting to build an epic ocean city.

**Comment by KarlOfDuty** [comment]
Seems fair, write the rule and I'll throw it in there.

**Comment by shirazmatas** [comment]
@RangerMK01 ticket will be closed if no answer
