### ISSUE TITLE
[Rules] Contents of rail greifing rule

### ISSUE THREAD

**Issue by KarlOfDuty** [EarthMC/EarthMC.net#3]
Now that powered rails are not valuable anymore we may want to classify destroying railways as greifing instead of stealing. The same as we do for other non-valuable blocks.

Thoughts?

**Comment by ghost** [comment]
Tunnels of ice and iron will bring the word together.

**Comment by KarlOfDuty** [comment]
At the moment we would rather limit this to railways rather than ice roads too.  Anyway, what do you think of this: https://earthmc.github.io/EarthMC.net/rules.html

**Comment by KarlOfDuty** [comment]
At the moment we would rather limit this to railways rather than ice roads too. Anyway, what do you think of this: https://earthmc.github.io/EarthMC.net/rules.html

**Comment by Dan1804** [comment]
One part you lot are forgetting. Allow destruction of transportation if and only if two nations are at war.

**Comment by ghost** [comment]
> One part you lot are forgetting. Allow destruction of transportation if and only if two nations are at war.

No, that's a bit dumb.

**Comment by SignatureChewy** [comment]
Because of the scale and method of minecraft pvp, its unrealistic that a nation could ever defend its rail network from its enemies, even if they're winning the war. Destruction of rails during war would be no different than the current griefing problem we are trying to avoid.

**Comment by Arganog** [comment]
> Destruction of rails during war would be no different than the current griefing problem we are trying to avoid.

I agree: Allowing destruction of rails when "at war" is pretty much exactly how things are now.
Players don't currently break rails that belong to their own nation or allies, they break "enemy" rails (or just break them to be trolls)

**Comment by KarlOfDuty** [comment]
The change has been pushed live. ac12dfec156db7ea98c25d60c9aa41acf9c9a544
