### ISSUE TITLE
[Plugin] Can we get a list of McMMO server changes

### ISSUE THREAD

**Issue by Sabatarge** [EarthMC/EarthMC.net#30]
This server seems to have a lot of McMMO settings that aren't the result, i've leveled a few skills now like unarmed to a high level and been told that several elements of it (including player damage) are disabled, just leveled my axes to a high level and been told that all McMMO combat damage is related. Talked to a few mods and non seem to be sure what does and doesn't work.

If we could just get a list of the changes and know what is and isn't disabled on the server it would be helpful.

Also please enable combat McMMOs, it rewards loyalty to the server

**Comment by DasCodes** [comment]
mcMMO settings were made available on the FAQ page a few months ago. https://earthmc.net/faq#mcmmo
