### ISSUE TITLE
Question about if a certain mod is allowed

### ISSUE THREAD

**Issue by storoonnik** [EarthMC/EarthMC.net#31]
So I'm not sure if 5zig (https://www.5zig.net/features) is allowed on the server

It has normal, not cheat-y features such as a friends list and (why I wanted to use it) a "2nd chat" which uses filters to sort chat messages (ex. DMs, /tc, etc.) into a second chat window.

However, it allows the user to create macros, which is against the EMC rules:
"_Cheat clients, macro keys and other modifications which give the player gameplay leverage over other players are not allowed._"

I won't use the macros, but I'm not sure if that's good enough

**Comment by storoonnik** [comment]
From the link above https://www.5zig.net/features
- Easy & Simple player information
Displays:
- A way more precise FPS-Counter that is updating every 1/50th second
- Your coordinates with a selectable precision
- Your Direction
- Your active potion effects
- Your armor status
- Your biome
- Your ping to a server
- How many players are connected to the server you are playing on
- Your current time
- Entity count
- Formatting options. Change the colors and formatting of the mod
- Supporting many different minigame servers and shows all kinds of stats when playing on them:
timolia.de
gommehd.net
mc.hypixel.net
mc.playminity.net
mineplex.com
- Scalable from 50% to 150%
- Choosable location of the player information, the server stats, your armor status and your potion effects in the mod options
- Friends!
- Introducing a new Friend-System to the 5zig Mod.
- Add unlimited friends, chat with them and have even more fun playing Minecraft.
- All Friends can be viewed in a List.
- Each Friend has an own Profile-Page, where you can see his current Profile Message, if he is online, his server he is playing on, the last online time of him and his avatar skin. (player heads powered by cravatar.eu)
- Select Friends as favorites to let them appear at the very top of your friends List. They will also have a shiny yellow star next to them so that you can find them even faster.
- Ultra-fast sending of messages via Java NIO
- Very little traffic while chatting.
- Send messages to your Friends, even if he is not online! Your Friend will then receive the messages as soon as he goes online.
- Set a Notification Behavior individually for each conversation you have.
- Message Statuses! See, if your message has been sent to the server, delivered or even read by your Friend
- The time of the Message is shown directly next to it
- The date of the Messages is shown in the center of the Chat-GUI
- Chats are saved offline, meaning that you can always have access to them, even if you are not connected.
- You can change the background of the Chat GUI, or even make it transparent.
- Get a Tray Notification when receiving new messages while the Minecraft window is not focused
- Enable Message-Sounds to hear a sound when you receive any new message
- You can also change these sounds! Simply create a resource pack, containing an
assets/the5zigmod/sounds/chat/
folder and both
message_receive.ogg
and
message_send.ogg
sound files.
- Alternatively, you can also change the message sounds located in
.minecraft/libraries/eu/the5zig/The5zigMod/1.8.4_3.0/The5zigMod-1.8.4_3.0.jar/assets/the5zigmod/sounds/chat/
- An example for such a Sound Pack can be found here.
- See if your Friend is currently typing!
- Very customizable privacy settings. Chose if you want to be able to connect, if you want to be shown online for your friends, if you want to show your server, if you want that other players see that you read their messages, if you want to be able to receive friend requests, if you want to receive chat and group chat notifications and if you want to see a notification if someone of your friends goes online.
- You can also click on Links in the Chat-GUI
- Use the arrow keys to scroll through your last sent messages.
- Online-Statuses:
- Choose between “Online”, “Away” and “Offline”
- You will be set to “Away” automatically after 10 minutes. You can also change that time in your profile settings.
- If you have donated, you name will be displayed with a Green Prefix (if you donated for a default cape) or with a Gold Prefix (if you donated for a custom cape). You will also be able to write with colors in chat, using the ‘&’ char and a Minecraft color code. You will also be able to connect, even if the Server is full.
Group Chats!
- Create unlimited Group Chats with up to 50 Members!
- Chat with multiple Friends at once!
- Group Chat Messages will be saved offline as well
- If there were new Messages in your Group while you were not online, you will receive them when you are back online again!
- As an owner, you can manage your group and group members even after you already created your group
- Add new Group Members
- Remove Members out of your Group
- Rename your group
- Transfer your ownership
- Promote players as administrator
- Delete your group
- Give Group Members the Administrator rank and allow them to manage group members and edit the name.
- 2 options for your coordinates: Display them side by side of one below the other
- A Gui where you can save coordinates so that you don't have to remember them anymore
- Available in different languages, which are located at
.minecraft/the5zigmod/lang
- Nearly everything of the mod is toggleable
Toggle if you want to:
- Show your coordinates
- Show your FPS
- Show your Direction
- Show your Ping
- Show the ip of the server you are connected to
- Show how many players are connected to the server you are playing on
- Show your potion effects
- Show your armor status
- Show a large invincibility time
- Show large killstreaks
- Show server stats
- Show all labels (except the label in the left top corner)
- Show your biome
- Show your ping to the server you are playing on
- Show your current time
- Lots and lots more
- Chat Filter
-Add Chat Messages to your Filter List and Ignore them ingame
-Use wildcard characters like “*” or “?” to easy match messages. You can escape those characters with “\”
-Messages that eg. Spam your chat on specific servers can be easily ignored
-Messages can be also server specific ignored.
-Manage all your chat messages in a fancy GUI
Tutorial: https://youtu.be/g5OOfjKMTIA

**Comment by KarlOfDuty** [comment]
Yes, chat and displaying stats is fine, but I'd like a list of anything that could possibly affect gameplay and this list isn't descriptive enough to tell from looking at it.

**Comment by storoonnik** [comment]
[This video](https://www.youtube.com/watch?v=vHizxVPbBVU) shows the macros in action; the command could be changed to something more affective (ex. /suicide, /t withdraw, /n spawn, etc.)

**Comment by KarlOfDuty** [comment]
It's fine as long as they are only chat macros.

**Comment by storoonnik** [comment]
Alright, thanks!
