### ISSUE TITLE
[New rule] Extend rule 3.1 partly to "in claims"

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/EarthMC.net#32]
Rule 3.1 states that:
>Players may not damage terrain around claims (griefing). Players breaking this rule will be warned and damage will be rolled back. Players doing this more than once may face a permanent ban. Please note that mayors/kings are responsible for misconfigured town/nation permission settings. Examples of grief:
  Cobble monsters - Mountain-like structures that are built using lava and water.
    Lava/water curtains - Placing rows of lava/water in the sky to make a wall of falling lava.
    TNT craters.
    Mass spawning entities within or around a town (Chickens, Boats, etc.).

 However I believe it is unfair to a certain extent to put the blame on mayors for allowing certain plots to be used by everyone;whether it be mining plots or train stations. Further more I do believe theft should still be allowed but just tearing down public property should not.

One exception would be that users OWN plot would be free to be changed as much as they deem fit.

New text:

>  3.1 Destroying land in and around claims.
Players may not damage terrain around or in claims (griefing). Players breaking this rule will be warned and damage will be rolled back. Players doing this more than once may face a permanent ban. The rule is exempt in self-owned plots
Examples of griefing are:
    Cobble monsters - Mountain-like structures that are built using lava and water.
    Lava/water curtains - Placing rows of lava/water in the sky to make a wall of falling lava.
    TNT craters.
    Mass spawning entities within or around a town (Chickens, Boats, etc.).

**Comment by ghost** [comment]
Yeah the blame shouldn't be on mayors thats ridiculous. It also does not say who is responsible: is it mayors or kings? It can't be both. How would you decide who gets the blame? If someone griefs it should be the person griefing who gets the blame. Otherwise people could join towns, buy a plot, make cobble monsters etc... and not be liable.

**Comment by ghost** [comment]
Holy fuck this issue is almost a year old I thought it was a new recent one

**Comment by KarlOfDuty** [comment]
I think this would create an issue where mayors don't bother with the permission system because staff would just deal with it for them instead. We need the mayors to have responsibility for their own towns themselves.
