### ISSUE TITLE
Player Abuse

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/EarthMC.net#33]
"2.4 Toxicity.
Toxicity is not allowed on this server. Toxicity in chat can be for instance using racial slurs, sexual harassment or severely explicit language. It can also be other non-chat actions which drive players away from the community, for instance luring newly joined players to your town so you can kill them or lock them in your town jail."
![2019-04-18_20 17 58](https://user-images.githubusercontent.com/46413791/56398983-849b8580-6219-11e9-9467-831f47788ca6.png)
![2019-04-18_20 21 23](https://user-images.githubusercontent.com/46413791/56398984-85ccb280-6219-11e9-89ea-91e86f6a31cd.png)
![2019-04-18_20 22 04](https://user-images.githubusercontent.com/46413791/56398986-87967600-6219-11e9-88b8-eb5b67bb897f.png)
![spawntrap](https://user-images.githubusercontent.com/46413791/56399017-b0b70680-6219-11e9-8501-8776228eaa02.PNG)
![2019-04-18_20 41 09](https://user-images.githubusercontent.com/46413791/56399167-7dc14280-621a-11e9-8439-1e0984b2e952.png)
![2019-04-18_20 53 32](https://user-images.githubusercontent.com/46413791/56399472-2623d680-621c-11e9-8a49-76522b0d9191.png)

Somerset users spawntrapping and repeatedly killing me - Using poison potions so we can't tp out and magma blocks too

**Comment by gabbobler** [comment]
So does Qin?
