### ISSUE TITLE
Remove rule 2.4

### ISSUE THREAD

**Issue by Renarchat** [EarthMC/EarthMC.net#34]
Rule 2.4 has the homo
"2.4 Toxicity.
Toxicity is not allowed on this server. Toxicity in chat can be for instance using racial slurs, sexual harassment or severely explicit language. It can also be other non-chat actions which drive players away from the community, for instance luring newly joined players to your town so you can kill them or lock them in your town jail.

Toxicity is determined on a case-by-case basis by staff. Repeated violations may lead to warnings, mutes and eventually a permanent ban."

**Comment by KarlOfDuty** [comment]
We will not be removing the toxicity rule.
