### ISSUE TITLE
EarthMC Dynamic Map is not working

### ISSUE THREAD

**Issue by DoctorSnakes** [EarthMC/EarthMC.net#36]
The dynamic map stopped working for me today for some reason while using Firefox. It works fine on my android.
Not sure if this will help but I found this error in the Inspect Element console:
The resource from “https://earthmc.net/map/js/map.js?_=3.0-beta-3-160” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

**Comment by KarlOfDuty** [comment]
Yes, something went wrong when reconfiguring the web server for the classic server's map before, we will work on it later today.

**Comment by KarlOfDuty** [comment]
Fixed.
