### ISSUE TITLE
Count breaking railways as griefing

### ISSUE THREAD

**Issue by ghost** [EarthMC/EarthMC.net#4]
Do you hate it when people keep breaking the railways you've built for ease of transport? Well, I do!
Currently, breaking railways is considered "stealing" which is allowed. However, on TerraNova, the creators want realism.

In the real world, do people break railways that the government built? Well, they could, but they would be sent to jail. They won't just say, "Oh he's just stealing our railways that we've spent tax dollars on."

**Solution: Count breaking railways as griefing.**

A simple solution to a simple problem.

Thank you for reading.

**Comment by Coffeetom** [comment]
I would recommend taking a look at Australia, Say Melbourne to CapeNaturaliste. How would we be expected to claim those 5 thousand blocks. Your plan is simply unreasonable and a complete waste of resources

**Comment by KarlOfDuty** [comment]
Done.
