### ISSUE TITLE
im banned for fly (Bor4N)

### ISSUE THREAD

**Issue by Bor4N** [EarthMC/EarthMC.net#41]
:(

**Comment by TinyBolts** [comment]
Your fault. You cheated and i bet the mods dont care about feelings of people that cheat.

**Comment by MasterMence** [comment]
No one told your stupid ass to cheat did they LOOOOOOOOL.

**Comment by WhitPlayzYT** [comment]
this isnt the place for ban appeals
its your own fault for hacking

**Comment by FutureCW** [comment]
If you cried the day you got banned I’m pretty sure you should spend more time with friends not playing games

**Comment by Kyoris** [comment]
ikr lol
if i got banned ofc i'll be a bit upset (i mean i've spent a shit ton of time on the server) but it's not the end of the world
also it's your own fault for using a client in the first place lmao

**Comment by ghost** [comment]
This is not the place to seek support or appeal your ban.
