### ISSUE TITLE
[Idea] Disband inactive towns

### ISSUE THREAD

**Issue by TinyBolts** [EarthMC/EarthMC.net#42]
There are some people hogging popular towns all for themselves without a big town or any other citizens. I think it would be a good idea to disband those inactive towns so others could take that name. For example the tiny chernobyl which only has 1 person in it - the mayor.
![ac95060f5f1115af9910df476cf4ec0a 1](https://user-images.githubusercontent.com/17342303/57196027-78c1fa00-6f61-11e9-9f29-4aac491682e1.png)

Im talking only about the popular town names that everybody knows.

I really just wanna take chernobyl with my friends and build it to be a nice town and thats why i made this xd.

**Comment by WhitPlayzYT** [comment]
its been a feature it just doesnt work automatically

**Comment by unown006** [comment]
There is already a system in place for this it is called town falling

**Comment by TinyBolts** [comment]
> There is already a system in place for this it is called town falling

oh didnt know...

**Comment by TinyBolts** [comment]
> its been a feature it just doesnt work automatically

if not automatic how does it work?

**Comment by Kyoris** [comment]
I mean you could go for New Chernobyl until it falls, but idk where you're gonna put it considering my town of Pripyat basically encompasses the entire CEZ

**Comment by TinyBolts** [comment]
> I mean you could go for New Chernobyl until it falls, but idk where you're gonna put it considering my town of Pripyat basically encompasses the entire CEZ

i know a nice place thats accurate to real life... at least i think

**Comment by ghost** [comment]
The towns/nations should fall automatically after 42 days of inactivity, but some has not been falling due to some bug.

Also please make issues like this on the issue tracker. EarthMC.net is our main website repo.

Edit: Use this repo's issue tracker to suggest change anything on our website.

**Comment by DasCodes** [comment]
@KarlOfDuty Towny issue.
