### ISSUE TITLE
[Suggestion] Lower griefing rules

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/EarthMC.net#45]
_imdoingthisforissue500_

Shouldn't have to be warned for breaking >10 blocks during a battle and not replace them. It's pretty damn obvious that unless it's a major grief, the player who reported it is a dick who wants to get people warned. Being more relaxed on these rules would stop feeding the dicks who report just to get enemies warned.

**Comment by Aitonater** [comment]
@CloakedEagle It's like playing the lottery with mods if you are reported or if you report someone. 
Every mod has a different interpretation of the rules and what punishments should be made.
The only thing you mods are consistent on is being inconsistent.
People will deliberately dm mods they trust on issues over making a ticket because they don't want to get shafted.

**Comment by FutureCW** [comment]
I’ll agree with Aitonater on that most staff have different interpretations of the rules on EMC. For example, John is the only mod that warns people for “Inciting racial slurs” which is how I assume he interprets the rule of toxicity. Though the main point of my post is that griefing needs to be more loosely enforced, meaning that if a grief could be reverted by a player within 5-10 minutes (dirt fort, some blocks broken, water/lava placed) should be up to the player to fix, and not the staff. This is what fuels the petty players by using staff as a tool to weaken their enemies. If a player makes some short walls during a battle to protect from arrows or something, is it really worth punishing that player for engaging in PvP and using strategies like building to their advantage?

**Comment by shirazmatas** [comment]
please follow format or the issue will be closed

**Comment by KarlOfDuty** [comment]
As stated above, you have to include the suggested change in your issue.
