### ISSUE TITLE
[Rules] Portal trapping not allowed

### ISSUE THREAD

**Issue by Chicken** [EarthMC/EarthMC.net#52]
**Exact wording of the rule** (not exact because I don't care enough, also it extends a rule. Not a new one)
Tp killing/trapping rule - netherportal trapping counts as tp killing/trapping.

**How will this rule affect the community**
Many people like me go to random portals in nether and then get stuck in them because they can't get back, can't, chat, and can't get out.

**Do you think this will benefit both the staff and the players**
Players won't get stuck.
Why should I care about staff? Atkeast people wouldn't come telling you to help.

**Comment by Chicken** [comment]
And ofc I misspell title.....and it's the only thing I can't edit.....

**Comment by KarlOfDuty** [comment]
Yes, this was stated in the toxicity rule before I guess it got removed when the jail stuff was put there instead.

**Comment by KarlOfDuty** [comment]
Closed by 3efc6d1f3ff38ebd661fd1f9f0eb2c78c1796ad3

**Comment by shirazmatas** [comment]
Please add portal trapping to the rules.
