### ISSUE TITLE
[Suggestion] End collective punishment

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/EarthMC.net#53]
Muting the entirety of chat and stopping us from speaking our minds is by far the dumbest thing I've ever seen. Treating us like children is so shitty and annoying to players trying to play the game. If staff are trying to mute the people who are acting like children, then FUCKING MUTE THEM! Why should people who aren't acting like retards be punished for something that they didn't do. When the staff muted chat today, it was worse after they unmuted than it was before they unmuted.

Here is the chat before the mute:
![beforemute](https://user-images.githubusercontent.com/46413791/58376410-d3cf8700-7f38-11e9-9863-f3c8edaeaac7.PNG)

Here is the chat after the mute:
![2019-05-25_22 00 48](https://user-images.githubusercontent.com/46413791/58376418-e9dd4780-7f38-11e9-9a55-ac4da5f5cb68.png)

What a surprise, the chat is way worse after the mute, as all those messages happened in the span of a couple seconds. I'm tired of the entirety of chat being muted for what a minuscule amount of players do. My goal for this issue is to show the ineffectiveness of muting all of chat and how it negatively effects the community by further developing the rapidly growing anti-mod feelings on EarthMC.

Edit: I'd also like to add that the newer staff need to chill with being trigger-happy on warns and bans. Need to be more relaxed in general tbh as warning everyone doesn't just fix the server.

**Comment by KarlOfDuty** [comment]
The mods have been told not to mute the chat as much.

It is supposed to be used for things like bot attacks or other times the chat is just going crazy with spam. It is not a punishment, it is there to make the chat usable again by splitting conversations into other chat channels when the global one is going too fast to read.
