### ISSUE TITLE
[Rule change 4.2] Adapt rule 4.2 to accomodate for large cities

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/EarthMC.net#57]
**Exact wording of the rule**
 4.2 Town and faction names.
Before creating a town or faction, make sure your name complies with the town naming. Names may be changed by a staff member if rule is not followed.

    Fictional town or faction names are allowed. However, we highly recommend towns to have a name tied to the real life town location.
    Town or faction name cannot be inappropriate/toxic/offensive.
    **Towns cannot have the same name as a nation, and must change even if the nation is made afterwards, excluding IRL cities.**
    Town or faction cannot have a similar name to already established town/faction to the point where one could easily be confused with the other.

**How will this rule affect the community**
It will allow the use of regional names for cities that cover a whole region, examples of this is: Wales, Berlin, London, and american states
**Do you think this will benefit both the staff and the players**
Yes, less disputes about illegal naming

**Comment by KarlOfDuty** [comment]
This doesn't seem to be relevant anymore with the current rules.
