### ISSUE TITLE
MODS SHOULD NOT BE ABLE TO SHOW ANY FORM OF BIAS

### ISSUE THREAD

**Issue by josfire18** [EarthMC/EarthMC.net#59]
**Exact wording of the rule**
Mods should not be able to show any form of bias.

**How will this rule affect the community**
When recently contacting the mods about getting a rule changed (ownership transfer when leader is banned) I was told by @Shirazmatas, Quote: "Mods do not have a say in this. If anything its more like shitty players considering your mayor got permabanned. Maybe next time find a better leader." THIS IS BLATANT BIAS. It's sickening.

**Do you think this will benefit both the staff and the players**
Staff may not benefit because they will ACTUALLY have to be neutral for once, but it will benefit the players tremendously. Or you will lose members as I post the screenshot everywhere I possibly can.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by shirazmatas** [comment]
Throw shit, you get shit

You called us all "shitty mods" so I thought you wanted to receive the same tone back. I don't even know you so why would this be biased? The only reaction I got from you is the so "polite" ticket that you opened and instantly called us shit for doing the same thing we do to all banned players: ignore their requests.

If anything thats the opposite of bias.

Also your request wasn't to change the rule, your request was to change who was the ruler. As stated I told you "Mods cannot and will not transfer ownership of towns from banned players, if you want it changed please post a rule change on the GitHub [link]" stop spewing lies

**Comment by Pengun78** [comment]
Shiraz dont curse!

**Comment by FutureCW** [comment]
Dude if you treat them like shit don’t expect them to get special treatment. If anything, you’ll be more likely to get muted and warned in chat

**Comment by josfire18** [comment]
This just highlights the issue even more. Threats of mutes and bans for standing up to the inequality? This just proves the point even more. Thanks for your comment.

Thank you,
Joey Rockwood
IT
Ext. 1134
________________________________

**Comment by daawesomemc** [comment]
"maybe next time find a better leader" How could people in a nation change the nation leader? From what I know, that isn't even possible. Is there some feature I don't know about?

**Comment by DasCodes** [comment]
I don't see how shiraz was biased on this. This is also not the place if you want to report staff abuse. But I would strongly advise not to behave rudely when you're seeking help from staff, we are contributing in our free time here, that doesn't justify to act rude against us for no reason. If you happen to believe that you were not treated right, seek another staff for advice or talk to the same mod asking the reason, I'm sure if you ask them nicely you won't be ignored.

**Comment by ghost** [comment]
:harold: Staff Abuse

**Comment by KarlOfDuty** [comment]
@josfire18 I recommend you don't use your email to respond to messages on the issues, your email client automatically added on some of your personal info at the end of your message.

**Comment by KarlOfDuty** [comment]
But also, moderators are allowed to have their own opinions and if you are being rude to them it is pretty natural they are not going to be very happy about it.

**Comment by josfire18** [comment]
It's just my signature. Only personal info not on my github or email is the extension which is no big deal. I'm mobile and didn't care about the sig info.

Thank you,
Joey Rockwood
IT
Ext. 1134
________________________________

**Comment by KarlOfDuty** [comment]
Ok, cool, just checking so it wasn't accidental.

**Comment by josfire18** [comment]
I appreciate it. BTW I know it's closed, but the bias I was speaking of was him saying the nation deserved it because of us having a shitty mayor. Regardless of what I said, that showed he had bias towards death and responded as such. I hope you guys can work on that at least.

Thank you,
Joey Rockwood
IT
Ext. 1134
________________________________

**Comment by BigBossBenja** [comment]
Thank you, Joey Rockwood IT Ext. 1134
