### ISSUE TITLE
Put "AFK FISHING NOT ALLOWED" really specific in the rules.

### ISSUE THREAD

**Issue by ghost** [EarthMC/EarthMC.net#6]
Players keep whining about afk fishing, just put it bolded in the rules that it's not allowed.

AFK : Away from keyboard
There is no way to afk fish without using a modification, as putting a weight on your mouse falls under that.

**Comment by ghost** [comment]
Please type -new in discord and ask about this there.

**Comment by KarlOfDuty** [comment]
1.1 Already addresses this.
