### ISSUE TITLE
New rule combatlogging

### ISSUE THREAD

**Issue by BillGates777** [EarthMC/EarthMC.net#61]
Please make a new rule, that says combatlogging is not allowed.
I can't count how many people I have attacked that just run away wait until there combat timer runs out and quit the game.

Example: Two people fight. The one person starts getting low on health and starts running. He than runs until his combattime runs out and quit.

**Comment by Sabatarge** [comment]
Billgates is from factions he isnt saying to add it to towny

30 seconds is plenty of time to kill your target and all damage resets the timer. Just get better with a bow or carry speed pots like everyone else
