### ISSUE TITLE
Is there any way to become mayor of an inactive town?

### ISSUE THREAD

**Issue by explodingmelons** [EarthMC/EarthMC.net#62]
Simply put, I'm the only active member of my town and the only councillor in my town. Once the previous mayor became inactive and who's data was deleted after 42 days I was expecting to become mayor since I was the last one on, however the mayor role was transferred to a player who hasn't been active for around 40 days. So my question is this: Is there any possible way I could become mayor since I'm the only active member in my town and essentially manage the town since there is no mayor?

**Comment by DasCodes** [comment]
Yes, when a mayor's data get deleted after 42 days of inactivity, Towny transfers the ownership to a random player. You'll have to wait till the ownership is passed down to you.

**Comment by explodingmelons** [comment]
rip, ah well then

**Comment by explodingmelons** [comment]
does it matter that I'm already a councillor?

**Comment by DasCodes** [comment]
Also, please make a ticket on our support discord, to request support on cases like this, and also this repository is used for issues on our website and the rules. For other issues, please use our issue tracker repository.

No, it does not matter whatever rank you have in the town.

**Comment by explodingmelons** [comment]
will do in the future, once I find where the support disc is

**Comment by DasCodes** [comment]
Check #info on EMC discord. @explodingmelons
