### ISSUE TITLE
Unauthorized Unclaiming Ban

### ISSUE THREAD

**Issue by alexwins2** [EarthMC/EarthMC.net#68]
Banning the use of unauthorized unclaiming

Unauthorized unclaiming: 
To unclaim land unauthorized by the mayor of a town will be considered a form of grief and will be punished accordingly and be undone

This will prevent councillors of towns from being paid off by another town/nation to unclaim a town and make dozens of people lose everything they have worked so hard on

I had a town called belgium that was completely unclaimed by a councillor i didnt even appoint, he was appointed by the previous owner. Almost 20 people lost everything they had spent months building, they will now most likely leave because of this. To save people from leaving a server I believe this is imperative to implement.

yes it will benefit both staff and players.
This rule provokes no negative consequences, it should be the mayors decision to unclaim land. It will also allow for less people to be unhappy; therefore, less people leaving, complaining, griefing.

**Comment by alexwins2** [comment]
I would like this rule to be retroactive so that the people from my town can stay on the server and be happy

**Comment by ImperialFishy** [comment]
This is not the place to complain about getting rekt emc has an element of conflict and you have to be careful who you trust.

**Comment by alexwins2** [comment]
I did not make him a councillor, he was already one when i bought the town

**Comment by alexwins2** [comment]
He essentially did it instantaneously as i got the town, I do not see any negative consequences to this rule

**Comment by alexwins2** [comment]
> This is not the place to complain about getting rekt emc has an element of conflict and you have to be careful who you trust.

this isnt about who i trust or about the "element of conflict" this is a form of grief

**Comment by ImperialFishy** [comment]
It is not. Read the rules. 

3.1	Destroying land around claims.
Players may not damage terrain around claims (griefing). Players breaking this rule will be warned and damage will be rolled back. Players doing this more than once may face a permanent ban. **Please note that mayors/kings are responsible for misconfigured town/nation permission settings.**

This is 100% your negligence buddy
