### ISSUE TITLE
There should be a lock system on doors and/or make the safe work on trapped chests

### ISSUE THREAD

**Issue by IGNSlaid** [EarthMC/EarthMC.net#7]
so, me and pengun and i guess more people in the server like building apartments for people, and right now we can set up a nice permission system but the thing is anyone can enter anyone's apartment at anytime. 
If the [safe] worked on doors, or there was a lock system on doors, or even if safe worked on trapped chests, we could set up a nice apartment system
 like> residents can switch but cant break, lock your door so you will be the only one who can access it and put your chests inside.

**Comment by KarlOfDuty** [comment]
This is irrelevant to the website.
