### ISSUE TITLE
Update Custom Crafting Recepies on earthmc.net/faq

### ISSUE THREAD

**Issue by MineTurtleBeach** [EarthMC/EarthMC.net#73]
Endrods (glowstone dust and white stained glass) and turning smooth sandstone to regular is not currently on the custom recipe section.

The new recipes at https://github.com/EarthMC/EMCRecipies/commit/172da87afb769870e6b71aebe2fd65f6c377df76 are not listed.

**Comment by anotherplayerofEMC** [comment]
Yeah.

**Comment by griffinht** [comment]
Also need to add vines and lily pads to the faq (these are currently in the game). Vines are (L L LLL L L). Lily pads are (L L LLL LLL). L is any type of leaf block.

**Comment by T0rn4do** [comment]
Shulker boxes recipe should be added too

**Comment by griffinht** [comment]
Shulker boxes aren't currently in the game. I'm not suggesting adding a new crafting recipe, I'm just suggesting adding the lily pad and vine recipe to the website as they are currently in the game

**Comment by DasCodes** [comment]
Only adding custom recipes that are currently in-game. @T0rn4do

**Comment by DasCodes** [comment]
I believe all the custom crafting recipes have been added there now. Also huge thanks to @jkmartindale.
