### ISSUE TITLE
[Feature] /plot reset

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/EarthMC.net#8]
I have many residents building unwanted houses while telling them to make them underground
some other towny servers have /plot reset which resets the plot to how it was (nature and no structures)
i would find this very handy and i bet other people would also

**Comment by NeonKrby** [comment]
If it resets shit what if you claim a chunk with 5g gold deposit claim it, mine it and then reset it again? Its a good idea on a server where gold isnt the currency but it doesnt work here.

**Comment by IGNSlaid** [comment]
krby has a point, if only the built structures were removed and ores replaced with stone... but this would be hard to set up

**Comment by Pengun78** [comment]
ok true i guess

**Comment by Pengun78** [comment]
What about the area above stone

**Comment by Pengun78** [comment]
@KarlOfDuty

**Comment by KarlOfDuty** [comment]
What does this have to do with the website?
