### ISSUE TITLE
[Feature] Nether Rules

### ISSUE THREAD

**Issue by DCDylanc123410** [EarthMC/EarthMC.net#83]
**Is your feature request related to a problem? Please describe.**
I run the International Nether Transit which goes to 20+ portals and is growing everyday. As you know the nether is in the wildness. This leads to grief, pvp, etc. This can hurt the INT and cause us to have to dump in more resources than necessary. The INT is gonna grow and spread to hundreds of portals across EMC Towny. This transportation system can bring you across continents within 3 minutes just by running alone. 

**Describe the solution you'd like**
So I have a few solutions. These are in no particular order:

- Option 1: There is a rule saying specifically that players are not allowed to grief any highways or nether hubs. Rule 3.2 currently states, "Wilderness is defined by Towny as any land not currently claimed. You are allowed to grief structures or terrain as long as they are not within or in close proximity to a claimed area. However, any player may request major terrain grief to be rolled back even in the wilderness. Breaking railways or ice roads is not allowed even in the wilderness, if willingly connecting two existing towns. This does not only apply to the rails but all blocks the railroad is made of." I was thinking make a rule or add to this rule so that it is clear that the nether is also protected by this rule. This will allow people to be able to get their portal, highway, or nether hub rolled back if needed. The problem with this is that Mods will have to take more of their time to have to deal with Nether griefs along with over world griefs

- Option 2: Allow the nether to be claimed for a higher price than the overworld. Im talking like 64 gold a chunk or something. This will allow nations and towns to be able to claim areas of the nether for shops and nether hubs and such. There wouldn't be towns and nations in the nether persay but maybe like resident outposts or something. Or make it so that explosions and pvp only can be disabled but allow everybody to still build and switch and stuff

- Option 3: Make the entire nether a special type of wildness with its own toggles and rules to keep it separate from the overworld wildness. This will allow for people to have rules for the overworld wildness exclusively and the nether wildness exclusively

All of these options have their pros and cons. I personally like Option 1 the best but I gave you guys other options just encase. 

**Additional context**
Here is the International Nether Transit Discord if you guys need more information about it.
https://discord.gg/Ds4ySe3

Also my Discord is DCDylanc123410#2641 if you need to contact me. Thank you all for your time and putting up with all of us. I hope you guys consider my new rule and we can help create something great. Thank you and have a nice day!

**Comment by KarlOfDuty** [comment]
I think we will be going by the first option, and as the rules currently do not specify world it should already be the case.
