### ISSUE TITLE
Disregard for all rules

### ISSUE THREAD

**Issue by VonApollo** [EarthMC/EarthMC.net#84]
Players who openly break rules knowingly and deliberately will face a permanent ban

This rule would be better for the community for multiple reasons, less griefers and rule breakers. There are many organizations that actively break the rules because they know they won't get any consequences until their final warning, so people who know that they are breaking the rules, do it because it isn't their final warning yet deserved to be banned because its clear that they aren't going to change their behavior even after a warn, here is an example. A group likes griefing, most of their members have openly broken the rules and have warnings, they do not care about the rules at all and only abide them because they do not want to be banned.

Staff and players can benefit from this as this can greatly decrease the the amount of rule-breakers and people who actively try to make the community a worse place by breaking the rules, players do not have to worry about continuous griefs due to the culprits not being banned and staff do not have to constantly rollback the environment.

**Comment by FranchuFranchu** [comment]
a permaban seems a lot. Maybe a really long ban

**Comment by KarlOfDuty** [comment]
I think we will keep the punishments as they are.
