### ISSUE TITLE
Tried to join factions, cant

### ISSUE THREAD

**Issue by Terrariawizz** [EarthMC/EarthMC.net#88]
I went to log on to Minecraft to play with my friends and I pressed factions but it lined up for the queue for towny instead. I'm confused what do I do now?

**Comment by DasCodes** [comment]
Yes, atm when you join the hub it automatically queues you up for towny. You can either leave the queue with `/leavequeue` and `/joinqueue factions` or you can directly join the factions with factions.earthmc.net. @Terrariawizz
