### ISSUE TITLE
[Feature] towns named to provinces

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/EarthMC.net#9]
I saw that new rule about nations being renamed to provinces
It would be weird if a town could be renamed as a province too
For example the town catalonia in the nation catalonia

**Comment by NeonKrby** [comment]
Also like, Think of City States like Singapore and the greatest nation Sealand. They have to be named what they are both if they make a town and nation.

**Comment by KarlOfDuty** [comment]
> Town cannot be named after a region which qualifies as a nation name.

Should suffice.
