### ISSUE TITLE
[Rule change 4.1] Allow former and current unions to be used as nation name & Australia

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/EarthMC.net#90]
**Exact wording of the rule**

> Before creating a nation, make sure your name complies with the nation naming rules. Nation names may be changed by a staff member if rule is not followed and may be disbanded if the rule is repeatedly broken.

    Nation name cannot be fictional. It has to have the same name as a current or past nation.
    Nation can be named after region, province or other large geographical area with defined borders if accurate nation name is already taken.
    Nation name must correspond with map location of the nation capital.
    Nation cannot have a similar name to already established nation to the point where one could easily be confused with the other.
    Nation cannot be named after alliances.
    Nation cannot be named after a continent (except Australia).

**How will this rule affect the community**
Allow countries/nations that used to be unions/are unions be able to be used as nation names.
Ex of current and previous unions:
Australia, Bosnia & herzegovina, Cameroon, Canada, German empire, India, Malaysia, Pakistan, Serbia & montenegro, Switzerland, Tanzania, UAE, UAR, USSR (soviet union), UK, USA

Allows Australia to exist
**Do you think this will benefit both the staff and the players**
Yes, less tickets and more options for players.

**Comment by GreenGuyyy** [comment]
Australia isn’t a union

**Comment by NeonKrby** [comment]
Australia doesnt exist smh

**Comment by KarlOfDuty** [comment]
Basically all of the ones you mentioned are already allowed, we will likely not change this at this time.

**Comment by shirazmatas** [comment]
Not according to rules but okay boomer
