### ISSUE TITLE
Add a rule for hollow claims, update 3.3 claimblocking. Allow mods to remove claim arms without a ticket.

### ISSUE THREAD

**Issue by ghost** [EarthMC/EarthMC.net#92]
Hollow claims are claims which have been made in a circle or a square. On the dynamic map these claims appear whole and appear to be part of the town which has created them. There are two issues: 1. the rules need to specifically state "hollow claims" as well as claim arms and 2. it needs to be easier for mods to remove and report claim arms or hollow claims.

1. The rules need to be updated to specifically state "hollow claims". There is a lot of contention and confusion among staff and the player base as the rules talk about claim arms but not hollow.
The hollow claims are removed when tickets are made however many players aren't aware they constitute a break in the rules.

2. Only towns which are close to the hollow claims or claim arms -may actually report them. If you play on the server you are probably aware of several large towns with hollow claims or massive claim arms that operate without impunity. This is because for the claims to be removed you have to have a town near them in order to raise an action. What has ended up happening as a result of this is players are deliberately making brand new towns inside claims just so they can report them and have them removed.

I think it should be worded like this:
"A town's claims count as blocking if they create hollow claims or long arms of claims protruding from their town like in the images above. These arms/hollow claims are an issue as they do not only block existing towns but also take up large areas where future towns could otherwise be created."

The original:
"A town's claims count as blocking if they create long arms of claims protruding from their town like in the images above. These arms are an issue as they do not only block existing towns but also take up large areas where future towns could otherwise be created."

I also think this:
"Only mayors of towns being claim blocked may report breaking the rule as claiming along someone's border is fine if all involved towns agree on it."

Should be changed to this:
"Only mayors of towns being claim blocked may report breaking the rule as claiming along someone's border is fine if all involved towns agree on it. However, if a town has blocked a large area using a claim arm or a hollow claim which is stopping others from claiming the area or making a new town mod's may remove the claims."

I'm only saying this because VladThyInhaler's town had lots of claims removed when someone made a town inside his claims. At the same time Mobile in the US is a huge hollow claim, it it was the actual number of chunks as the hollow claim it is it would surpass all other towns on the server by far.

The reason why I think mods should be able to remove these claims is because some players are being punished for breaking this rule while others are totally unaffected when they break it. Those people are only punished when a player and not a mod spends 64 gold to make a town inside the hollow claims or close to the claim arm. 

Another issue that arises from the rules is deciding what takes priority. Making a town too close to another town is claimblocking, but having hollow claims is also claimblocking? So in a ticket what comes first?

**Comment by ghost** [comment]
Here are some examples of claim arms and hollow claims which exist if you didn't think it was a problem:
![town 4](https://user-images.githubusercontent.com/47613294/73711531-11f38c00-46ff-11ea-877b-b8906609a253.PNG)
![town 1](https://user-images.githubusercontent.com/47613294/73711533-128c2280-46ff-11ea-8df4-7f249aff4e17.PNG)
![town 2](https://user-images.githubusercontent.com/47613294/73711534-128c2280-46ff-11ea-96fc-220d041e57af.PNG)
![town 3](https://user-images.githubusercontent.com/47613294/73711535-128c2280-46ff-11ea-9176-46bbeddc9064.PNG)

**Comment by ghost** [comment]
A tl;dr version:

- Hollow claims are illegal as they block land which could be used by neighboring  or new towns.

- It is illegal to create a new town within a hollow claim, to then try and report it.

- Only neighboring mayors may report hollow claims as claim arms and claim blocking. But, if all neighbors agree... large areas of land can be secured for a fraction of the cost.

- On top of all that, it isn't explicitly stated in the rules that hollow claims are not allowed.

Why is this a problem?
Hollow claims are illegal and the player-base doesn't know that they are. People who do have them and block large areas cannot be reported by new towns which would like to settle in the area. So essentially you have players hoarding massive areas of land they cannot claim breaking a rule (which doesn't explicitly exist).

**Comment by ghost** [comment]
![90111509_232375537943161_1810180732165816320_n](https://user-images.githubusercontent.com/47613294/77006095-c49f4700-6959-11ea-99cf-eaa70e1f1251.jpg)

The mod CorruptedGreed has said this which completely contradicts the rule:
These arms are an issue as they do not only block existing towns but also take up large areas where future towns could otherwise be created."

**Comment by ghost** [comment]
@DasCodes have you had the chance to look at this yet?

**Comment by ghost** [comment]
"Tickets are necessary for issues like these due to the documentation they require. Also for keeping track of both sides of the issue. As it stands, hollow claiming is legal as long as it does not interfere with the expansion of nearby pre-existing towns. There may be the possibility of a nearby town eventually requesting nearby hollow claimed land to be removed in order for their town to access and expand into it, but that depends on the specific circumstances. For instance, if you have an area with towns in the same nation that are in an agreement of sorts, hollow claiming is allowed as long as all the neighboring towns approve. This can result in groups of players holding a monopoly over land, but as Fix said to me earlier, this is aspect is currently not being enforced (hollow claims and the potential free land they occupy). It is only punishable when they are used to block pre-existing towns, usually by utilizing the tactic to lock down far-fetched future claims with little resources in the presence of other towns looking to expand as well." Update the rule so it says this or something like this.

**Comment by shirazmatas** [comment]
please follow format for rule suggestion
