### ISSUE TITLE
Changing to rule 1.1

### ISSUE THREAD

**Issue by Biteof87** [EarthMC/EarthMC.net#96]
**Rule 1.1**
Cheat clients, macro keys and other modifications which give the player gameplay leverage over other players are not allowed. Players found breaking this rule will face a temporary 30 day ban, If they are caught hacking again then they will face a permanent ban, and permanent means permanent. Also you can face a permanent ban for malicious hacks like Server lagger or crasher or any other hacks which affect the actual server.

**How will this rule affect the community**
I think that this will have benefits to the community by first people who have had there accounts cracked have another chance, people are giving a second chance lowing the amount of unban tickets, also people who did it absent minded for fun and later regret it have another chance to integrate into society

**Do you think this will benefit both the staff and the players**
I think also staff will benefit because if people are given a second chance and then banned for hacking again, there point is less valid because they clearly were warned, also if less people are being banned and having another chance there could be less un-ban tickets for moderators to go through meaning less work for them.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by ghost** [comment]
No fuck this. I'm sorry but hackers can cause huuuge amounts of damage. And proving whether someone's account was stolen during the hacking is very hard to prove. It should just be a straight up ban to protect the server and the community.

**Comment by Biteof87** [comment]
But there's different types of hacking and I think its unfair that all hackers should be put in the same category some improve your stats like speed, flying, or kill aura, others like server crasher or server lagger does do harm to the server so I understand why people doing those hacks should be first perm banned but I think that your punishment should be based on your hack not if you hacked or not. You said that hackers can cause huuuge amounts of damage, But I don't think speed hacking should get the same punishment as server crashing

**Comment by AmphireYT** [comment]
> But there's different types of hacking and I think its unfair that all hackers should be put in the same category some improve your stats like speed, flying, or kill aura, others like server crasher or server lagger does do harm to the server so I understand why people doing those hacks should be first perm banned but I think that your punishment should be based on your hack not if you hacked or not. You said that hackers can cause huuuge amounts of damage, But I don't think speed hacking should get the same punishment as server crashing

Bruh kill aura is useless its going to do like no damage cuz we in 1.15.2 and i agreee with bite. If like there just zoomin thru the land, yes ban them for 30 days but if there lagging the server yes ban then permanently.

**Comment by Biteof87** [comment]
that's what I'm saying I think that hacks like speed should be temp and if done again perm and malicious ones like server crasher should be perm

**Comment by AmphireYT** [comment]
> that's what I'm saying I think that hacks like speed should be temp and if done again perm and malicious ones like server crasher should be perm

Yes

**Comment by Biteof87** [comment]
so why you dislike this cuz I'm saying what your saying

**Comment by Biteof87** [comment]
that why u should upvote cuz thats what I want cuz on earth you get perm banned for speed hacks

**Comment by KarlOfDuty** [comment]
We will not be changing this rule at this time.
